C     END SUBROUTINE RESORTO2


C      CALL ARCHOICE(NUMTEACH,NEWMAT,RCHOICE,PWEIGHTS,MAXCH)
      SUBROUTINE ARCHOICE(NUMTEACH,NEWMAT,RCHOICE,
     C MAXCH,FIXR,HIFLAG,MEANW,VARW)
      INCLUDE 'PARAM.H'
      INTEGER RCHOICE(MAXKLIQ),NUMTEACH,S,R3,R2,NEWMAT(MAXKLIQ,MAXKLIQ),
     C MAXCH,HIFLAG,MAXR,V
      REAL OBS(MAXKLIQ),VARW(MAXKLIQ),MEANW(MAXKLIQ),FIXR,SUMW(MAXKLIQ),
     C TR


      DO 30 S=1,NUMTEACH
       RCHOICE(S)=0
   30 CONTINUE
C      WRITE(27,140) "R IS ZERO"
        MAXR=0
        MAXCH=-99
       HIFLAG=0
      DO 32 R3=1,NUMTEACH
        SUMW(R3)=0
        VARW(R3)=0
        MEANW(R3)=0
        DO 33 R2=1,NUMTEACH
         IF (NEWMAT(R3,R2) .GT. 0) THEN 
            RCHOICE(R3)=RCHOICE(R3)+1
            SUMW(R3)=SUMW(R3)+NEWMAT(R3,R2)
            OBS(RCHOICE(R3))=NEWMAT(R3,R2)
         END IF
         IF (NEWMAT(R3,R2) .GT. MAXCH) THEN
           MAXCH=NEWMAT(R3,R2)
         END IF
   33   CONTINUE
       IF (RCHOICE(R3) .GT. MAXR) THEN
         MAXR=RCHOICE(R3)
         END IF
       IF (RCHOICE(R3) .GT. 0) THEN
        TR=RCHOICE(R3)
         MEANW(R3)=SUMW(R3)/RCHOICE(R3)
       DO 29 V=1,RCHOICE(R3)
       VARW(R3)=VARW(R3)+((OBS(V)-MEANW(R3))**2)/TR
00029   CONTINUE
       END IF
   32  CONTINUE

         IF (MAXR .GT. FIXR) THEN
         HIFLAG=1
         END IF
         FIXR=MAXR

       RETURN 
       END
