C     END SUBROUTINE ASSIGN
C

      SUBROUTINE ASSIGN2(SUBJECTS,KAFFIL,MAXGROUP,
     C COUNTGR)

CASSIGNM,ASSIGNV,
C
C                         X          X             X                        
C        CALL ASSIGN2(NUMTEACH[I] ,NEWDEPT[I251] ,MAXDEPT[I] 
C              X
C       ,ALLGROUP[I251,251]
C          X             X              X
C    C  ,DEPARTN[I251],RCHOICE[I251],ALLGROUR[I251,251]
C     ,MEANWT[R251] ,VARWT[R251],
C     C  1,2)
      INCLUDE 'PARAM.H'

      INTEGER SUBJECTS,KAFFIL(MAXKLIQ),MAXGROUP,
     C        COUNTGR(MAXKLIQ)
      INTEGER C,IG,ADEPART,TSUBJECT
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ASSIGNG(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ),
     C ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ASSIGNG,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

C      REAL MEANW(MAXKLIQ),VARW(MAXKLIQ)
C     C   ASSIGNM(MAXKLIQ,MAXKLIQ),ASSIGNV(MAXKLIQ,MAXKLIQ)
C           ASSIGNV(ADEPART,COUNTGR(ADEPART))=VARW(IG)
C   
C      ASSIGN PEOPLE TO DEPARTMENTS ACCORDING TO THEIR INPUT DATA
C
C         NUMTEACH = TOTAL NUMBER OF TEACHERS
C         DEPART IS BASED ON THE INPUT DATA
C         ADEPART IS A TEMPOARARY NUMBER FOR THE DEPARTMENT
C         MAXDEPT IF THE MAXIMUM NUMBER OF DEPARTMENTS
C         DEPARTN IS AN ARRAY OF THE DEPARTMENTAL SIZES
C         ALLGROUP IS AN ARRAY OF DEPARTMENTS BY PEOPLE IN 
C            THE DEPARTMENTS (AHH FOR A PASCAL POINTER)
C
C
C        CALL CHECKVAL(INMAT,SUBJECTS,P1,P2,'BEGIN ASSIGN')

       DO 20 C=1,MAXGROUP
       COUNTGR(C)=0
   20  CONTINUE
C

       TSUBJECT=SUBJECTS+1
       DO 23 IG=1,SUBJECTS
C           WRITE(330,777) IG,KAFFIL(IG)
C         IF (KAFFIL(IG) .EQ. 0) THEN
C           KAFFIL(IG)=1
C          END IF
           ADEPART=KAFFIL(IG)
           IF (MAXGROUP .LT. ADEPART) THEN 
             MAXGROUP=ADEPART
           END IF
           IF ((ADEPART .GE. 1) .AND. (ADEPART .LT. MAXKLIQ)) THEN
           COUNTGR(ADEPART)=COUNTGR(ADEPART) + 1
           ASSIGNG(ADEPART,COUNTGR(ADEPART))=IG
C           ASSIGNR(ADEPART,COUNTGR(ADEPART))=INCHOICE(IG)
C           ASSIGNM(ADEPART,COUNTGR(ADEPART))=MEANW(IG)
C           ASSIGNV(ADEPART,COUNTGR(ADEPART))=VARW(IG)
           END IF
C           WRITE(17,117) IG,KAFFIL(IG),MAXGROUP,COUNTGR(ADEPART)
   23   CONTINUE
  117 FORMAT('PERSON=',F4.0,' DEPT=',F4.0,' MAXD=',F4.0,' DC=',F4.0)
  777 FORMAT('PERSON=',I3,' DEPART=',I3)
C
      RETURN
      END
