
C      CALL ATTACHO2 (CHANGEC,STOPVAL,LOWMEM,NUMTEACH,
C     C MADECHNG,ISO,ISOLIST,NEWDEPT,MEANWT,VARWT,WPIK,
C     C ALLGROUM,ALLGROUV,NEARVAL,ALLGROUR,DEPARTN,MAXDEPT,
C     C ALLGROUP,RCHOICE,NEWMAT,DMEMBERS,QUITIT,LASTCHNG,NSUBID,
C     C TITLES,DEBUG)

      SUBROUTINE ATTACHO2 (CHANGEC,STOPVAL,LOWMEM,NUMTEACH,
     C MADECHNG,ISO,ISOLIST,NEWDEPT,MEANWT,VARWT,WPIK,
     C NEARVAL,DEPARTN,MAXDEPT,
     C RCHOICE,DMEMBERS,QUITIT,LASTCHNG,NSUBID,
     C ATITLE,HYPERG)
      INCLUDE 'PARAM.H'
C        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,ALLGROUP
C     C  ,DEPARTN,RCHOICE,ALLGROUR,MEANWT,VARWT,ALLGROUM,ALLGROUV)


      CHARACTER ATITLE(3)*20
      REAL AVAR2,MEANWT(MAXKLIQ),VARWT(MAXKLIQ),WPIK,NOB
      INTEGER CHECK,FIXIT,P,P2


      DOUBLE PRECISION SUMCLOSE
      REAL CHOSEMN(MAXKLIQ),
     C CHOSEVR(MAXKLIQ),AMEAN,AVAR,
     C TOTE,TOTCON,TOTV,UTOTCON
      REAL CDEPT,NEARVAL,BESTD(MAXKLIQ),CHANGEC(MAXKLIQ),
     C NOWCLOSE(MAXKLIQ),LOWCOMP,STOPVAL,LASTCHNG,ALLC(MAXKLIQ,MAXKLIQ)
C
      INTEGER LOWMEM,NUMTEACH,ISO,ISOLIST(MAXKLIQ),NSUBID(MAXKLIQ),
     C DEPARTN(MAXKLIQ),NEWDEPT(MAXKLIQ),MAXDEPT,
     C RCHOICE(MAXKLIQ),MADECHNG,
     C Z,IDD,BJ,NUMIN,HYPERG

 
      INTEGER SKIPIT,DMEMBERS(MAXKLIQ),THISMEM,TEMPS,OLDLOWM,
     C FOUNDONE,NEWMEMS(MAXKLIQ),OLDDEPT,LDEPART,LDEPTN,NGROUP,
     C THED(MAXKLIQ),NOPICK,DNUM(MAXKLIQ),ONLIST(MAXKLIQ),AB,ON,
     C KNODO,KSTOP,KCOUNT
       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ),MT,VT
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT

  
       WRITE(33,102) 'ATTACH'
       ON=1
       DO 666 AB=1,NUMTEACH
       ISOLIST(AB)=0
       IF (NEWDEPT(AB) .LT. 1) THEN
         ONLIST(ON)=AB
         ON=ON+1
       END IF
  666    CONTINUE
      ON=ON-1
      KNODO=0
      IF (ON .LT. 1) THEN 
      KNODO=1
      END IF
      IF (KNODO .EQ. 0) THEN
      NOB=1.00000
      MADECHNG=1
      OLDLOWM=0
      ISO=1
      ISOLIST(1)=0
      LOWMEM=1  
      CHANGEC(LOWMEM)=MAXKLIQ
      BJ=0
       KCOUNT=1
      KSTOP=0
      DO WHILE ((KCOUNT .LT. MAXKLIQ) .AND. (KSTOP .EQ. 0))
      KCOUNT=KCOUNT+1
      LASTCHNG=CHANGEC(LOWMEM)
      LOWCOMP=-200.000
      NOPRINT=0
      NUMIN=0
      SUMCLOSE=0.0 
      DO 28, IDD=1,ON
       I=ONLIST(IDD)
       IF (NEWDEPT(I) .LT. 1) THEN
       SKIPIT=0
       IF (MADECHNG .EQ. 0 )THEN
         NOPRINT=1
         DO 18 CHECK=1,ISO
          IF (I .EQ. ISOLIST(CHECK)) THEN
            SKIPIT=1
          END IF
   18    CONTINUE
        ELSE
         DO 19 FIXIT=1,ISO
          ISOLIST(FIXIT)=0
   19    CONTINUE
         ISO=1
       END IF
       IF (SKIPIT .EQ. 0) THEN
       BESTD(I)=-10.0
       THED(I)=NEWDEPT(I)
      DO 34 J=1,MAXDEPT
         CHOSEMN(J)=0.000
         CHOSEVR(J)=0.00
       DO 40 K=1,DEPARTN(J)
         THISMEM=ALLGROUP(J,K)
         DMEMBERS(K)=THISMEM
C WORKING K

         IF (THISMEM .GT. 0) THEN
         IF ((THISMEM .NE. I) .AND. (RCHOICE(THISMEM) .GT. 0)) THEN
C      SUBROUTINE DISTRIB (THISR,THISWM,THISWV,MEAN,TVAR,KGRPSIZE,
C     C           TOTSIZE,THISPER)
         CALL DISTRIB (RCHOICE(THISMEM),MEANWT(THISMEM),
     C    VARWT(THISMEM),AMEAN,AVAR,2,NUMTEACH,THISMEM,AVAR2,HYPERG)
         CHOSEMN(J)=CHOSEMN(J)+AMEAN
         CHOSEVR(J)=CHOSEVR(J)+AVAR
         END IF
         END IF

   40  CONTINUE
C      SUBROUTINE HOWMANY (MEMBERS,KGRPSIZE,INDIV,PATTERN,TOTSIZE,
C     C                  TOTCON,GROUP,WEIGHT,WTB)
         CALL HOWMANY (DMEMBERS,DEPARTN(J),I,NEWMAT,NUMTEACH,
     C                  TOTCON,J,WPIK,NOB,UTOTCON,MT,VT)
         IF (TOTCON .GT. 99) THEN 
         END IF
         TEMPS=DEPARTN(J)
         IF (NEWDEPT(I) .NE. J) THEN
         TEMPS=TEMPS+1
         END IF 
         IF (DEPARTN(J) .EQ. 1) THEN
         TEMPS=2
         END IF

           AMEAN=0.000
           AVAR=0.000
         IF (RCHOICE(I) .GT. 0) THEN 
           CALL DISTRIB (RCHOICE(I),MEANWT(I),
     C      VARWT(I),AMEAN,AVAR,TEMPS,NUMTEACH,I,AVAR2,HYPERG)
         END IF
            TOTE=CHOSEMN(J)+AMEAN
            TOTV=CHOSEVR(J)+AVAR
         CDEPT=(TOTCON-TOTE)/(TOTV**.5)
         ALLC(I,J)=CDEPT
        IF (J .EQ. NEWDEPT(I)) THEN
         NOWCLOSE(I)=CDEPT
         SUMCLOSE=SUMCLOSE+CDEPT
         NUMIN=NUMIN+1
         IF (DEPARTN(NEWDEPT(I)) .LT. 2) THEN 
         SUMCLOSE=SUMCLOSE-CDEPT
         NUMIN=NUMIN-1
          NOWCLOSE(I)=0.0
          ALLC(I,J)=0.0
          DUMBO=0
         END IF
        END IF
        IF (CDEPT .GT. BESTD(I)) THEN
         THED(I)=J
         BESTD(I)=CDEPT
         END IF
C FIRST CLOSEDEP
   34 CONTINUE
       CHANGEC(I)=BESTD(I)-NOWCLOSE(I)
       IF (CHANGEC(I) .GT. LOWCOMP) THEN
        LOWCOMP=CHANGEC(I)
        LOWMEM=I
       END IF
      END IF
      END IF
   28 CONTINUE
    
        NOPRINT=1
      OLDLOWM=LOWMEM       
        IF (NOPRINT .EQ. 0) THEN
        DO 80 Z=1,MAXDEPT
          IF (DEPARTN(Z) .GT. 0) THEN
          WRITE(33,133) Z , (NSUBID(ALLGROUP(Z,P)) , P=1,DEPARTN(Z))
          WRITE(33,134) DEPARTN(Z),
     C         (NOWCLOSE(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,137) 'BEST G',
     C         (BESTD(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,137) 'GROUP',
     C         (THED(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
         END IF
   80   CONTINUE
        END IF
        WRITE(33,139) LOWMEM,NEWDEPT(LOWMEM),THED(LOWMEM)
C
C
C       NOW I HAVE FOUND THE BEST PERSON TO CHANGE (LOWMEM) AND THE 
C        BEST DEPARTMENT FOR THAT PERSON THED(LOWMEM)
C        AND THE DISTANCE TO THAT DEPARTMENT (BESTD(LOWMEM))
C        IS IT GOOD ENOUGH? 
C
        WRITE(33,251) LOWMEM,THED(LOWMEM),ALLGROUP(THED(LOWMEM),1),
     C  RCHOICE(ALLGROUP(THED(LOWMEM),1)),DEPARTN(THED(LOWMEM)),
     C NOPICK

         NOPICK=0
      IF ((RCHOICE(LOWMEM) .EQ. 0) .AND. 
     C   (DEPARTN(THED(LOWMEM)) .LT. 2)) THEN
         NOPICK = 1
         DUMBO=0
      END IF
      IF ((DEPARTN(THED(LOWMEM)) .LT. 2)  .AND. 
     C    (RCHOICE(ALLGROUP(THED(LOWMEM),1)) .LT. 1)) THEN
       NOPICK=1
       DUMBO=0
      END IF
        IF ((NOPICK .EQ. 1) .OR. (LOWMEM .LT. 1)) THEN
        MADECHNG=0
        ISOLIST(ISO)=LOWMEM
        ISO=ISO+1
        WRITE(33,251) LOWMEM,DEPARTN(THED(LOWMEM)),
     C  RCHOICE(LOWMEM),RCHOICE(ALLGROUP(THED(LOWMEM),1))
       ELSE
      IF ((BESTD(LOWMEM) .GT. NEARVAL) .AND. (THED(LOWMEM) .NE. 
     C NEWDEPT(LOWMEM))) THEN
          MADECHNG=1
          BJ=BJ+1
          LONER=0
          OLDDEPT=NEWDEPT(LOWMEM)
          LDEPART=NEWDEPT(LOWMEM)
          LDEPTN=DEPARTN(NEWDEPT(LOWMEM))
          NEWDEPT(LOWMEM)=THED(LOWMEM)
          DEPARTN(THED(LOWMEM))=DEPARTN(THED(LOWMEM))+1
         ELSE
             KSTOP=1
             MADECHNG=0
             ISOLIST(ISO)=LOWMEM
             ISO=ISO+1
              WRITE(33,251) LOWMEM,BESTD(LOWMEM),THED(LOWMEM),
     C       NEWDEPT(LOWMEM)
         END IF
        END IF
      IF (MADECHNG .EQ. 1) THEN

        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN,RCHOICE,MEANWT,VARWT,
     C  I,THISMEM)
        WRITE(33,136) LOWMEM,OLDDEPT,NEWDEPT(LOWMEM)
        WRITE(33,132) 
      END IF
C    1 CONTINUE
       END DO
       DO 88 Z=1,NUMTEACH
       IF (NEWDEPT(Z) .EQ. 0) THEN 
        MAXDEPT=MAXDEPT+1
        NEWDEPT(Z)=MAXDEPT
       END IF
   88     CONTINUE
      END IF
        DO 82 Z=1,MAXDEPT
          IF (DEPARTN(Z) .GT. 0) THEN
          WRITE(33,133) Z , (ALLGROUP(Z,P) , P=1,DEPARTN(Z))
          WRITE(33,133) Z , (NSUBID(ALLGROUP(Z,P)) , P=1,DEPARTN(Z))
          WRITE(33,134) DEPARTN(Z),
     C         (NOWCLOSE(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,137) 'BEST G',
     C         (BESTD(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,137) 'GROUP',
     C         (THED(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
           END IF
          DNUM(Z)=Z
   82   CONTINUE
       RETURN
  144 FORMAT(2F10.5)
  251 FORMAT(20(F10.5))
  103 FORMAT(20(F6.2,2X))  
  102 FORMAT(10(A30)) 
  101 FORMAT(20(A8)) 
  132 FORMAT('DEPART    MEMBERS')
  133 FORMAT(I4,4X,251(I6,4X))
  134 FORMAT('(',I4,')',4X,251('(',F8.3,')'))
  137 FORMAT(A6,4X,251('(',F8.3,')'))
  136 FORMAT('HAVE MOVED ',I4,' FROM ',I4,' TO ',I4)
  139 FORMAT('WANT TO MOVE ',I4,' FROM ',I4,' TO ',I4)
      END
