
      SUBROUTINE BSPAN(DIFF,NUMTEACH,MAXDEPT,BOUND,CHANGEC,NEWDEPT,
     C ATITLE,XTITLE1,XTITLE2,DEPARTN,NSUBID,INFILE,ABBREV,TYPE,ADDEND,
     C NSIM,PRINTK)
      INCLUDE 'PARAM.H'
      INTEGER NUMTEACH,MAXDEPT,CHANGEC(MAXKLIQ),ID,COUNTG(MAXGR),
     C IB,JB,NEWDEPT(MAXKLIQ),TJB,BOUNDG(MAXGR,MAXKLIQ),ADDEND,
     C DEPARTN(MAXKLIQ),PERS,NSUBID(MAXKLIQ),GROUP,TG,THISPER,NSIM,
     C GR,ABBREV,PRINTK,TCOUNTG(MAXGR)

      REAL DIFF(MAXKLIQ,MAXKLIQ),BOUND
      CHARACTER ATITLE(3)*20,INFILE*16,XTITLE1*16,XTITLE2*16,TYPE*1,
     C BFILE*13,BFILE2*14,TBFILEB*11

      REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)

       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ),BG,ZG,A
       REAL TBLAUC(MAXKLIQ,MAXKLIQ),TDIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C TBLAUC,TDIFF

      BFILE=INFILE(1:6) // '.bound' // TYPE 
      OPEN(20,file=BFILE)
      BFILE=INFILE(1:6) // '.bndat' // TYPE
      OPEN(23,file=BFILE)
      IF (ADDEND .EQ. 1) THEN
      CALL MOVEEND(20)
      CALL MOVEEND(23) 
      END IF
        DO 00087 ID=1,MAXDEPT
         COUNTG(ID) = 0
00087     CONTINUE

         DO 8247 IB=1,NUMTEACH
         DO 8248 JB=1,MAXDEPT
C            JB=CHANGEC(TJB)
            IF (NEWDEPT(IB) .NE. JB) THEN
            IF (DIFF(IB,JB) .GT. BOUND) THEN
              COUNTG(JB)=COUNTG(JB) + 1
              BOUNDG(JB,COUNTG(JB))=IB
            END IF
            END IF
08248      CONTINUE
08247       CONTINUE


         WRITE(20,102) (ATITLE(A) , A=1,3)
         WRITE(20,102) XTITLE1,INFILE
         WRITE(20,2107) XTITLE2,
     C       (CHANGEC(IB) , IB=1,MAXDEPT)
         WRITE(20,2107) 'GROUP SIZE',
     C   (DEPARTN(IB) , IB=1,MAXDEPT)
         WRITE(20,101) '  ACTOR' , '  GROUP', '    CONNECT'

        DO 84 GROUP=1,MAXDEPT
        TG=CHANGEC(GROUP)
         DO 85 PERS=1,DEPARTN(GROUP)
        THISPER=ALLGROUP(GROUP,PERS)
         WRITE(20,2103) NSUBID(THISPER),GROUP,
     C   (DIFF(THISPER,CHANGEC(GR)), GR=1,MAXDEPT)
         WRITE(23,21033) NSIM,PRINTK,NSUBID(THISPER),GROUP,
     C   (DIFF(THISPER,CHANGEC(GR)), GR=1,MAXDEPT)
   85    CONTINUE
   84   CONTINUE

        CLOSE(20)
        CLOSE(23)
      BFILE2=INFILE(1:6) // '.bound' // TYPE // '2'
      OPEN(20,file=BFILE2)
      IF (ADDEND .EQ. 1) THEN
      CALL MOVEEND(20)
      END IF

      TBFILEB=INFILE(1:6) // TYPE //'.ddat'
      OPEN(27,file=TBFILEB)
      IF (ADDEND .EQ. 1) THEN
      CALL MOVEEND(27)
      END IF

          IF (ABBREV .EQ. 1) THEN
          WRITE(20,89897) 'ABBREVIATED BOUNDARY -- COMPACTNESS ',
     C    INFILE
         WRITE(20,102) (ATITLE(A) , A=1,3)
         WRITE(20,102) 'CUT-OFF VALUE'
         WRITE(20,251) BOUND
         DO 00111 GROUP=1,MAXDEPT
C          TG=CHANGEC(GROUP)
          TG=GROUP
          IF ((DEPARTN(TG) .GT. 0) .AND. (TG .LE. MAXDEPT)) THEN
          WRITE(20,2107) '---------------'
          WRITE(20,105) 'Group ',TG
          WRITE(20,105) '# OF SPANNERS ' ,COUNTG(GROUP)
          WRITE(20,103) 
           DO 6262 GR=1,MAXDEPT
           TCOUNTG(GR)=COUNTG(GR)
           IF (TCOUNTG(GR) .GT. 50.0) THEN
           TCOUNTG(GR)=50.0
           END IF
06262      CONTINUE
           
           
           
           WRITE(20,105) 'ACTOR ',(NSUBID(BOUNDG(GROUP,ZG)) , 
     C     ZG=1,TCOUNTG(GROUP))
           WRITE(20,104) 'CONNECTION ' , (DIFF(BOUNDG(GROUP,ZG),TG),
     C     ZG=1,TCOUNTG(GROUP))
           WRITE(20,105) 'CURRENT GROUP ',
     C     (NEWDEPT(BOUNDG(GROUP,ZG)) , ZG=1,TCOUNTG(GROUP))
        DO 6464 BG=1,TCOUNTG(GROUP)
           WRITE(27,251) GROUP, NEWDEPT(BOUNDG(GROUP,BG))
06464    CONTINUE
         END IF
00111      CONTINUE
          
            END IF
        CLOSE(20)
        CLOSE(27)
       RETURN
  251 FORMAT(20(G15.5))
 2103 FORMAT(2I8,F8.0,500(F5.2,1X))  
21033 FORMAT(3I8,I6,500(F10.2,1X))  
 2107 FORMAT(A16,500(I5,1X))  
  103 FORMAT(F8.1,500(F5.2,1X))  
  105 FORMAT(A15,500(I5,1X))  
  104 FORMAT(A15,500(F5.2,1X))  
  102 FORMAT(10(A30)) 
  101 FORMAT(500(A8)) 
89897 FORMAT(10(A))
      END
