
      SUBROUTINE CHECKVAL(INMAT,SIZE,P1,P2,WHERE)
      INCLUDE 'PARAM.H'
       REAL INMAT(MAXKLIQ,MAXKLIQ)
       INTEGER SIZE,P1,P2,I,J
       CHARACTER WHERE*20

      DO 10 I=1,SIZE
         DO 20 J=1,SIZE
         IF (INMAT(I,J) .GT. 5) THEN
C          WRITE(217,102) WHERE,I,J,INMAT(I,J)
          CALL MYSTOP
         END IF
   20       CONTINUE
   10        CONTINUE

       RETURN
  102 FORMAT(A20,500(F10.5))
      END
