      SUBROUTINE DIFFDIST(COORDA,COORDB,NUMTEACH,NUMDIM,
     C ISTRESS,TAD)
      INCLUDE 'PARAM.H'
       REAL COORDA(MAXKLIQ,2),COORDB(MAXKLIQ,2),ISTRESS(MAXKLIQ),TAD,TEMP
        INTEGER NUMTEACH,NUMDIM,I,J,K

        TAD=0
       DO 6 I=1,NUMTEACH
       ISTRESS(I)=0
00006   CONTINUE

       DO 2 I=2,NUMTEACH 
       DO 3 J=1,(I-1)
       DISTA=0
       DISTB=0
       DO 4 K=1,NUMDIM
       DISTA=DISTA+(COORDA(I,K)-COORDA(J,K))**2
       DISTB=DISTB+(COORDB(I,K)-COORDB(J,K))**2
00004   CONTINUE
       TEMP=(SQRT(DISTA)-SQRT(DISTB))**2
       ISTRESS(I)=ISTRESS(I)+TEMP/(NUMTEACH-1.000)
       ISTRESS(J)=ISTRESS(J)+TEMP/(NUMTEACH-1.000)
       TAD=TAD+TEMP
00003   CONTINUE
00002    CONTINUE
        TAD=TAD*2/(NUMTEACH*(NUMTEACH-1))
        RETURN
        END
