

      SUBROUTINE DIFFMEAN(I,GROUPMAT,G,NUMTEACH,DIFF,THISN,
     C ACTRSQR,TSS,MAXDEPT,ROWWT,COLWT,NEWDEPT)
      INCLUDE 'PARAM.H'
      INTEGER NUMTEACH,I,J,G,THISN,ACTRSQR,MAXDEPT,
     C NEWDEPT(MAXKLIQ)
      REAL DIFF,GROUPMAT(MAXKLIQ,MAXKLIQ),TREAL1,TREAL2,TSS,
     C ROWWT,COLWT,WDENOM
       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),KDIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,KDIFF

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT
        WDENOM=ROWWT+COLWT
      DIFF=0.00
      DO 04 J=1,NUMTEACH
      TREAL1=NEWMAT(I,J)
       IF ((J .EQ. I) .OR. (NEWDEPT(J) .EQ. G)) THEN
       WT=ROWWT
       ELSE
       WT=COLWT
       END IF
       WT=WT/WDENOM
      DIFF=DIFF+WT*(TREAL1-GROUPMAT(G,J))**2
00004  CONTINUE
       IF (ACTRSQR .EQ. 1) THEN
       TREAL2=THISN
       DIFF=DIFF*TREAL2/(TREAL2+1.)
       END IF
        DIFF=TSS-DIFF
C       DIFF=1000/DIFF
       RETURN
      END
