
C       CALL DIFFCOMP(NEWMAT,I,J,NUMTEACH,NEWCON(I,J),
C     C DEPARTN(J),ACTRSQR,SSRI(J),SRI(J),OLDCON(J),
C     C ALLGROUP,RCHOICE(I),DIFF(I,J),NEWONE,GRMEAN,GRVAR,
C     C SRIU2,XSRI)

       SUBROUTINE DIFFCOMP(I,J,NUMTEACH,NEWCON,
     C DEPARTN,ACTRSQR,SSRI,SRI,OLDCON,
     C RCHOICE,CONNECT,NEWONE,GMEAN,GVAR,SRIU2,XSRI,THISMW,
     C THISVW,ROWWT,COLWT,QUANTYPE,SQUAREIT,IEXPECT,ICON,ISTD,
     C ADDVAR,ADDE,DELTAK,DELTAM,DELTAV,PERGROUP,TBLAUC,DISBAND,
     C HYPERG,MAXWT)
      INCLUDE 'PARAM.H'
       
       INTEGER I,J,NUMTEACH,OLDCON,DEPARTN,HYPERG,
     C  ACTRSQR,PI,RCHOICE,NEWONE,TCON,TI,MAXWT,
     C QUANTYPE,SQUAREIT,PERGROUP,DISBAND,BADOLD,BADNEW
   
       REAL SSRI, SRI ,TOP,BOTTOM,CONNECT,NG,N,GAM,
     C ADDVAR,ADDE,XSRI,SRIU2,GMEAN,GVAR,IE,IVAR,THISMW,THISVW,
     C ADDSUB,TNG,XNEWCON,NEWCOMP,OLDCOMP,TOLDCON,
     C TXSRI,TSRIU2,TSRI,TSSRI,ROWWT,COLWT,PNEWCON,NEWE,TBLAUC,
     C NDIFF,ODIFF,NSIGN,OSIGN,NRAT,ORAT,IEXPECT,ICON,ISTD,TUFFY,
     C TUFFY2,INDVSUB,INDMSUB,DELTAK,DELTAM,DELTAV,NEWV,TIVAR,TIE,
     C BDENOM,TX,LNEWE(4),LPNEWCON(4),LGMEAN(4),LTOLDCON(4)

       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       INTEGER ALLGROUP(MAXKLIQ,MAXKLIQ),HUBERT(MAXKLIQ,MAXKLIQ),
     C RESULTM(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ),NEWCON
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF
       DATA ODIFF/0.0/,NDIFF/0.0/,NEWCOMP/0.0/,OLDCOMP/0.0/

      NG=DEPARTN-1
      N=NUMTEACH-1



        IE=0.000000
        IVAR=0.000000
       IF (NEWONE .EQ. 1) THEN
        ADDSUB=1
        TNG=NG+1
       IF ((QUANTYPE .NE. 5) .AND. (RCHOICE .GT. 0))  THEN
       IE=THISMW*RCHOICE*TNG/N
       IVAR=(RCHOICE*TNG*(N-TNG)*THISMW**2/N**2) *
     C  (1. + N*THISVW/((N-TNG)*THISMW**2) - 
     C  HYPERG*((RCHOICE-1.)/(N-1.)))
       END IF       
       ELSE
        ADDSUB=-1
        TNG=NG
       END IF

        NEWCON=0
        XNEWCON=0
          TOLDCON=OLDCON

       DO 02 PI=1,DEPARTN
         NEWCON=NEWCON+NEWMAT(ALLGROUP(J,PI),I)
         XNEWCON=XNEWCON+NEWMAT(I,ALLGROUP(J,PI))
00002     CONTINUE


          TNCON= (COLWT*NEWCON+ROWWT*XNEWCON)
          DISBAND=0
          IF ((ADDSUB .LT. 1) .AND. (TNCON .LE. 0)) THEN
           DISBAND=1
          END IF

          NEWE=   COLWT*ADDE+ROWWT*ADDSUB*IE
          NCHOICE=COLWT*SRI+ROWWT*ADDSUB*RCHOICE*THISMW

          PNEWCON= (TOLDCON+ADDSUB*(COLWT*NEWCON+ROWWT*XNEWCON)) 

          IF (QUANTYPE .EQ. 3) THEN
          LNEWE(3)=NEWE
          LNEWE(4)=NCHOICE-NEWE
          LNEWE(2)=TNG*(TNG-1.0)*MAXWT - NEWE
          LNEWE(1)=TNG*(N-TNG)*MAXWT - LNEWE(2)


          LPNEWCON(3)=PNEWCON 
          LPNEWCON(4)=NCHOICE-PNEWCON
          LPNEWCON(2)=TNG*(TNG-1.0)*MAXWT - PNEWCON
          LPNEWCON(1)=TNG*(N-TNG)*MAXWT - LPNEWCON(2)

          LGMEAN(3)=GMEAN
          LGMEAN(4)=SRI-GMEAN
          LGMEAN(2)=DEPARTN*(DEPARTN-1.0)*MAXWT-GMEAN
          LGMEAN(1)=DEPARTN*(N-DEPARTN)*MAXWT - LGMEAN(2)

          LTOLDCON(3)=TOLDCON
          LTOLDCON(4)=SRI-TOLDCON
          LTOLDCON(2)=DEPARTN*(DEPARTN-1.0)*MAXWT-TOLDCON
          LTOLDCON(1)=DEPARTN*(N-DEPARTN)*MAXWT - LTOLDCON(2)
          END IF

          IF (RCHOICE .LT. TNG) THEN
           BDENOM=RCHOICE
          ELSE
           BDENOM=TNG
          END IF

          TBLAUC=(COLWT*NEWCON+ROWWT*XNEWCON)/(BDENOM+TNG)

           DELTAK=PNEWCON-TOLDCON
           ICON=-ADDSUB*(COLWT*NEWCON+ROWWT*XNEWCON)
           IF (QUANTYPE .NE. 5) THEN
           ODIFF=TOLDCON-GMEAN
           NDIFF=PNEWCON-NEWE
           IEXPECT=-ADDSUB*(COLWT*ADDE+ROWWT*IE)
           ISTD=-ADDSUB*(COLWT*ADDVAR +ROWWT*IVAR)**.5
           DELTAM=NEWE-GMEAN
           NEWV=COLWT*ADDVAR + ROWWT*ADDSUB*IVAR
           DELTAV= NEWV-GVAR
           END IF          
           IF (ODIFF .GT. 0.00000) THEN 
             OSIGN=1
           ELSE
             OSIGN=-1
           END IF

           IF (NDIFF .GT. 0.00000) THEN 
             NSIGN=1
           ELSE
             NSIGN=-1
           END IF


           ORAT=TOLDCON/GMEAN
           NRAT=TOLDCON/NEWE



           IF (QUANTYPE .EQ. 1) THEN
          OLDCOMP= (ODIFF)/GVAR**.5
          NEWCOMP=    (NDIFF) / NEWV**.5
C     C    (ADDVAR+ ADDSUB*IVAR)**.5
          END IF
            IF (QUANTYPE .EQ. 2) THEN
           OLDCOMP=(ODIFF)/GMEAN**.5
           NEWCOMP=(NDIFF)/NEWE**.5
           END IF
           IF (QUANTYPE .EQ. 3) THEN
           OLDCOMP=0
           BADOLD=0
           NEWCOMP=0
           BADNEW=0
           DO 8282 TI=1,4
           IF ((TI .EQ. 1) .OR. (TI .EQ. 3)) THEN
           LADD=1
           ELSE
           LADD=-1
           END IF
           IF (LGMEAN(TI) .LT. .0001) THEN
           LGMEAN(TI)=.0001
           END IF
           IF (LTOLDCON(TI) .LT. .0001) THEN
           LTOLDCON(TI)=.0001
           END IF

            OLDCOMP=OLDCOMP+LADD*2*LTOLDCON(TI)*
     C     LOG(LTOLDCON(TI)/LGMEAN(TI))

           IF (LNEWE(TI) .LT. .0001) THEN
           LNEWE(TI)=.0001
           END IF
           IF (LPNEWCON(TI) .LT. .0001) THEN
           LPNEWCON(TI)=.0001
           END IF

            NEWCOMP=NEWCOMP+2*LADD*LPNEWCON(TI)*
     C     LOG(LPNEWCON(TI)/LNEWE(TI))
08282       CONTINUE

C          IF ((PNEWCON .GT. 0.000000) .AND. (NEWE .GT. 0.00000)) THEN
C            NEWCOMP=2*PNEWCON*LOG(PNEWCON/NEWE)
C           ELSE
C            NEWCOMP=-999999
C          END IF

           END IF
          IF (QUANTYPE .EQ. 4)  THEN
           NEWCOMP=0
           OLDCOMP=0
           IF (NG .GT. 0) THEN
           OLDCOMP=TOLDCON/(DEPARTN*(DEPARTN-1.00))
           END  IF

           TX=DEPARTN+ADDSUB
           IF (TX .GT. 1) THEN
           NEWCOMP=PNEWCON/(TX*(TX-1.00))
           END IF
           END IF
C           IF (NEWONE .EQ. 1) THEN
C           NEWCOMP=(TOLDCON+TNCON)/(NG*(NG+1.000))
C          ELSE
C          NEWCOMP=(TOLDCON-TNCON)/(NG*(NG-1.000))
C           END IF
C           IF (NG .GT. 1) THEN
C           OLDCOMP=TOLDCON/(NG*(NG-1.000))
C          END IF
C           ELSE
C           IF (NG .GT. 1) THEN
C          OLDCOMP=TOLDCON/(NG*(NG-1.000))
C           END IF
C           IF (NG .GT. 2) THEN
C           NEWCOMP=(TOLDCON-NEWCON-XNEWCON)/((NG-1.00)*(NG-2.00))
C           END IF
C           END IF
C          END IF
C          END IF
      
           IF ((SQUAREIT .EQ. 1) .AND. (QUANTYPE .LT. 3)) THEN
           NEWCOMP=NSIGN*NEWCOMP**2
           OLDCOMP=OSIGN*OLDCOMP**2
           END IF
           IF (PERGROUP .EQ. 1) THEN
            NEWCOMP=NEWCOMP/(DEPARTN-1.+ADDSUB)
            OLDCOMP=OLDCOMP/(DEPARTN-1.)
           END IF
           IF ((DEPARTN .LT. 2) .AND. (NEWONE .EQ. 1)) THEN
           OLDCOMP=0
           END IF
           IF ((NEWONE .EQ. 0) .AND. (DEPARTN .EQ. 2)) THEN
           NEWCOMP=0
           END IF

           CONNECT=ADDSUB*(NEWCOMP-OLDCOMP)

           IF ((QUANTYPE .NE. 3) .AND. (TNCON .LE. 0)) THEN
           CONNECT=-999
           END IF

       RETURN
       END
