C         CALL DISTRIB (RCHOICE(THISMEM),MEANWT(THISMEM),
C     C    VARWT(THISMEM),AMEAN,AVAR,1,NUMTEACH)
C         CALL DISTRIB (RCHOICE(I),MEANWT(I),
C     C    VARWT(I),AMEAN,AVAR,TEMPS,NUMTEACH)

      SUBROUTINE DISTRIB (THISR,THISWM,THISWV,MEAN,TVAR,KGRPSIZE,
     C           TOTSIZE,THISPER,AVAR2,HYPERG)
      REAL ATHISR,ANTEACH,ATHISSIZ,AVAR2
      INTEGER THISR,TOTSIZE,KGRPSIZE,NTEACH,THISSIZE,THISPER,
     C HYPERG
      REAL THISWM,THISWV,MEAN,TVAR,OTHERS,MIDPART
      MEAN=0
      TVAR=.000001
      AVAR2=.000001
      ATHISR=THISR
      ATHISSIZ=KGRPSIZE-1
      OTHERS=TOTSIZE-KGRPSIZE
      ANTEACH=TOTSIZE-1

        MEAN=(THISWM*ATHISR*ATHISSIZ)/ANTEACH
         AVAR2=(THISWM**2)*ATHISR*ATHISSIZ*OTHERS/(ANTEACH**2)
         IF (THISWV .GT. 0) THEN
         MIDPART=(ANTEACH*THISWV)/(OTHERS*THISWM**2) 
         ELSE
         MIDPART=0
         END IF
         TVAR=(THISWM*THISWM)*ATHISR*ATHISSIZ*OTHERS*
     C        (1+ MIDPART
     C          -HYPERG*((ATHISR-1)/(ANTEACH-1)))/(ANTEACH*ANTEACH)
      RETURN
  251 FORMAT(15F10.5)
      END
