       
      SUBROUTINE FIXMAT(INMAT,MAXG,CURPLACE)
      INCLUDE 'PARAM.H'
      REAL INMAT(MAXGR,MAXGR),COMPMAT(MAXGR,MAXGR)
      INTEGER MAXG,I,J,CURPLACE(MAXKLIQ)
       DO 9 I=1,MAXG
       DO 10 J=1,MAXG
       COMPMAT(I,J)=INMAT(I,J)
00010   CONTINUE
00009    CONTINUE
       DO 11 I=1,MAXG
       DO 12 J=1,MAXG
       INMAT(CURPLACE(I),CURPLACE(J))=COMPMAT(I,J)
00012   CONTINUE
00011    CONTINUE
       RETURN
       END
