C     END SUBROUTINE RESORTO




      SUBROUTINE GETRS2(NEWDEPT,NUMTEACH,MAXDEPT,
     C DEPARTN,WANTSS,RCHOICE,SRI,SSRI,OLDCON,XSRI,
     C MEANWT,VARWT,SRIU2,GMEAN,GVAR,GVPLUS,GMPLUS,GVSUB,
     C IVSUB,GMSUB,IMSUB,DTOTK,DTOTE,DTOTV,IDELTKA,QUANTYPE,
     C TOBFUN,SQUAREIT,NETLEV,PERGROUP,WANTFUN,CURVAR,CURMEAN,
     C PLUSVAR,PLUSMEAN,OLDGZ,HYPERG,BLT,MAXCH,SAMEG1,K1,K2,
     C COLWT,ROWWT)
      INCLUDE 'PARAM.H'

      INTEGER NEWDEPT(MAXKLIQ),NUMTEACH,I,J,MAXDEPT,
     C DEPARTN(MAXKLIQ),TN,WANTSS,OLDCON(MAXKLIQ),RCHOICE(MAXKLIQ),
     C QUANTYPE,IFSQUARE,SQUAREIT,NETLEV,MAXCH,SAMEG1,
     C PERGROUP,WANTFUN,ACTG,HYPERG,TI,LADD,BLT,K1,K2
      INTEGER G,THISMEM

      REAL TREAL,TDENOM,SRI(MAXKLIQ),GMEAN(MAXKLIQ),GVAR(MAXKLIQ),NG,N,
     C SSRI(MAXKLIQ),XSRI(MAXKLIQ),MEANWT(MAXKLIQ),VARWT(MAXKLIQ),
     C SRIU2(MAXKLIQ),TUFFY,TUFFY2,ADDVAR,GVAR2,GVPLUS(MAXKLIQ),
     C GMPLUS(MAXKLIQ),GVSUB(MAXKLIQ),IVSUB(MAXKLIQ),GMSUB(MAXKLIQ),
     C IMSUB(MAXKLIQ),DTOTK,DTOTE,DTOTV,KADDVAR,KADDM,IDELTKA(MAXKLIQ),
     C TOBFUN,DENOM,CURVAR(MAXKLIQ),CURMEAN(MAXKLIQ),PLUSVAR(MAXKLIQ),
     C PLUSMEAN(MAXKLIQ),OLDGZ(MAXKLIQ),SIDEWT,KSIGN,LGMEAN(4),
     C LTOLDCON(4),PENNUM,COLWT,ROWWT
       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

       IFSQUARE=SQUAREIT+1
       DTOTE=0
       DTOTK=0
       DTOTV=0
       SAMEG1=0 
      DO 4 I=1,MAXDEPT
        SAMEG1=SAMEG1+DEPARTN(I)*(DEPARTN(I)-1)
C       SRIU2(I)=0.000
C       XSRI(I)=0.000
       SRI(I)=0.000
C
C       SSRI(I)=0.000
       GVAR(I)=0.000
       GMEAN(I)=0.000
       GVPLUS(I)=0.000
       GMPLUS(I)=0.000
       GVSUB(I)=0.0000
       GMSUB(I)=0.0000
       OLDGZ(I)=0.000
       OLDCON(I)=0
00004   CONTINUE
       SAMEG1=SAMEG1*MAXCH
       N=NUMTEACH-1
      DO 06 I=1,NUMTEACH
        PLUSMEAN(I)=0.000
        PLUSVAR(I)=0.000
        CURMEAN(I)=0.0000
        CURVAR(I)=0.000
        IDELTKA(I)=0.000
        IVSUB(I)=0.000
        IMSUB(I)=0.000
        IF (RCHOICE(I) .GT. 0) THEN
        NG=DEPARTN(NEWDEPT(I))-1
        SRI(NEWDEPT(I))=SRI(NEWDEPT(I))+RCHOICE(I)*MEANWT(I)
        IF (NG .GT. 0) THEN
C        SRIU2(NEWDEPT(I))=SRIU2(NEWDEPT(I))+
C     C  RCHOICE(I)*MEANWT(I)**2
C        SSRI(NEWDEPT(I))=SSRI(NEWDEPT(I))+ 
C     C  (MEANWT(I)*RCHOICE(I))**2 -
C     C  MEANWT(I)**2 * RCHOICE(I)
C        XSRI(NEWDEPT(I))=XSRI(NEWDEPT(I)) + 
C     C   RCHOICE(I)*VARWT(I)


         KADDVAR=
     C   (RCHOICE(I)*NG*(N-NG)*MEANWT(I)**2 /N**2) *
     C    (1 + (N*VARWT(I))/((N-NG)*MEANWT(I)**2) - 
     C   HYPERG*((RCHOICE(I) - 1)/ (N-1)))
         CURVAR(I)=KADDVAR
         GVAR(NEWDEPT(I))=GVAR(NEWDEPT(I)) +KADDVAR
         KADDM=
     C  MEANWT(I)*RCHOICE(I)*NG/N
         CURMEAN(I)=KADDM
        GMEAN(NEWDEPT(I))= GMEAN(NEWDEPT(I)) +KADDM
        DTOTE=DTOTE+ KADDM
        DTOTV=DTOTV+KADDVAR
         END IF
        TNG=NG+1
 
C     GVPLUS(251),GMPLUS(251),
C     C GVSUB(251),IVSUB(251),GMSUB(251),IMSUB(251)

         PLUSVAR(I)=
     C   (RCHOICE(I)*TNG*(N-TNG)*MEANWT(I)**2 /N**2) *
     C    (1 + (N*VARWT(I))/((N-TNG)*MEANWT(I)**2) - 
     C   HYPERG*((RCHOICE(I) - 1)/ (N-1)))
         GVPLUS(NEWDEPT(I))=GVPLUS(NEWDEPT(I)) + PLUSVAR(I)


        PLUSMEAN(I)=
     C  MEANWT(I)*RCHOICE(I)*TNG/N
         GMPLUS(NEWDEPT(I))=GMPLUS(NEWDEPT(I))+PLUSMEAN(I)
          IF (NG .GT. 1) THEN
          TNG=TNG-2
        IVSUB(I)=
     C   (RCHOICE(I)*TNG*(N-TNG)*MEANWT(I)**2 /N**2) *
     C    (1 + (N*VARWT(I))/((N-TNG)*MEANWT(I)**2) - 
     C   HYPERG*((RCHOICE(I) - 1)/ (N-1)))
        IMSUB(I)=
     C  MEANWT(I)*RCHOICE(I)*TNG/N
          ELSE
C        CURVAR(I)=999999
C        CURMEAN(I)=0
        IMSUB(I)=0.000
        IVSUB(I)=0.000
          END IF
         GMSUB(NEWDEPT(I))=GMSUB(NEWDEPT(I))+IMSUB(I)
         GVSUB(NEWDEPT(I))=GVSUB(NEWDEPT(I))+IVSUB(I)
        END IF

00006    CONTINUE
      TOBFUN=0
      DTOTK=0
      ACTG=0
      DO 012 G=1,MAXDEPT
      IF (DEPARTN(G) .GT. 1) THEN
      ACTG=ACTG+1
      END IF
00012  CONTINUE
       SIDEWT=1.000
       IF (NETLEV .EQ. 2) THEN 
       SIDEWT=0.000
       END IF
      DO 08 G=1,MAXDEPT
       OLDGZ(G)=0.0000
      DO 09 I=1,DEPARTN(G)
       DO 10 J=1,DEPARTN(G)
        OLDCON(G)=OLDCON(G)+NEWMAT(ALLGROUP(G,I),ALLGROUP(G,J))
        DTOTK=DTOTK+NEWMAT(ALLGROUP(G,I),ALLGROUP(G,J))
        IDELTKA(ALLGROUP(G,I))=IDELTKA(ALLGROUP(G,I)) +
     C  NEWMAT(ALLGROUP(G,I),ALLGROUP(G,J)) +
     C  NEWMAT(ALLGROUP(G,J),ALLGROUP(G,I)) * SIDEWT
00010  CONTINUE


        THISMEM=ALLGROUP(G,I)
        IF ((THISMEM .GT. .00001) .AND. (G .GT. 0) .AND.
     C  (CURVAR(THISMEM) .GT. .00001)) THEN
        OLDGZ(G)=OLDGZ(G)+(IDELTKA(THISMEM) - CURMEAN(THISMEM)) /
     C   SQRT(CURVAR(THISMEM))
         END IF
00009   CONTINUE

        IF ((DEPARTN(G) .GT. 0) .AND. ((WANTFUN .EQ. 1) 
     C                           .OR. (NETLEV .EQ. 1))) THEN
        IF (PERGROUP .EQ. 0) THEN
        DENOM=1
        ELSE
        DENOM=(DEPARTN(G)-1.)*ACTG
        END IF

        IF ((QUANTYPE .EQ. 1) .AND. (NETLEV .EQ. 0) .AND.
     C  (GVAR(G) .GT. 0.000000)) THEN
        TOBFUN=TOBFUN+(((OLDCON(G) - GMEAN(G))/GVAR(G)**.5)
     C **IFSQUARE) / DENOM
         END IF

        IF ((GMEAN(G) .GT. 0.00000) .AND. (QUANTYPE .EQ. 2)) THEN
        TOBFUN=TOBFUN+(((OLDCON(G)-GMEAN(G))/GMEAN(G)**.5)**IFSQUARE)
     C / DENOM
        END IF

        IF ((QUANTYPE .EQ. 3) .AND. (OLDCON(G) .GT. 0.00000) .AND.
     C   (GMEAN(G) .GT. 0.00000)) THEN

          LGMEAN(3)=GMEAN(G)
          LGMEAN(4)=SRI(G)-GMEAN(G)
          LGMEAN(2)=MAXCH*DEPARTN(G)*(DEPARTN(G)-1.0)-GMEAN(G)
          LGMEAN(1)=MAXCH*DEPARTN(G)*(NUMTEACH-DEPARTN(G)) - LGMEAN(2)

          LTOLDCON(3)=OLDCON(G)
          LTOLDCON(4)=SRI(G)-OLDCON(G)
          LTOLDCON(2)=MAXCH*DEPARTN(G)*(DEPARTN(G)-1.0)-OLDCON(G)
          LTOLDCON(1)=MAXCH*DEPARTN(G)*(NUMTEACH-DEPARTN(G)) 
     C    - LTOLDCON(2)

           DO 8282 TI=1,4
           IF ((TI .EQ. 1) .OR. (TI .EQ. 3)) THEN
           LADD=1
           ELSE
           LADD=-1
           END IF
           IF (LGMEAN(TI) .LT. .0001) THEN
           LGMEAN(TI)=.0001
           END IF
           IF (LTOLDCON(TI) .LT. .0001) THEN
           LTOLDCON(TI)=.0001
           END IF

            TOBFUN=TOBFUN+LADD*2*LTOLDCON(TI)*
     C      LOG(LTOLDCON(TI)/LGMEAN(TI))

08282       CONTINUE
         IF (BLT .EQ. 1) THEN
          PENNUM=NUMTEACH*(NUMTEACH-1)
          TOBFUN=TOBFUN-MAXDEPT*LOG(PENNUM)
         END IF
        END IF

        IF (QUANTYPE .EQ. 4) THEN
         IF (DEPARTN(G) .GT. 1) THEN
         TOBFUN=TOBFUN+OLDCON(G)/(DEPARTN(G)*(DEPARTN(G)-1.0000))
         END IF
        END IF
        END IF
00008    CONTINUE
       
       IF (NETLEV .EQ. 1) THEN
       IF (QUANTYPE .EQ. 1) THEN
       TOBFUN=(DTOTK-DTOTE)/DTOTV**.5
       END IF
       IF (QUANTYPE .EQ. 5) THEN
       IF (COLWT .LT. .0001) THEN
       TOBFUN=DTOTK/SAMEG1
       ELSE
       TOBFUN=(DTOTK*(K1-(SAMEG1-DTOTK)))/
     C ((SAMEG1-DTOTK)*(K2-DTOTK))
       END IF
       END IF
        END IF
        IF (NETLEV .EQ. 2) THEN
        TOBFUN=0
        DO 987 I=1,NUMTEACH
         CHANGE=0.0000
        IF ((QUANTYPE .EQ. 1) .AND. (CURVAR(I) .GT. 0)) THEN
        CHANGE=(IDELTKA(I)-CURMEAN(I))/SQRT(CURVAR(I))
        END IF

        IF ((QUANTYPE .EQ. 2) .AND. (CURMEAN(I) .GT. 0)) THEN
        CHANGE=(IDELTKA(I)-CURMEAN(I))/SQRT(CURMEAN(I))
        END IF
        IF (QUANTYPE .EQ. 3) THEN
        KSIGN=IDELTKA(I)/CURMEAN(I)
        IF (KSIGN .GT. 0) THEN
        CHANGE=2*IDELTKA(I)*LOG(KSIGN)
        END IF
        END IF
        TOBFUN=TOBFUN+CHANGE
00987    CONTINUE
         END IF
   
        RETURN
        END
