      SUBROUTINE GETWARP(INMAT,MAXG,KMAXVAL,TOTVAL,WARP)

      INCLUDE 'PARAM.H'
      INTEGER TOTVAL,MAXG,MATZ,I,J,K,IERR
      REAL INMAT(MAXGR,MAXGR),WARP,OUTA(TOTVAL),W(MAXG),Z(MAXG,MAXG),
     C KMAXVAL,FV1(MAXG),FV2(MAXG)

      K=1
      OUTA(K)=KMAXVAL
      DO 1 I=2,MAXG
      DO 2 J=1,(I-1)
      OUTA(K)=(INMAT(I,J)+INMAT(J,I))/2
      K=K+1
00002  CONTINUE
      OUTA(K)=KMAXVAL
      K=K+1
00001  CONTINUE
      MATZ=0
      CALL RSP(MAXG,MAXG,TOTVAL,OUTA,W,MATZ,Z,FV1,FV2,IERR)
      TOTVAR=0
      TOTPOS=0
      OPEN (62, file='eigval.dat')
      DO 3 I=1,MAXG      
      TOTVAR=TOTVAR+W(I)
      IF (W(I) .GT. 0) THEN
      TOTPOS=TOTPOS+W(I)
      END IF
      WRITE(62,10) I,W(I)

00003  CONTINUE
      WARP=TOTPOS/TOTVAR
      CLOSE(62)
      RETURN
00010  FORMAT (F10.0,F15.5)
      END
      
