
      SUBROUTINE GROUPASC (ZCOVMAT,LMAXDEPT,LGROUP,DEPARTN,
     C LOGIT,ZIT,INUM,NUMTEACH,INFILE,TACKON,PRINTGRP,LABEL,
     C ADDEND,ONLYPOS,NSIM,FINAL,MAXDEPT,PRINTK,LAMNDA)
      INCLUDE 'PARAM.H'

      INTEGER LMAXDEPT,LGROUP(MAXKLIQ),DEPARTN(MAXKLIQ),G1,G2,LOGIT,ZIT,
     C AG1,AG2,AG3,INUM,NUMTEACH,PRINTGRP,G3,ADDEND,ADDW,DIVW,ONLYPOS,
     C NSIM,FINAL,MAXDEPT,PRINTK
      REAL ZCOVMAT(MAXGR,MAXGR),
     C TOTRELC(MAXGR,MAXGR),BETWEENC(MAXGR,MAXGR),
     C GDEGREE(MAXGR,1),GCLOSE(MAXGR,1),GBETW(MAXGR,1),
     C ICOMP(MAXGR),LAMNDA(MAXGR)

       CHARACTER*16 INFILE,OUTFILE,OUTFILE2
       CHARACTER LABEL(MAXKLIQ)*9,TACKON*4


       IF (PRINTGRP .EQ. 1) THEN
       OUTFILE2='central.' // TACKON
       OPEN(56,file=OUTFILE2)
       IF (ADDEND .EQ. 1) THEN
       CALL MOVEEND(56)
       END IF
       END IF
       DO 88 I=1,LMAXDEPT
       DO 86 J=1,LMAXDEPT
       BETWEENC(I,J)=ZCOVMAT(LGROUP(I),LGROUP(J))
00086   CONTINUE
00088    CONTINUE

       CALL PRINTCOV(BETWEENC,LGROUP,LMAXDEPT,DEPARTN,
     C '               DIRECT ASSOCIATIONS                   ',
     C INUM,NUMTEACH,1,1,GDEGREE,LABEL,0,'DIRECT ',INFILE,PRINTGRP,
     C 0)
       IF (ONLYPOS .EQ. 1) THEN
       ADDW=0
       DIVW=1
       ELSE
       ADDW=1
       DIVW=2
       END IF
      DO 321 G1=1,LMAXDEPT
       ICOMP(G1)=ZCOVMAT(LGROUP(G1),LGROUP(G1))
       DO 4321 G2=1,LMAXDEPT
         TOTRELC(G1,G2)=0
         BETWEENC(G1,G2)=0
         IF (LOGIT .EQ. 1) THEN
         ZCOVMAT(LGROUP(G1),LGROUP(G2))=
     C   LOG(ZCOVMAT(LGROUP(G1),LGROUP(G2))+1.)
         END IF
         IF (ZIT .EQ. 1) THEN
         LG1=LGROUP(G1)
         LG2=LGROUP(G2)
        IF (ZCOVMAT(LG1,LG2) .GE. 0) THEN
         KSIGN=1
        ELSE 
         KSIGN=-1
        END IF
         NODO=0
        IF (ZCOVMAT(LG1,LG2) .GT. 10) THEN 
         ZCOVMAT(LG1,LG2) = 1
         NODO=1
        END IF
       IF (ZCOVMAT(LG1,LG2) .LT. -10) THEN 
         ZCOVMAT(LG1,LG2) = -1
         NODO=1
        END IF
        IF (NODO .EQ. 0) THEN
        ZABS=EXP(ABS(ZCOVMAT(LG1,LG2)*2))
        ZCOVMAT(LG1,LG2)=(ADDW+KSIGN*(ZABS-1)/(ZABS+1))/DIVW
        END IF

        END IF
04321    CONTINUE
  321 CONTINUE

C    TOTAL RELATION

       DO 88771 AG1=2,LMAXDEPT
        G1=LGROUP(AG1)
       DO 88772 AG2=1,(AG1-1)
        G2=LGROUP(AG2)
       TOTRELC(AG1,AG2)=TOTRELC(AG1,AG2)+ZCOVMAT(G1,G2)
       DO 88773 AG3=1,LMAXDEPT
        G3=LGROUP(AG3)
       IF ((G3 .NE. G1) .AND. (G3 .NE. G2)) THEN
       TOTRELC(AG1,AG2)=TOTRELC(AG1,AG2)
     C  +ZCOVMAT(G1,G3)*ZCOVMAT(G2,G3)
       END IF
88773   CONTINUE
       TOTRELC(AG2,AG1)=TOTRELC(AG1,AG2)
88772   CONTINUE
88771   CONTINUE

C        BETWEENNESS

       DO 89771 AG1=2,LMAXDEPT
        G1=LGROUP(AG1)
       DO 89772 AG2=1,(AG1-1)
        G2=LGROUP(AG2)
       DO 89773 AG3=1,LMAXDEPT
        G3=LGROUP(AG3)
       IF ((G3 .NE. G1) .AND. (G3 .NE. G2)) THEN
       IF (ABS(TOTRELC(AG1,AG2)) .GT. .00001) THEN
       BETWEENC(AG3,AG2)=BETWEENC(AG3,AG2)+
     C  ZCOVMAT(G1,G3)*ZCOVMAT(G2,G3)/TOTRELC(AG1,AG2)
       BETWEENC(AG3,AG1)=BETWEENC(AG3,AG1)+
     C  ZCOVMAT(G1,G3)*ZCOVMAT(G2,G3)/TOTRELC(AG1,AG2)
       END IF
       END IF
89773   CONTINUE
89772   CONTINUE
89771   CONTINUE

       CALL PRINTCOV(TOTRELC,LGROUP,LMAXDEPT,DEPARTN,
     C '       TOTAL RELATIONS (FREEMAN''S CLOSENESS)         ',
     C  INUM,NUMTEACH,0,1,GCLOSE,LABEL,1,'TOTAL  ',INFILE,PRINTGRP,
     C  1)

       CALL PRINTCOV(BETWEENC,LGROUP,LMAXDEPT,DEPARTN,
     C 'BETWEENNESS / TOTAL RELATIONS (FREEMAN''S BETWEENNESS)',
     C  INUM,NUMTEACH,0,1,GBETW,LABEL,0,'BETWEEN',INFILE,PRINTGRP,
     C  0)

        IF (PRINTGRP .EQ. 1) THEN
        OUTFILE='compgrp.' // TACKON
        OPEN(28,file=OUTFILE)
       IF (ADDEND .EQ. 1) THEN
       CALL MOVEEND(28)
       END IF
        DO 3174 AG1=1,LMAXDEPT
        G1=LGROUP(AG1)
        WRITE(28,2195) INFILE,NSIM,FINAL,G1,DEPARTN(G1),
     C  ICOMP(AG1),GDEGREE(AG1,1),GCLOSE(AG1,1),GBETW(AG1,1),
     C  NSIM,PRINTK,LAMNDA(G1)
03174    CONTINUE
       CLOSE(28)
       CLOSE(56)
       END IF

       RETURN
02195 FORMAT(A10,4I10,4F10.3,2I10,F10.5)
       END
