
       SUBROUTINE INITGRPD(NUMDYAD,PERSON1,PERSON2,
     C NEWDEPT,NUMTEACH,LIST,L)
     
      INCLUDE 'PARAM.H'
       INTEGER NUMDYAD,PERSON1(MAXKLIQ),PERSON2(MAXKLIQ),
     C NEWDEPT(MAXKLIQ),ND,NEWA(MAXKLIQ),LIST(MAXKLIQ),L,J,NUMTEACH
       
         
      DO 5 I=1,NUMTEACH
        NEWDEPT(I)=0
    5 CONTINUE

      DO 10 ND=1,NUMDYAD
        NEWDEPT(PERSON1(ND))=ND
        NEWDEPT(PERSON2(ND))=ND
   10  CONTINUE
  101 FORMAT(A15)
  251 FORMAT(20(F10.5))
        RETURN
        END
