

C       CALL INITGRP(NUMDYAD,PERSON1,PERSON2,PERSON3,NEWDEPT,
C     C NUMTEACH,NLIST,NUMNLIST)       

       SUBROUTINE INITGRP(NUMDYAD,PERSON1,PERSON2,PERSON3,
     C NEWDEPT,NUMTEACH,LIST,L,NSUBID)
     
      INCLUDE 'PARAM.H'
       INTEGER NUMDYAD,PERSON1(MAXKLIQ),PERSON2(MAXKLIQ),
     C PERSON3(MAXKLIQ),NEWDEPT(MAXKLIQ),ND,NEWA(MAXKLIQ),
     C LIST(MAXKLIQ),L,J,NUMTEACH,NSUBID(MAXKLIQ)
       
         
      DO 5 I=1,NUMTEACH
        NEWDEPT(I)=0
    5 CONTINUE

        WRITE(33,3252) 
        WRITE(33,2252) 'INITIALIZE' ,'GROUPS'

        WRITE(33,2252) 'STARTING','GROUPS'
        WRITE(33,2252)
        WRITE(33,2252) 'TRIAD','ACTOR 1','ACTOR 2','ACTOR 3'
      DO 10 ND=1,NUMDYAD
        IF ((PERSON1(ND) .GT. 0) .AND. (PERSON2(ND) .GT. 0) .AND.
     C  (PERSON3(ND) .GT. 0)) THEN
        WRITE(33,2251) ND,NSUBID(PERSON1(ND)),
     C NSUBID(PERSON2(ND)),NSUBID(PERSON3(ND))
        END IF
        IF (PERSON1(ND) .GT. 0) THEN
        NEWDEPT(PERSON1(ND))=ND
        END IF
C        NEWA(PERSON1(ND))=1
        IF (PERSON2(ND) .GT. 0) THEN
        NEWDEPT(PERSON2(ND))=ND
        END IF
C        NEWA(PERSON2(ND))=1
        IF (PERSON3(ND) .GT. 0) THEN
        NEWDEPT(PERSON3(ND))=ND
        END IF
C        NEWA(PERSON3(ND))=1
   10  CONTINUE
  101 FORMAT(A15)
  251 FORMAT(251(F10.5))
02252 FORMAT(251(A10))
02251 FORMAT(251(I10))
03252 FORMAT(//,'---------------------------------------------',//)

        RETURN
        END
