C      END FUNCTION TOTWI
C
C
      FUNCTION ISOGROUP(INGROUP,GROUPI,PATTERN,STARTER,MAXGROUP,
     C                  COUNTGR)
      INCLUDE 'PARAM.H'
      INTEGER MEMBER,OTHERMEM,INGROUP(MAXKLIQ,MAXKLIQ),
     C PATTERN(MAXKLIQ,MAXKLIQ)
      INTEGER STARTER,MAXGROUP,I,J,Z,GROUPI,COUNTGR(MAXKLIQ),THISGRP
      INTEGER ISOGROUP,ISOTEMP,MGROUP
C     INGROUP IS AN ARRAY OF THE ID'S OF THE PEOPLE IN THE GROUPS
C     NUMTOT IS THE TOTAL NUMBER OF TEACHERS
C     NUMGROUP IS THE NUMBER OF PEOPLE IN THE GROUP
C     PATTERN IS THE MATRIX OF RELATION PATTERNS
C     PRELATE IS THE PROPORTION OF PATTERNS WITHIN THE MATRIX
C     
       ISOTEMP=STARTER
      DO 200  MGROUP=1,COUNTGR(GROUPI)
      MEMBER=INGROUP(GROUPI,MGROUP)
        DO 250 Z=1,MAXGROUP
          IF (Z .NE. GROUPI) THEN
            DO 300 J = 1,COUNTGR(Z)
              OTHERMEM=INGROUP(Z,J)
              ISOTEMP=ISOTEMP+PATTERN(MEMBER,OTHERMEM)
C             IF (THISGRP .EQ. 3) THEN 
C              WRITE(16,993) MEMBER,OTHERMEM,PATTERN(MEMBER,OTHERMEM)
C             END IF
  300       CONTINUE
          END IF
  250  CONTINUE
  200  CONTINUE
       ISOGROUP=ISOTEMP
  993 FORMAT('MEMBER=',F4.0,' OTHER=',F4.0,' PATT=',F4.0)
       RETURN
       END
