      
       SUBROUTINE KDIST(I,J,COORD,MAXG,NUMDIM,KEXP,TRUEDIST,
     C OUTDIST,NORMAL,MINDIST,KSCALE,ANGLEI,ANGLEH,BYANGLE)
       INCLUDE 'PARAM.H'
       INTEGER I,J,NUMDIM,MAXG,K,NORMAL,BYANGLE
       REAL COORD(MAXKLIQ,NUMDIM),KEXP,TKDIST,TRUEDIST,OUTDIST,VDIST,
     C MINDIST,KSCALE,ANGLEI,ANGLEH,DIFFANGL

       TKDIST=0
       DO 2 K=1,NUMDIM
       TKDIST=TKDIST+(COORD(I,K)-COORD(J,K))**2
00002   CONTINUE
       TKDIST=(TKDIST**.5)*KSCALE
       IF (TKDIST .LT. MINDIST) THEN
       VDIST=999
       ELSE
      IF (BYANGLE .EQ. 1) THEN
      TKDIST=ABS(ANGLEI-ANGLEH)
      IF (TKDIST .GT. 3.14159) THEN
      TKDIST=3.14159*2-TKDIST
      END IF
      END IF
       VDIST=TRUEDIST-TKDIST
       END IF

       IF (NORMAL .EQ. 1) THEN
        VDIST=VDIST/TRUEDIST
       END IF
       IF (KEXP .LT. 0) THEN
       OUTDIST=ABS(VDIST)
       END IF
       IF (ABS(KEXP) .LT .00001) THEN
       OUTDIST=LOG(ABS(VDIST))
       END IF
       IF (KEXP .GT. 0) THEN
       OUTDIST=VDIST**KEXP
       END IF
       RETURN
       END 
