      SUBROUTINE KEVAL(MAXDEPT,DEPARTN,NUMTEACH,
     C RCHOICE,OLDDEPT,MEANWT,VARWT,PRINTT,
     C FINAL,FSYMMAT,PRINTO,FCOMPACT,CHNGSIM,NEVAL,BASEVAL,
     C NBESTDEP,STRUCTEQ,NUMRES,TRYDEPT,QUANTYPE,TOPVAL,NEWGRPS,
     C PERGROUP,SQUAREIT,FIXR,HIWTEVAL,HYPERG,ROWWT,COLWT,KQMAX,
     C INFILE,SIMO)

C      
C     C 
C     C COVMAT,ACHISQRI,ACHISQRO,
C     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,COVMAT2,FCOMPAC2,
C     C ACOMPAC3,ACOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5)
      INCLUDE 'PARAM.H'

        REAL FCOMPAC2,FCOMPAC5,
     C KCHISQR,ACOMPAC3,ACOMPAC4,ACHISQRI(MAXKLIQ),ACHISQRO(MAXKLIQ),
     C GCENTRAL(MAXKLIQ),ICON(MAXKLIQ),ISTD(MAXKLIQ),IEXPECT(MAXKLIQ),
     C FIXR,INDEPT,GLAMNDA,TABLE1A,TABLE1B,TABLE1C,TABLE1D
          CHARACTER INFILE*16
C       CHARACTER LABEL(MAXKLIQ)*9,TITLES(3)*20

C      CALL HUBVAR(HUBERT,RESULTM,NUMTEACH,CHNGSIM,CHNGSTD,CHNGCON)
C      CALL HUBVAR(NEWMAT,RESULTM,NUMTEACH,HUBSIM,STDHS,ALLCON)

      REAL MEANWT(MAXKLIQ),VARWT(MAXKLIQ),AVAR2,
     C NOB,TWEIGHT,BESTVAL,
     C STOTCON,AMEAN,AVAR,PEARSON,EQUIPEAR,
     C FCOMPACT,HUBSIM,STDHS,OUTOF,ZABS,PCON,
     C CHNGSIM,CHNGSTD,TOPVAL
      
      INTEGER
     C  MAXDEPT,DEPARTN(MAXKLIQ),HYPERG,REVERSE,SIMO,
     C NUMTEACH,RCHOICE(MAXKLIQ),NEWDEPT(MAXKLIQ),
     C GROUP1,GROUP2,DMEMBERS(MAXKLIQ),THISPER,KTEMPS,I,J,
     C LMAXDEPT,STRUCTEQ,NEWGRPS,
     C K,LENGTH,NO2,G2,G3,PRINTT,FINAL,FSYMMAT,OLDDEPT(MAXKLIQ),
     C NEVAL,ENUFVAL,NBESTDEP(MAXKLIQ),FC,PEDRO1,PRINTO(100),
     C LGROUP(MAXKLIQ),RP1,RP2,NUMRES,IMAX(1000),TRYDEPT(MAXKLIQ),
     C ORDER(1000),NUMPRED,CRES,QUANTYPE,PERGROUP,SQUAREIT,
     C BOBSCONI(MAXKLIQ),BOBSCONO(MAXKLIQ),TG1

       REAL ALLCON,CHNGCON,PC,UCUT,BASEVAL,INCREM,TM,TSTD,
     C OBFUN(1000),PREDICT(1000,1)
       DOUBLE PRECISION USEED,QSEED,
     C ISEEDS(1000)
       REAL ICUTS(1000),MDIAG,VDIAG,CDIAG,
     C BCMEANI(MAXKLIQ),BCMEANO(MAXKLIQ)

C        CALL ASSIGN2(NUMTEACH[I] ,NEWDEPT[I251] ,MAXDEPT[I] 
C       ,ALLGROUP[I251,251]
C    C  ,DEPARTN[I251],RCHOICE[I251],ALLGROUR[I251,251]
C     ,MEANWT[R251] ,VARWT[R251],
C     C  1,2)



       REAL KSIGN,TEMP(2),XYBAR(2),A(3),ALFA,ANOVA(14),B(2,7),
     C VARB(1),BETA(2),RES(1000,4),MYRES(1000),TCOMPACT,
     C TSS,WSS,EVALFUN,FCOMPAC6,FCOMPAC7,FCOMPAC8,FCOMPAC9,
     C LRT,BCENT1(MAXKLIQ),BCENT2(MAXKLIQ),TINCREM,NLRT,
     C HIWTEVAL,REAL
       INTEGER NBR(6),IER,IB,IH(2),HOLDOFF,NUMIN,HIGHRES,XTCOUNT,
     C KQMAX
C       PARAMETER (PAR1=11)
C       PARAMETER (CPAR1=2**PAR1)
       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ),
     C COVMAT(MAXGR,MAXGR),COVMAT2(MAXGR,MAXGR),
     C COVMAT3(MAXGR,MAXGR),COVMAT4(MAXGR,MAXGR)

       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)

C      HUBERT AND RESULTM SWITCHED INTENTIONALLY
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

C       COMMON ZCOMPMAT,ALLGROUP,RESULTM,HUBERT,NEWMAT

       OPEN(85, FILE='obfun.dat')
       BESTVAL=0.000
      ENUFVAL=1
      INCREM=(TOPVAL-BASEVAL)/(NEVAL)
      QSEED=5163516.D0
      USEED=4161416.D0

      CRES=1
      SUMWT=0
      DO 987 I=1,NEVAL
      SUMWT=SUMWT+INCREM/I
00987  CONTINUE
      UCUT=TOPVAL
C      SUMWT=HIWT*(NEVAL+1)*NEVAL/2
      DO WHILE (ENUFVAL .LE. (NEVAL+1.))
      IF (ENUFVAL .GT. 1) THEN
      TINCREM=(INCREM/(ENUFVAL-1.))/SUMWT
      ELSE
      TINCREM=0
       END IF
      ORDER(ENUFVAL)=ENUFVAL
      PEDRO1=1
      UCUT=UCUT-TINCREM
        ISEEDS(ENUFVAL)=USEED
        ICUTS(ENUFVAL)=UCUT
        IMAX(ENUFVAL)=MAXDEPT
      CALL RESORTO3(OLDDEPT,NUMTEACH,QSEED,USEED,UCUT,NEWDEPT,
     C MAXDEPT,NEWGRPS)

C      SUBROUTINE RESORTO3 (ELEMENTS,NUMELEM,RSEED,USEED,UCUT,
C     C  NELEMENT,TMAXDEPT,NEWGRPS)

        CALL ASSIGN2(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN)
        CALL REMOVEO4(MAXDEPT,DEPARTN,LGROUP,1,CUTOFF,0)
        NUMIN=0
        DO 56 RP1=1,NUMTEACH
          IF (DEPARTN(NEWDEPT(RP1)) .GT. 1) THEN
          NUMIN=NUMIN+1
          END IF
          NEWDEPT(RP1)=LGROUP(NEWDEPT(RP1))
00056    CONTINUE

        CALL ASSIGN2(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN) 



C       MDIAG = 0
C       VDIAG = 0
C       CDIAG=0
C       IF (MAXDEPT .GT. 250) THEN 
C         CALL MYSTOP
C       END IF
C
C      NOB=0.0000
C      TWEIGHT=1.0000
C
       REVERSE=0
      IF (STRUCTEQ .EQ. 1) THEN
      CALL SLOGIT(MAXDEPT,DEPARTN,NUMTEACH,
     C NEWDEPT,
     C COVMAT,FCOMPACT,
     C TSS,WSS,GROUPMAT,
     C ROWWT,COLWT,KQMAX)
C      SUBROUTINE SLOGIT(MAXDEPT,DEPARTN,NUMTEACH,
C     C NEWDEPT,COVMAT,FCOMPACT,TSS,WBSS,GROUPMAT,
C     C ROWWT,COLWT)

       FCOMPACT=(TSS-WSS)*(NUMTEACH**2-MAXDEPT**2)/
     C ((MAXDEPT**2 -1)*WSS)

      CALL LOGIT(MAXDEPT,DEPARTN,NEWMAT,NUMTEACH,
     C RCHOICE,NEWDEPT,MEANWT,VARWT,
     C FINAL,FSYMMAT,TCOMPACT,ACHISQRI,ACHISQRO,
     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,FCOMPAC2,
     C ACOMPAC3,ACOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5,
     C PERGROUP,QUANTYPE,SQUAREIT,EVALFUN,FCOMPAC6,FCOMPAC7,
     C FCOMPAC8,FCOMPAC9,FIXR,PEARSON,EQUIPEAR,
     C LRT,BCENT1,BCENT2,REVERSE,XCOVMAT,COVMAT2,COVMAT3,COVMAT4,
     C HYPERG,KQMAX,PRINTO(27),INFILE,SIMO,NLRT,
     C BCMEANI,BCMEANO,BOBSCONI,BOBSCONO)
       ELSE

      CALL LOGIT(MAXDEPT,DEPARTN,NEWMAT,NUMTEACH,
     C RCHOICE,NEWDEPT,MEANWT,VARWT,
     C FINAL,FSYMMAT,TCOMPACT,ACHISQRI,ACHISQRO,
     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,FCOMPAC2,
     C ACOMPAC3,ACOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5,
     C PERGROUP,QUANTYPE,SQUAREIT,EVALFUN,FCOMPAC6,FCOMPAC7,
     C FCOMPAC8,FCOMPAC9,FIXR,PEARSON,EQUIPEAR,
     C LRT,BCENT1,BCENT2,REVERSE,COVMAT,COVMAT2,COVMAT3,
     C COVMAT4,
     C HYPERG,KQMAX,PRINTO(27),INFILE,SIMO,NLRT,
     C BCMEANI,BCMEANO,BOBSCONI,BOBSCONO)
C  QQQ

       
         FCOMPACT=TCOMPACT
      END IF

      IF (FCOMPACT .GT. BESTVAL) THEN 
       DO 00019 FC=1,NUMTEACH
        NBESTDEP(FC)=NEWDEPT(FC)
00019    CONTINUE
        BESTVAL=FCOMPACT
       END IF

      TM=0.00
      TSTD=0.00
      CALL HUBIZE(NEWDEPT,NUMTEACH,RESULTM,STRUCTEQ)

      CALL HUBVAR(HUBERT,RESULTM,NUMTEACH,CHNGSIM,CHNGSTD,CHNGCON,
     C TM,TSTD,XTCOUNT)
      TM=0.00
      TSTD=0.00
      CALL HUBVAR(NEWMAT,RESULTM,NUMTEACH,HUBSIM,STDHS,ALLCON,TM,
     C TSTD,XTCOUNT)
      CHNGSIM=CHNGSIM/2
C   input (id pct chngcnt chngstd fcompact increm hubert
C   hubdiag pearson g2 hubdiagx pearsonx g2x) 

      TABLE1D=0
      TABLE1B=0
      INDEPT=0
      DO 2525 TG1=1,MAXDEPT  
      IF (DEPARTN(TG1) .GT. 0) THEN
      INDEPT=INDEPT+DEPARTN(TG1)*(DEPARTN(TG1)-1)
      TABLE1B=TABLE1B+BOBSCONO(TG1)
      TABLE1D=TABLE1D+BOBSCONI(TG1)
       END IF

02525  CONTINUE

       INDEPT=INDEPT*HIWTEVAL
      TABLE1C=INDEPT-TABLE1D
      TABLE1A=NUMTEACH*(NUMTEACH-1)*HIWTEVAL
     C  - (TABLE1B + TABLE1D)-TABLE1C

       GLAMNDA=TABLE1D*TABLE1A
       GLAMNDA=GLAMNDA/(TABLE1B*TABLE1C)
       GLAMNDA=LOG(GLAMNDA)/2

       WRITE(85,251) ENUFVAL,UCUT,CHNGSIM,CHNGSTD,FCOMPACT,TINCREM,
     C STDHS,FCOMPAC2,ACOMPAC3,ACOMPAC4,FCOMPAC5,FCOMPAC6,FCOMPAC7,
     C TCOMPACT,GLAMNDA
        OBFUN(ENUFVAL)=FCOMPACT
        PREDICT(ENUFVAL,CRES)=CHNGSTD
        ENUFVAL=ENUFVAL+1

       END DO
       HOLDOFF=1
       IF (NUMRES .GT. 1) THEN
        NUMPRED=1
        CALL KGETRES(OBFUN,PREDICT,NUMPRED,NEVAL,HIGHRES)


C       NBR(1)=2
C       NBR(2)=NEVAL
C       NBR(3)=NEVAL
C       NBR(4)=1
C       NBR(5)=1
C       NBR(6)=1
C
C       CALL BECOVM(OBFUN,NEVAL,NBR,TEMP,XYBAR,A,IER)
C       ALFA=0.05
C       IB=2
C       IH(1)=3
C       IH(2)=1
C       BETA(2)=B(1,1)
C       BETA(1)=B(2,1)
C       CALL RLMUL (A,XYBAR,NEVAL,1,ALFA,ANOVA,B,IB,VARB,IER)
C       CALL RLRES (OBFUN,NEVAL,2,ENUFVAL,IH,2,BETA,
C     C ANOVA(12),RES,ENUFVAL,IER)
C       DO 99 I=1,NEVAL
C       MYRES(I)=RES(I,3)
C00099   CONTINUE

C      CALL SPSORT(ORDCLOSE,NUMIN,SLOTA)
C       CALL SPSORT(RESIDS,NEVAL,ORDER)
C      CALL RESORTO3(OLDDEPT,NUMTEACH,QSEED,USEED,UCUT,NEWDEPT,
C     C MAXDEPT)

      CALL RESORTO3(OLDDEPT,NUMTEACH,QSEED,
     C ISEEDS(HIGHRES),ICUTS(HIGHRES),TRYDEPT,
     C IMAX(HIGHRES),NEWGRPS)

C      SUBROUTINE RESORTO3 (ELEMENTS,NUMELEM,RSEED,USEED,UCUT,
C     C  NELEMENT,TMAXDEPT,NEWGRPS)

        CALL ASSIGN2(NUMTEACH,TRYDEPT,MAXDEPT,
     C  DEPARTN)
        CALL REMOVEO4(MAXDEPT,DEPARTN,LGROUP,1,CUTOFF,0)
        DO 856 RP1=1,NUMTEACH
          NEWDEPT(RP1)=LGROUP(NEWDEPT(RP1))
00856    CONTINUE

        
       ELSE 
       DO 9988 RP2=1,NUMTEACH
       TRYDEPT(RP2)=NEWDEPT(RP2)
09988   CONTINUE

       END IF
        CALL ASSIGN2(NUMTEACH,TRYDEPT,MAXDEPT,
     C  DEPARTN)
  251 FORMAT(25(F10.5)) 

      RETURN

      END
