
       SUBROUTINE KGETRES(OBFUN,PREDICT,NUMPRED,NEVAL,HIGHRES)
       INTEGER NEVAL,NUMPRED,I,J,IER,IAINV,IBETAHAT,IER2,C,HIGHRES
       REAL OBFUN(1000),PREDICT(1000,2),TRESIDS,
     C BESTRES,
     C  SXX(1000,1000),XBAR(1000),YBAR,SXY(1000),
     C S(1000),WK(2*1000),INVSXX(1000,1000),
     C BETAHAT(1000,1),PREDVAL(1000),BETA0,TBETA

C     C BETAHAT,IBETAHAT,IER2)

C     C IAINV,S,WK,IER)
       
       DO 02 I=1,NEVAL
       C=I-1
       DO 03 J=1,NUMPRED
       DO 04 K=1,(J-1)
       SXX(J,K)=SXX(J,K)+(PREDICT(I,J)-XBAR(J))*
     C  (PREDICT(I,K)-XBAR(K))*C/(C+1)
       SXX(K,J)=SXX(J,K)
 0004   CONTINUE
       SXX(J,J)=SXX(J,J)+(C/(C+1.))*(PREDICT(I,J)-XBAR(J))**2
       SXY(J)=SXY(J)+(C/(C+1.))*(PREDICT(I,J)-XBAR(J))*
     C                         (OBFUN(I)-YBAR)
       XBAR(J)=XBAR(J)+(1./(C+1.))*(PREDICT(I,J)-XBAR(J))
00003   CONTINUE
       YBAR=YBAR+(1./(C+1.))*(OBFUN(I)-YBAR) 
 0002    CONTINUE
       BESTRES=0
       IF (NUMPRED .GT. 1) THEN
C       FIND OTHER REGRESSION ROUTINE
C       CALL LGINF(SXX,NUMPRED,NUMPRED,NUMPRED,.0,INVSXX,
C     C IAINV,S,WK,IER)

C      FIND OTHER REGRESSION ROUTINE 
C       CALL VMULFF(INVSXX,SXY,NUMPRED,NUMPRED,1,NUMPRED,NUMPRED,
C     C BETAHAT,IBETAHAT,IER2)
       DO 08 I=1,NEVAL
       DO 09 J=1,NUMPRED
       BETAHAT(J,1)=1
       PREDVAL(I)=PREDVAL(I)+BETAHAT(J,1)*PREDICT(I,J)
 0009  CONTINUE
       TRESIDS=OBFUN(I)-PREDVAL(I)
       IF (TRESIDS .GT. BESTRES) THEN
       HIGHRES=I
        BESTRES=TRESIDS
        END IF
 0008   CONTINUE
       ELSE
       TBETA=SXY(1)/SXX(1,1)
       BETA0=YBAR-TBETA*XBAR(1)
       DO 11 I=1,NEVAL
       TRESIDS=OBFUN(I)-(BETA0+ TBETA*PREDICT(I,1))
       IF (TRESIDS .GT. BESTRES) THEN
        HIGHRES=I
        BESTRES=TRESIDS
        END IF
 0011   CONTINUE
       END IF


       RETURN
       END
