
      
       SUBROUTINE KMISS(NOWMISS,NUMTEACH,SSEED,TAKEOUT)
      INCLUDE 'PARAM.H'
          INTEGER NUMTEACH,TAKEOUT(MAXKLIQ),NREMOVE,
     C INLIST(MAXKLIQ),I
          REAL NOWMISS
          DOUBLE PRECISION SSEED

          DO 21 I=1,NUMTEACH
          INLIST(I)=I
          TAKEOUT(I)=0
00021      CONTINUE
          CALL RESORTO (INLIST,NUMTEACH,SSEED)
          NREMOVE=INT(NOWMISS*NUMTEACH)

          DO 22 I=1,NREMOVE

          IF ((INLIST(I) .GT. 0) .AND. (INLIST(I) .LE. MAXKLIQ)) THEN
          TAKEOUT(INLIST(I))=1
          END IF

00022     CONTINUE
          RETURN
           END
