
C         CALL KMULTMA3(ZCOMPMAT,ELGC,RCHOICE,DIRECT,TWXPX,DSYMMAT,
C     C ONLIST,1,PERSON1,PERSON2,ELGLIST,LOWMEM)

       SUBROUTINE KMULTMA3(SIZE,RCHOICE,KDIRECT,WTXPX,WTXXP,
     C ONLIST,NUMDYAD,PERSON1,PERSON2,ELGLIST,LOWMEM,TOTSIZE)
      INCLUDE 'PARAM.H'
C                                                      SYMMAT,WT     
        INTEGER SIZE,I,J,K,A,RCHOICE(MAXKLIQ),ONLIST(MAXKLIQ),NUMDYAD,
     C  OCOUNT,H,IHAVE(MAXKLIQ),PERSON1,PERSON2,TI,TJ,TK,TA,
     C  ELGLIST(MAXKLIQ),LOWMEM,TOTSIZE,G
          REAL WTXPX,WTXXP,BESTTRID

        REAL VINMAT(MAXKLIQ,MAXKLIQ),CONNECTO
        DOUBLE PRECISION TXPX,TXXP
        REAL KDIRECT,TIA,TAI,TJA,TAJ,TAK,TKA

       INTEGER ALLGROUP(MAXKLIQ,MAXKLIQ),HUBERT(MAXKLIQ,MAXKLIQ),
     C RESULTM(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON VINMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

C       COMMON VINMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT

       DO 2 G=1,SIZE
       IHAVE(G)=0
    2     CONTINUE

        PERSON1=LOWMEM
        PERSON2=LOWMEM
C       DO 5 H=1,NUMDYAD

        BESTTRID=-999999  

           I=LOWMEM
           DO 40 TJ=2,SIZE
           J=ELGLIST(TJ)
           IF ((IHAVE(TJ) .EQ. 0) .AND. (RCHOICE(J) .GT. 0) .AND.
     C      (J .NE. I)) THEN
            DO 50 TK=1,(TJ-1)
            K=ELGLIST(TK)
           IF ((IHAVE(TK) .EQ. 0) .AND. (RCHOICE(K) .GT. 0) .AND.
     C     (K .NE. I)) THEN
         TXPX=0
         TXXP=0
         CONNECTO=0
         DO 60 A=1,TOTSIZE
         IF (A .EQ. I) THEN
         TAI=KDIRECT
         TIA=KDIRECT
         ELSE
         TAI=VINMAT(A,I)
         TIA=VINMAT(I,A)
         END IF
         IF (A .EQ. J) THEN
         TAJ=KDIRECT
         TJA=KDIRECT
         ELSE
         TAJ=VINMAT(A,J)
         TJA=VINMAT(J,A)
         END IF
         IF (A .EQ. K) THEN
         TAK=KDIRECT
         TKA=KDIRECT
         ELSE
         TAK=VINMAT(A,K)
         TKA=VINMAT(K,A)
         END IF
         TXPX=TXPX+TAI*TAJ+TAI*TAK+TAJ*TAK
         TXXP=TXXP+TIA*TJA+TIA*TKA+TJA*TKA
   60    CONTINUE

          CONNECTO=TXPX*WTXPX+TXXP*WTXXP

          IF (CONNECTO .GT. BESTTRID) THEN
          PERSON1=J
          PERSON2=K
          BESTTRID=CONNECTO
          END IF

          END IF
C         WRITE(504,504) I,J,K, TXXPRIME(I,J,K), TXPRIMEX(I,J,K)
   50    CONTINUE
         END IF
   40  CONTINUE
      RETURN
  502 FORMAT(A12,1X)
  504 FORMAT(20(F10.5))
  251 FORMAT(20(F10.5))
      END
