
       SUBROUTINE KMULTMA2(SIZE,RCHOICE,KDIRECT,WTXPX,WTXXP,
     C ONLIST,NUMDYAD,PERSON1,PERSON2,PERSON3)
      INCLUDE 'PARAM.H'
C                                                      SYMMAT,WT     
        INTEGER SIZE,I,J,K,A,RCHOICE(MAXKLIQ),ONLIST(MAXKLIQ),NUMDYAD,
     C  OCOUNT,H,IHAVE(MAXKLIQ),PERSON1(MAXKLIQ),PERSON2(MAXKLIQ),
     C  PERSON3(MAXKLIQ),G
          REAL WTXPX,WTXXP

        REAL VINMAT(MAXKLIQ,MAXKLIQ)
        DOUBLE PRECISION TXPX,TXXP,BESTTRID,CONNECTO
        REAL KMAT(MAXKLIQ,MAXKLIQ),INMAT(MAXKLIQ,MAXKLIQ),KDIRECT

       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),
     C NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON VINMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

C       COMMON VINMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT


       DO 2 G=1,SIZE
       IHAVE(G)=0
    2     CONTINUE

       DO 5 H=1,NUMDYAD
        BESTTRID=-999999  
C       WRITE(503,251) 999
      DO 10 I=1,SIZE
      DO 20 J=1,SIZE
        INMAT(I,J)=VINMAT(I,J)
        KMAT(I,J)=INMAT(I,J)
        IF (I .EQ. J) THEN
         KMAT(I,J)=KDIRECT
        INMAT(I,J)=KDIRECT
        END IF
   20 CONTINUE
   10 CONTINUE

         DO 30 I=3,SIZE
           IF ((IHAVE(I) .EQ. 0) .AND. (RCHOICE(I) .GT. 0)) THEN
           DO 40 J=2,(I-1)

           IF ((IHAVE(J) .EQ. 0) .AND. (RCHOICE(J) .GT. 0)) THEN
            DO 50 K=1,(J-1)
           IF ((IHAVE(K) .EQ. 0) .AND. (RCHOICE(K) .GT. 0)) THEN
         TXPX=0
         TXXP=0
C          IF ((RCHOICE(I) .GT. 0)  .AND. (RCHOICE(J) .GT. 0)
C     C .AND. (RCHOICE(K) .GT. 0)) THEN
         CONNECTO=0
         DO 60 A=1,SIZE
         TXPX=TXPX+KMAT(A,I)*INMAT(A,J)
         TXPX=TXPX+KMAT(A,I)*INMAT(A,K)
         TXPX=TXPX+KMAT(A,J)*INMAT(A,K)
         TXXP=TXXP+INMAT(I,A)*KMAT(J,A)+
     C                                  INMAT(I,A)*KMAT(K,A)+
     C                                  INMAT(J,A)*KMAT(K,A)
   60    CONTINUE

          CONNECTO=TXPX*WTXPX+TXXP*WTXXP

          IF (CONNECTO .GT. BESTTRID) THEN
          PERSON1(H)=I
          PERSON2(H)=J
          PERSON3(H)=K
          BESTTRID=CONNECTO
          END IF

          END IF
C         WRITE(504,504) I,J,K, TXXPRIME(I,J,K), TXPRIMEX(I,J,K)
   50    CONTINUE
         END IF
   40  CONTINUE
         END IF
   30 CONTINUE
      OCOUNT=3*(H-1)
      ONLIST(OCOUNT+1)=PERSON1(H)
      ONLIST(OCOUNT+2)=PERSON2(H)
      ONLIST(OCOUNT+3)=PERSON3(H)
      IF (PERSON1(H) .GT. .0001) THEN
      IHAVE(PERSON1(H))=1
      END IF
      IF (PERSON2(H) .GT. .0001) THEN
      IHAVE(PERSON2(H))=1
      END IF
      IF (PERSON3(H) .GT. .0001) THEN
      IHAVE(PERSON3(H))=1
      END IF
    5 CONTINUE

      RETURN
  502 FORMAT(A12,1X)
  504 FORMAT(20(F10.5))
  251 FORMAT(20(F10.5))
      END
