
       SUBROUTINE KMULTMAD(INMAT,SIZE,RCHOICE,KDIRECT,WTXPX,WTXXP,
     C ONLIST,NUMDYAD,PERSON1,PERSON2)
      INCLUDE 'PARAM.H'
C                                                      SYMMAT,WT     
        INTEGER SIZE,I,J,K,A,RCHOICE(MAXKLIQ),ONLIST(MAXKLIQ),NUMDYAD,
     C  OCOUNT,H,IHAVE(MAXKLIQ),PERSON1(MAXKLIQ),PERSON2(MAXKLIQ),G
     
          REAL WTXPX,WTXXP

        REAL CONNECTO,BESTTRID

C       REAL VINMAT(MAXKLIQ,MAXKLIQ),KMAT(MAXKLIQ,MAXKLIQ)

        DOUBLE PRECISION TXPX,TXXP
        REAL INMAT(MAXKLIQ,MAXKLIQ),KDIRECT

C       WRITE(33,251) WTXPX,WTXXP

       DO 2 G=1,SIZE
       IHAVE(G)=0
       INMAT(G,G)=KDIRECT  
    2     CONTINUE

       DO 5 H=1,NUMDYAD
        BESTTRID=-999999  
C       WRITE(503,251) 999

         DO 30 I=2,SIZE
           IF ((IHAVE(I) .EQ. 0) .AND. (RCHOICE(I) .GT. 0)) THEN

           DO 40 J=1,(I-1)

           IF ((IHAVE(J) .EQ. 0) .AND. (RCHOICE(J) .GT. 0)) THEN
         TXPX=0
         TXXP=0
         CONNECTO=0
         DO 60 A=1,SIZE
         
         TXPX=TXPX+INMAT(A,I)*INMAT(A,J)
         TXXP=TXXP+INMAT(I,A)*INMAT(J,A)
   60    CONTINUE


          CONNECTO=TXPX*WTXPX+TXXP*WTXXP
C          LOOKMAT(I,J)=CONNECTO

          IF (CONNECTO .GT. BESTTRID) THEN
          PERSON1(H)=I
          PERSON2(H)=J
          BESTTRID=CONNECTO
          END IF
C
           END IF

C         WRITE(504,504) I,J,K, TXXPRIME(I,J,K), TXPRIMEX(I,J,K)
   40  CONTINUE
         END IF
   30 CONTINUE
      OCOUNT=2*(H-1)
      ONLIST(OCOUNT+1)=PERSON1(H)
      ONLIST(OCOUNT+2)=PERSON2(H)
      IHAVE(PERSON1(H))=1
      IHAVE(PERSON2(H))=1
    5 CONTINUE


      RETURN
  502 FORMAT(A12,1X)
  504 FORMAT(50(F10.5))
  251 FORMAT(50(F10.5))
      END
