
      
      
      SUBROUTINE KSTRESS(STRESS,COORD,XNORMAL,MATLEN,
     C MAXVAL,XMINVAL,KEXP,STRESS2,FIT,ISTRESS,STRESS3,
     C ISTRESS2,ISTRESS3,COORD2,DISTFILE,PRINTO,NEWDEPT,
     C ID,ODDSRATI)
      INCLUDE 'PARAM.H'

      INTEGER NUMTEACH,NORMAL,MATLEN,PRINTO(100),ADDEND,
     C NEWDEPT(MAXKLIQ),ID(MAXKLIQ),XNORMAL,NOLOG

      CHARACTER*12 DISTFILE
      CHARACTER*6 INFILE

      REAL COORD(MAXKLIQ,2),PDIST,MAXVAL,MINVAL,TH,TEMPCELL,KEXP,TKEXP,
     C TCELLI,TCELLJ,FIT(MAXKLIQ),ACTJ,POSSJ,ISTRESS(MAXKLIQ),XSTRESS,
     C COMPA,COMPB,COMPC,COMPD,COMP2A,COMP2B,COMP2C,COMP2D,
     C ISTRESS2(MAXKLIQ),ISTRESS3(MAXKLIQ),COORD2(MATLEN,2),ODDSRATI,
     C COEFF,TOTDYAD,TEMPVAL,XMINVAL

      DOUBLE PRECISION STRESS,STRESS2,STRESS3,SCALEFAC,SQDIST,
     C SUMDIST

       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ),
     C ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF
        MINVAL=ABS(XMINVAL)
        NOLOG=0
        IF (XNORMAL .LT. 0) THEN
        NOLOG=1
        END IF
        NORMAL=ABS(XNORMAL)

      TKEXP=ABS(KEXP)
       
      IF (PRINTO(43) .EQ. 1) THEN
      INFILE=DISTFILE(1:6)
      DISTFILE='compgrp.idis'
      OPEN(29,file=DISTFILE)

       IF (PRINTO(27) .EQ. 1) THEN
        CALL MOVEEND(29)
       END IF 
      END IF

      DO 18 I=1,MATLEN
       ISTRESS(I)=0
00018   CONTINUE
      
      TH=1
      IF ((MAXVAL .GT. 0) .AND. (NORMAL .EQ. 3)) THEN
      TH=MAXVAL
      END IF
       COMPA=0
       COMPB=0
       COMPC=0
       COMPD=0 
       COMP2A=0
       COMP2B=0
       COMP2C=0
       COMP2D=0 

       STRESS=0
       STRESS2=0
       SCALEFAC=0
       MEANDIST=0
       SQDIST=0
       SUMDIST=0
      
       CALL KFIT(MATLEN,FIT,ODDSRATI)
       OPEN(24,file='coeff')
       REWIND(24)
       COEFF=1
       READ(24,6261,END=8888) COEFF
08888  CLOSE(24)

       DO 2 I=2,MATLEN

       DO 3 J=1,(I-1.)
       PDIST=0
       IF (((COORD(I,1)-COORD(J,1))**2 .GE. .000001) .AND.
     C ((COORD(I,2)-COORD(J,2))**2 .GE. .000001)) THEN
       PDIST=SQRT((COORD(I,1)-COORD(J,1))**2+
     C            (COORD(I,2)-COORD(J,2))**2)
        END IF
C       END
C       IF (((COORD2(I,1)-COORD2(J,1))**2 .GT. .0000001) .AND.
C     C ((COORD2(I,2)-COORD2(J,2))**2) .GT. .0000001)) THEN 
        PDIST2=0
       IF (((COORD2(I,1)-COORD2(J,1))**2 .GE. .000001) .AND.
     C ((COORD2(I,2)-COORD2(J,2))**2 .GE. .000001)) THEN

       PDIST2=SQRT((COORD2(I,1)-COORD2(J,1))**2+
     C            (COORD2(I,2)-COORD2(J,2))**2)
        END IF
C       END
       IF (PRINTO(43) .EQ. 1) THEN
       WRITE(29,443) INFILE,ID(I),ID(J),PDIST,PDIST2,
     C MATLEN,NEWDEPT(I),NEWDEPT(J)
       END IF
       IF (HUBERT(I,J) .EQ. 1) THEN

       IF (RESULTM(I,J) .EQ. 1) THEN
        COMPA=COMPA+1
        COMP2A=COMP2A+(MAXVAL-PDIST)*(MAXVAL-PDIST2)
       ELSE
        COMPB=COMPB+1
        COMP2B=COMP2B+PDIST*(MAXVAL-PDIST2)
       END IF
       ELSE
       IF (RESULTM(I,J) .EQ. 1) THEN
        COMPC=COMPC+1
        COMP2C=COMP2C+(MAXVAL-PDIST)*PDIST2
       ELSE
        COMPD=COMPD+1
        COMP2D=COMP2D+PDIST*PDIST2
       END IF
       END IF
      TEMPVAL=(NEWMAT(I,J)+NEWMAT(J,I))/2.0000

      IF ((NORMAL .GT. 3) .OR. (NORMAL .LT. 2)) THEN
      TEMPVAL=MAXVAL-TEMPVAL
      END IF
      IF ((NORMAL .EQ. 2) .OR. (NORMAL .EQ. 3)) THEN
      IF (TEMPVAL .LT. MINVAL) THEN 
      TEMPVAL=MINVAL
      END IF
      IF (NOLOG .EQ. 0) THEN
      TEMPVAL=LOG(TH)-LOG(TEMPVAL)
      ELSE
      TEMPVAL=TH/TEMPVAL 
      END IF
      END IF
       XSTRESS=0
C       IF (((PDIST-TEMPVAL) .GT. 0) .AND. 
C     C  (ABS(PDIST-TEMPVAL) .LT. 99999)  .AND.
C     C   (TKEXP .LT. 20)) THEN
C         WRITE(33,6261) PDIST,TEMPVAL,TKEXP
C       IF ((ABS(PDIST-TEMPVAL)**TKEXP) .LT. 99999) THEN
C       XSTRESS=(PDIST-TEMPVAL)**TKEXP
C       END IF
C       END IF
       SUMDIST=SUMDIST+PDIST
       SQDIST=SQDIST+PDIST**2
       STRESS=STRESS+XSTRESS
       ISTRESS(I)=ISTRESS(I)+XSTRESS/(MATLEN-1)
       ISTRESS(J)=ISTRESS(J)+XSTRESS/(MATLEN-1) 

00003  CONTINUE
00002   CONTINUE
        TOTDYAD=MATLEN*(MATLEN-1)/2
        SCALEFAC=SQDIST-(SUMDIST**2)/TOTDYAD
       
       STRESS=STRESS/SCALEFAC
       IF (COMPA .LT. 1) THEN
       COMPA=1
       END IF 
       IF (COMPB .LT. 1) THEN
       COMPB=1
       END IF 
       IF (COMPC .LT. 1) THEN
       COMPC=1
       END IF 
       IF (COMPD .LT. 1) THEN
       COMPD=1
       END IF 
       IF (COMP2A .LT. .01) THEN
       COMP2A=.01
       END IF 
       IF (COMP2B .LT. .01) THEN
       COMP2B=.01
       END IF 
       IF (COMP2C .LT. .01) THEN
       COMP2C=.01
       END IF 
       IF (COMP2D .LT. .01) THEN
       COMP2D=.01
       END IF 
       STRESS2=LOG(COMPA) +LOG(COMPD) - LOG(COMPC)-LOG(COMPB)
       STRESS3=LOG(COMP2A) +LOG(COMP2D) - LOG(COMP2C)-LOG(COMP2B)
C       STRESS=STRESS*2/(MATLEN*(MATLEN-1.))

       DO 22 I=1,MATLEN
       COMPA=0
       COMPD=0
       COMPC=0
       COMPD=0
       COMP2A=0
       COMP2D=0
       COMP2C=0
       COMP2D=0

       DO 23 J=1,MATLEN
       PDIST=0
       IF (((COORD(I,1)-COORD(J,1))**2 .GE. .000001) .AND.
     C ((COORD(I,2)-COORD(J,2))**2 .GE. .000001)) THEN
       PDIST=SQRT((COORD(I,1)-COORD(J,1))**2+
     C            (COORD(I,2)-COORD(J,2))**2)
       END IF
       PDIST2=0
       IF (((COORD2(I,1)-COORD2(J,1))**2 .GE. .000001) .AND.
       
     C ((COORD2(I,2)-COORD2(J,2))**2 .GE. .000001)) THEN
       PDIST2=SQRT((COORD2(I,1)-COORD2(J,1))**2+
     C            (COORD2(I,2)-COORD2(J,2))**2)
        END IF
       IF (HUBERT(I,J) .EQ. 1) THEN
       IF (RESULTM(I,J) .EQ. 1) THEN
        COMPA=COMPA+1
        COMP2A=COMP2A+(MAXVAL-PDIST)*(MAXVAL-PDIST2)
       ELSE
        COMPB=COMPB+1
        COMP2B=COMP2B+PDIST*(MAXVAL-PDIST2)
       END IF
       ELSE
       IF (RESULTM(I,J) .EQ. 1) THEN
        COMPC=COMPC+1
        COMP2C=COMP2C+(MAXVAL-PDIST)*PDIST2
       ELSE
        COMPD=COMPD+1
        COMP2D=COMP2D+PDIST*PDIST2
       END IF
       END IF

00023  CONTINUE
       IF (COMPA .LT. 1) THEN
       COMPA=1
       END IF 
       IF (COMPB .LT. 1) THEN
       COMPB=1
       END IF 
       IF (COMPC .LT. 1) THEN
       COMPC=1
       END IF 
       IF (COMPD .LT. 1) THEN
       COMPD=1
       END IF 
       IF (COMP2A .LT. .01) THEN
       COMP2A=.01
       END IF 
       IF (COMP2B .LT. .01) THEN
       COMP2B=.01
       END IF 
       IF (COMP2C .LT. .01) THEN
       COMP2C=.01
       END IF 
       IF (COMP2D .LT. .01) THEN
       COMP2D=.01
       END IF 
       ISTRESS2(I)=LOG(COMPA) +LOG(COMPD) - LOG(COMPC)-LOG(COMPB)
       ISTRESS3(I)=LOG(COMP2A) +LOG(COMP2D) - LOG(COMP2C)-LOG(COMP2B)
00022   CONTINUE
      IF (PRINTO(43) .EQ. 1) THEN
      CLOSE(29)
      END IF

 6261  FORMAT(F10.5)
00251    FORMAT (2I10,2F10.5)
00443    FORMAT (A6,2I10,2F10.5,3I10)
       RETURN

       END
