     
C             CALL LMEAN(NEWMAT,NEWDEPT,NUMTEACH,GROUPMAT,MAXDEPT,
C     C DEPARTN,I,DIFF(I,J))

      SUBROUTINE LMEAN(NEWDEPT,NUMTEACH,GROUPMAT,MAXDEPT,
     C DEPARTN,THISPER,THISDIFF,ACTRSQR,TSS,ROWWT,COLWT,ZDEPT)
      INCLUDE 'PARAM.H'
      INTEGER NEWDEPT(MAXKLIQ),NUMTEACH,I,J,MAXDEPT,ZDEPT(MAXKLIQ),
     C DEPARTN(MAXKLIQ),THISPER,THISGRP,ACTRSQR
      REAL GROUPMAT(MAXKLIQ,MAXKLIQ),THISDIFF,TG,THISN,TREAL1,TSS,
     C ROWWT,COLWT,WDENOM
       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),
     C NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT
       WDENOM=ROWWT+COLWT

       THISGRP=NEWDEPT(THISPER)      
        THISDIFF=0.00
       THISN=DEPARTN(THISGRP)
       DO 5 J=1,NUMTEACH
       TREAL1=NEWMAT(THISPER,J)
      TG=GROUPMAT(THISGRP,J)*THISN/(THISN-1.)
     C - (TREAL1)/(THISN-1.)
       IF ((J .EQ. THISPER) .OR. (ZDEPT(J) .EQ. THISGRP))
     C  THEN
       WT=ROWWT
        ELSE
       WT=COLWT
       END IF
       WT=WT/WDENOM
c      DIFF=DIFF+WT*(TREAL1-GROUPMAT(G,J))**2
       THISDIFF=THISDIFF+WT*(TG-TREAL1)**2
00005  CONTINUE
       IF (ACTRSQR .EQ. 1) THEN
       THISDIFF=THISDIFF*(THISN-1.)/THISN
       END IF

       THISDIFF=TSS-THISDIFF
        RETURN
        END
