
C      CALL LOGIT(MAXDEPT,DEPARTN,ALLGROUP,REVMAT,NUMTEACH,
C     C RCHOICE,NEWDEPT,MEANWT,VARWT,
C     C FINAL,FSYMMAT,COVMAT,FCOMPACT,BCHISQRI,BCHISQRO,
C     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG)

      SUBROUTINE LOGIT(MAXDEPT,DEPARTN,NEWMAT,NUMTEACH,
     C RCHOICE,NEWDEPT,MEANWT,VARWT,
     C FINAL,FSYMMAT,FCOMPACT,KCHISQRI,KCHISQRO,
     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,FCOMPAC2,
     C FCOMPAC3,FCOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5,
     C PERGROUP,QUANTYPE,SQUAREIT,EVALFUN,FCOMPAC6,FCOMPAC7,
     C FCOMPAC8,FCOMPAC9,FIXR,PEARSON,EQUIPEAR,
     C LRT,BCENT1,BCENT2,REVERSE,COVMAT,COVMAT2,COVMAT3,COVMAT4,
     C HYPERG,KQMAX,ADDEND,INFILE,SIMO,NLRT,
     C CHIMEANI,CHIMEANO,OBSCONI,OBSCONO)
      INCLUDE 'PARAM.H'

C LABEL,TITLES,PRINTT,KEEPLIST,
         CHARACTER INFILE*16
      REAL MEANWT(MAXKLIQ),VARWT(MAXKLIQ),
     C NOB,TWEIGHT,PEARSON,
     C FCOMPAC6,FCOMPAC7,
     C STOTCON,AMEAN,AVAR,MDIAG,VDIAG,CDIAG,
     C FCOMPACT,
     C OPCOMP,XDENOM1
C     C ACHISQRI,ACHISQRO,
C     C KCHISQR,GCENTRAL,
C     C ACOMPAC3,ACOMPAC4,ICON,IEXPECT,ISTD

      
      INTEGER MAXDEPT,DEPARTN(MAXKLIQ),PERGROUP,QUANTYPE,SQUAREIT,
     C NUMTEACH,RCHOICE(MAXKLIQ),NEWDEPT(MAXKLIQ),MACTG,
     C GROUP1,GROUP2,DMEMBERS(MAXKLIQ),THISPER,KTEMPS,I,J,
     C BDEPTN(MAXKLIQ),SIMO,NO,MULTI,MULTO,
     C FINAL,FSYMMAT,BDENOM,COMPD,
     C OBSCONO(MAXKLIQ),OBSCONI(MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ),
     C REVERSE,HYPERG,KQMAX,ADDEND,M,EACHPER,MAXCH,FLAGR

       REAL PCOMP,AVAR2,LRT,FIXR,BETAP,BETAQ,NLRT

       REAL KSIGN,KCHISQR,KCHISQRI(MAXKLIQ),KCHISQRO(MAXKLIQ),
     C CHIMEANI(MAXKLIQ),CHIMEANO(MAXKLIQ),CHIVARI(MAXKLIQ),
     C CHIVARO(MAXKLIQ),FCOMPAC2,FCOMPAC3,FCOMPAC4,UTOTCON,MT,VT,
     C GEXPECT(MAXKLIQ),GVAR(MAXKLIQ),GCENTRAL(MAXKLIQ),
     C GCON(MAXKLIQ),IEXPECT(MAXKLIQ),ICON(MAXKLIQ),ISTD(MAXKLIQ),
     C FCOMPAC5,EVALFUN,KSIGN2,ADDIN,PCOMP3,TOTCHOI(MAXKLIQ),
     C FCOMPAC8,NCOMPAC8,DCOMPAC8,DCOMPAC9,FCOMPAC9,DENOM1,
     C DENOM2,EQUIPEAR,BLAUDEN1(MAXKLIQ),BLAUDEN2(MAXKLIQ),
     C BLAUNUM(MAXKLIQ),BCENT1(MAXKLIQ),BCENT2(MAXKLIQ),
     C GRMEAN(MAXGR,MAXGR),GRVAR(MAXGR,MAXGR),
     C GTOTCON(MAXGR,MAXGR)
C                         I       I                I      I       I   
C         CALL HOWMANY (DMEMBERS,DEPARTN(GROUP2),THISPER,NEWMAT,NUMTEACH,
C                           R     I       R     R
C     C                  STOTCON,GROUP2,TWEIGHT,NOB)

      REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ),
     C COVMAT(MAXGR,MAXGR),
     C COVMAT2(MAXGR,MAXGR),
     C COVMAT3(MAXGR,MAXGR),
     C COVMAT4(MAXGR,MAXGR)


        REAL MU,VARP,MIBETAP,MIBETAQ,MOBETAP,TCHII,TCHIO,
     C MOBETAQ,RATIO,MIRATIO,MORATIO,ADD3,ADD4,ADD3A,ADD4A

       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),KNEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,KNEWMAT,
     C BLAUC,DIFF

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,KNEWMAT


       IF (MAXDEPT .LT. 51) THEN
        MULTI=1
        IF (REVERSE .EQ. 1) THEN
        MULTI=-1
        END IF
         
C         BIG LOOP FOR COVMAT
       IF (SIMO .EQ. 0) THEN
       OPEN(52,file='betap')
       OPEN(55,file='wtbetap')
       IF (ADDEND .EQ. 1) THEN
        CALL MOVEEND(52)
        CALL MOVEEND(55)
         END IF 
        END IF
      DO 70002 I=1,NUMTEACH
      DO 70003 J=1,NUMTEACH
      IF (REVERSE .EQ. 1) THEN
       IF (KNEWMAT(I,J) .GT. 0) THEN
         NEWMAT(I,J)=0
       ELSE
         TMW=INT(MEANWT(I))
         IF (MEANWT(I) .LT. 1) THEN
         TMW=1
         END IF
         NEWMAT(I,J)=TMW
       END IF
      ELSE
       NEWMAT(I,J)=KNEWMAT(I,J)
      END IF
70003     CONTINUE
       NEWMAT(I,I)=0
70002     CONTINUE
      IF (REVERSE .EQ. 1) THEN      
      CALL ARCHOICE(NUMTEACH,NEWMAT,RCHOICE,MAXCH,FIXR,FLAGR,
     C MEANWT,VARWT)
      END IF

      NO=1
      NOB=0.0000
      TWEIGHT=1.0000
      DCOMPAC8=0.000
      NCOMPAC8=0.0000
      DCOMPAC9=0.0000
      FCOMPAC5=0.000
      FCOMPAC2=0.000
      EVALFUN=0.000
      MIBETAP=0
      MIBETAQ=0
      MOBETAP=0
      MOBETAQ=0
      MORATIO=0
      MIRATIO=0   

      DO 119 GROUP1=1,MAXDEPT
        BLAUDEN1(GROUP1)=0.000
        BLAUDEN2(GROUP1)=0.000
        BLAUNUM(GROUP1)=0.000
        BCENT1(GROUP1)=0.000
        BCENT2(GROUP1)=0.0000
        CHIMEANI(GROUP1)=0.000
        CHIVARI(GROUP1)=0.0000
        CHIMEANO(GROUP1)=0.000
        CHIVARO(GROUP1)=0.000
        OBSCONO(GROUP1)=0.000
        OBSCONI(GROUP1)=0.000
        TOTCHOI(GROUP1)=0.000
        BDEPTN(GROUP1)=0
C         FOR EACH GROUP
        DO 121 GROUP2=1,MAXDEPT
           GRMEAN(GROUP1,GROUP2)=0.000
           GRVAR(GROUP1,GROUP2)=0.000
           GTOTCON(GROUP1,GROUP2)=0.000
           COVMAT2(GROUP1,GROUP2)=0.000
           COVMAT(GROUP1,GROUP2)=0.0000
           COVMAT3(GROUP1,GROUP2)=0.0000
            BETAP=0
            BETAQ=0
            MU=0
            VARP=0 
            MACTG=0
C
C          AND EVERY OTHER GROUP
C          MAKE VECTOR OF OTHER MEMBERS
C
         TOTCHOI(GROUP2)=0.000
         DO 122 M=1,DEPARTN(GROUP2)
          DMEMBERS(M)=ALLGROUP(GROUP2,M)
         TOTCHOI(GROUP2)=TOTCHOI(GROUP2)+RCHOICE(DMEMBERS(M))*
     C   MEANWT(DMEMBERS(M))
  122    CONTINUE

         DO 123 EACHPER=1,DEPARTN(GROUP1)
          THISPER=ALLGROUP(GROUP1,EACHPER)

C        ZZZ

         CALL HOWMANY (DMEMBERS,DEPARTN(GROUP2),THISPER,NEWMAT,NUMTEACH,
     C                  STOTCON,GROUP2,TWEIGHT,NOB,UTOTCON,MT,VT)
       IF ((REVERSE .EQ. 0) .AND. (SIMO .EQ. 0)) THEN
         WRITE(55,251) NUMTEACH,THISPER,GROUP1,GROUP2,MT,VT,
     C    STOTCON,UTOTCON,RCHOICE(THISPER)
       END IF
         BDENOM=DEPARTN(GROUP2)
         IF (GROUP1 .EQ. GROUP2) THEN
         BDENOM=BDENOM-1.
         END IF
         BDENOM=RCHOICE(THISPER) 
         IF (RCHOICE(THISPER) .GT. 0) THEN
          MACTG=MACTG+1.0
         MU=MU+UTOTCON/BDENOM
         VARP=VARP+(UTOTCON/BDENOM)**2
          END IF
         GTOTCON(GROUP1,GROUP2)=GTOTCON(GROUP1,GROUP2)+STOTCON
         IF (GROUP1 .EQ. GROUP2) THEN
         OBSCONI(GROUP1)=OBSCONI(GROUP1)+STOTCON
         ELSE
         OBSCONO(GROUP1)=OBSCONO(GROUP1)+STOTCON
         END IF

         KTEMPS=DEPARTN(GROUP2)+1
         IF (GROUP1 .EQ. GROUP2) THEN
          KTEMPS=KTEMPS-1
         END IF
         IF (RCHOICE(THISPER) .GT. 0) THEN
C      SUBROUTINE DISTRIB (THISR,THISWM,THISWV,MEAN,TVAR,KGRPSIZE,
C     C           TOTSIZE,THISPER,AVAR2)

         CALL DISTRIB (RCHOICE(THISPER),MEANWT(THISPER),
     C    VARWT(THISPER),AMEAN,AVAR,KTEMPS,NUMTEACH,THISPER,AVAR2,
     C    HYPERG)
         GRMEAN(GROUP1,GROUP2)=GRMEAN(GROUP1,GROUP2)+AMEAN
         GRVAR(GROUP1,GROUP2)=GRVAR(GROUP1,GROUP2)+AVAR

          OPCOMP=0
          PCOMP=0
         IF (AVAR .GT. 0) THEN
          OPCOMP=(STOTCON-AMEAN)/(SQRT(AVAR))
         ELSE 
         OPCOMP=0
         END IF
         IF ((QUANTYPE .EQ. 1) .OR. (QUANTYPE .GE. 4)) THEN
         PCOMP=OPCOMP
         END IF

         IF ((QUANTYPE .EQ. 2)
     C            .AND. (AMEAN .GT. 0)) THEN
         PCOMP=(STOTCON-AMEAN)/AMEAN**.5
         END IF
         IF (QUANTYPE .EQ. 3) THEN
         KSIGN=STOTCON/AMEAN
         IF (KSIGN .GT. 0) THEN
         PCOMP=2*STOTCON*LOG(KSIGN)
         ELSE
         PCOMP=0
         END IF
         END IF

         IF (SQUAREIT .EQ. 1) THEN
          IF (PCOMP .GT. 0) THEN
            KSIGN=1
          ELSE
            KSIGN=-1
          END IF
          PCOMP=KSIGN*PCOMP*PCOMP
         END IF
         IF (PERGROUP .EQ. 1) THEN
         IF (KTEMPS .GT. 1) THEN
         PCOMP=PCOMP/(KTEMPS-1.)
         ELSE
         PCOMP=0
         END IF
         END IF
         
         COVMAT2(GROUP1,GROUP2)=COVMAT2(GROUP1,GROUP2) + PCOMP

C         WRITE(555,251) THISPER,GROUP2,PCOMP 
         IF (GROUP1 .EQ. GROUP2) THEN
          EVALFUN=EVALFUN+PCOMP
          IEXPECT(THISPER)=AMEAN
          ISTD(THISPER)=AVAR**.5
          ICON(THISPER)=STOTCON
         FCOMPAC2=FCOMPAC2+ OPCOMP
         IF (DEPARTN(GROUP1) .GT. 1) THEN
         FCOMPAC5=FCOMPAC5+OPCOMP/(DEPARTN(GROUP1)-1.)
         END IF
         CHIMEANI(GROUP1)=CHIMEANI(GROUP1)+AMEAN
         CHIVARI(GROUP1)=CHIVARI(GROUP1)+AVAR2
         ELSE
         CHIMEANO(GROUP1)=CHIMEANO(GROUP1)+AMEAN
         CHIVARO(GROUP1)=CHIVARO(GROUP1)+AVAR2
         END IF

         END IF

  123   CONTINUE
        VARP=(VARP-MU**2/MACTG)/(MACTG-1.)
        MU=MU/MACTG
C        VARP=MU*(1.-MU)
        IF (MU .LT. .01) THEN
        MU=.01
         END IF
         IF (MU .GT. .99) THEN
          MU =.99
           END IF

C         FMU=(1.0-MU)/MU
C         BETAP=(1+FMU)**2
C         BETAP=BETAP*VARP
C         TBETAP=BETAP
C         BETAP=FMU/TBETAP
C         BETAP=BETAP-1.0
C         FMU=1.0+FMU
C         TFMU=FMU
C         FMU=1.0/TFMU 
C          TBETAP=BETAP
C         BETAP=TBETAP*FMU
        BETAP=(((1.0-MU)/MU)/(VARP*(1.0+(1.0-MU)/MU)**2) -1.0)*
     C  (1.0/(1.0+(1.0-MU)/MU))
C         FMU=(1.0-MU)
C         FMU=FMU/MU
        BETAQ=BETAP*(1.0-MU)/MU
        RATIO=0
        IF ((BETAP .GT. 0) .AND. (BETAQ .GT. 0)) THEN
        RATIO=BETAP/BETAQ
        END IF
        IF (SIMO .EQ. 0) THEN
        WRITE(52,544) INFILE,1,GROUP1,GROUP2,MU,VARP,BETAP,BETAQ,RATIO
        END IF
        IF (GROUP1 .EQ. GROUP2) THEN
        MIRATIO=MIRATIO+RATIO/MAXDEPT 
        MIBETAP=MIBETAP+BETAP/MAXDEPT 
        MIBETAQ=MIBETAQ+BETAQ/MAXDEPT
        ELSE
        MORATIO=MORATIO+RATIO/MAXDEPT
        MOBETAP=MOBETAP+BETAP/(MAXDEPT*(MAXDEPT-1.0)) 
        MOBETAQ=MOBETAQ+BETAQ/(MAXDEPT*(MAXDEPT-1.0)) 
        END IF 
  121   CONTINUE
  119  CONTINUE
        IF (SIMO .EQ. 0) THEN
        WRITE(52,544) INFILE,2,MIBETAP,MIBETAQ,MIRATIO,MOBETAP,MOBETAQ,
     C  MORATIO
        END IF
       DO 678 I=1,NUMTEACH
         IF (RCHOICE(I) .GT. 0) THEN 
          BDEPTN(NEWDEPT(I))=BDEPTN(NEWDEPT(I))+1.0000
         END IF
00678     CONTINUE

       MDIAG = 0.0000
       VDIAG = 0.0000
       CDIAG=0.0000
       KCHISQR=0.000
       FCOMPAC3=0.00000
       FCOMPAC4=0.00000
         NLRT=0.00
         LRT=0.00
         PEARSON=0.00
         EQUIPEAR=0.00

       FCOMPAC6=0.00000
       FCOMPAC7=0.00000
       FCOMPAC8=0.00000
       DO 221 I=1,MAXDEPT
         KCHISQRI(I)=0.000
         KCHISQRO(I)=0.000
         GEXPECT(I)=0.000
         GVAR(I)=0.000
         GCON(I)=0.000
         MDIAG=MDIAG+GRMEAN(I,I)
         CDIAG=CDIAG+GTOTCON(I,I)
         VDIAG=VDIAG+GRVAR(I,I)
        DO 222 J=1,MAXDEPT

        IF (((QUANTYPE .EQ. 1) .OR. (QUANTYPE .GE. 4))
     C  .AND. (GRVAR(I,J) .GT. 0))  THEN
         COVMAT(I,J)=(GTOTCON(I,J)-GRMEAN(I,J))/
     C                (GRVAR(I,J))**.5
        END IF
        IF ((QUANTYPE .EQ. 2) .AND. (GRMEAN(I,J) .GT. 0)) THEN
         COVMAT(I,J)=(GTOTCON(I,J)-GRMEAN(I,J))/
     C                (GRMEAN(I,J))**.5
        END IF
        IF (QUANTYPE .EQ. 3) THEN
        KSIGN=GTOTCON(I,J)/GRMEAN(I,J)
        IF (KSIGN .GT. 0) THEN
         COVMAT(I,J)=2*GTOTCON(I,J)*LOG(KSIGN)
        ELSE
         COVMAT(I,J)=0
         END IF
        END IF
        IF (SQUAREIT .EQ. 1) THEN
          IF (COVMAT(I,J) .GT. 0) THEN
            KSIGN=1
          ELSE
            KSIGN=-1
          END IF
        COVMAT(I,J)=KSIGN*COVMAT(I,J)**2
        END IF
        IF ((PERGROUP .EQ. 1) .AND. (DEPARTN(I) .GT. 0)) THEN
        COVMAT(I,J)=COVMAT(I,J)/DEPARTN(I)
        END IF
          IF (FIXR .LT. DEPARTN(J)) THEN
          DENOM1=BDEPTN(I)*FIXR
          ELSE
          DENOM1=BDEPTN(I)*DEPARTN(J)
          END IF
          IF (FIXR .LT. DEPARTN(I)) THEN
          DENOM2=BDEPTN(J)*FIXR
          ELSE
          DENOM2=BDEPTN(J)*DEPARTN(I)
          END IF
          BLAUDEN1(I)=BLAUDEN1(I)+DENOM1+DENOM2
          BLAUNUM(I)=BLAUNUM(I)+GTOTCON(I,J)+GTOTCON(J,I)
          BLAUDEN2(I)=BLAUDEN2(I)+(TOTCHOI(I)+TOTCHOI(J))
          BLAUDEN1(J)=BLAUDEN1(J)+DENOM1+DENOM2
          BLAUNUM(J)=BLAUNUM(J)+GTOTCON(I,J)+GTOTCON(J,I)
          BLAUDEN2(J)=BLAUDEN2(I)+(TOTCHOI(I)+TOTCHOI(J))
          COVMAT3(I,J)=GTOTCON(I,J)/DENOM1
          COVMAT4(I,J)=GTOTCON(I,J)/TOTCHOI(I)
          IF (DENOM1 .LE. 0) THEN
          COVMAT3(I,J)=0
          END IF
          IF (ABS(TOTCHOI(I)) .LT. .000001) THEN
          COVMAT4(I,J)=0
          END IF
  222    CONTINUE
         PCOMP3=0.0000
         IF ((DEPARTN(I) .GT. 1) .AND. (TOTCHOI(I) .GT. 0))  THEN
         DENOM1=DEPARTN(I)-1.
         IF (FIXR .LT. DENOM1) THEN
         DENOM1=FIXR
         END IF
         PCOMP3=(GTOTCON(I,I)/(BDEPTN(I)*(DENOM1)))
         COVMAT3(I,I)=PCOMP3
         IF (ABS(BDEPTN(I)*DENOM1) .LT. 0000001) THEN
         COVMAT3(I,I)=0
         END IF
         COVMAT4(I,I)=GTOTCON(I,I)/TOTCHOI(I)
          IF (ABS(TOTCHOI(I)) .LT. .000001) THEN
         COVMAT4(I,I)=0
         END IF
         DCOMPAC8=DCOMPAC8+(TOTCHOI(I))**(SQUAREIT+1.)
          COMPD=DEPARTN(I)-1.
          IF (FIXR .LT. COMPD) THEN
          XDENOM1=BDEPTN(I)*FIXR
          ELSE
          XDENOM1=BDEPTN(I)*COMPD
          END IF
         DCOMPAC9=DCOMPAC9+(XDENOM1)
         NCOMPAC8=NCOMPAC8+(GTOTCON(I,I))**(SQUAREIT+1.)
         END IF

         IF (GRVAR(I,I) .GT. 0) THEN
C         EQUIPEAR=(GTOTCON(I,I)-GRMEAN(I,I))**2/GRVAR(I,I)
         IF ((QUANTYPE .EQ. 1) .OR. (QUANTYPE .GE. 4)) THEN
         COVMAT(I,I)=(GTOTCON(I,I)-GRMEAN(I,I))/GRVAR(I,I)**.5
         END IF
         END IF

         IF ((QUANTYPE .EQ. 2) .AND. (GRMEAN(I,I) .GT. 0)) THEN
         COVMAT(I,I)=(GTOTCON(I,I)-GRMEAN(I,I))/GRMEAN(I,I)**.5
         END IF

         IF (QUANTYPE .EQ. 3) THEN
         KSIGN=GTOTCON(I,I)/GRMEAN(I,I)
         IF (KSIGN .GT. 0) THEN
         COVMAT(I,I)=2*GTOTCON(I,I)*LOG(GTOTCON(I,I)/GRMEAN(I,I))
         END IF
         END IF
         IF (SQUAREIT .EQ. 1) THEN
          IF (COVMAT(I,I) .GT. 0) THEN
            KSIGN=1
          ELSE
            KSIGN=-1
          END IF
         COVMAT(I,I)=KSIGN*COVMAT(I,I)**2
         END IF
         IF (PERGROUP .EQ. 1) THEN
         COVMAT(I,I)=COVMAT(I,I)/(DEPARTN(I)-1.)
         END IF

          DO 2512 J=1,MAXDEPT
          IF (J .NE. I) THEN
          GEXPECT(I)=GEXPECT(I)+GRMEAN(I,J)
          GVAR(I)=GVAR(I)+GRVAR(I,J)
          GCON(I)=GCON(I)+GTOTCON(I,J)
          END IF
02512      CONTINUE
          GCENTRAL(I)=0.000
         IF (GVAR(I) .GT. 0) THEN
         GCENTRAL(I)=(GCON(I)-GEXPECT(I))/(GVAR(I)**.5)
         END IF
        IF (DEPARTN(I) .GT. 1) THEN
         ADD3=0
         ADD4=0
         ADD3A=0
         ADD4A=0
          ADDIN=0
          IF (CHIMEANI(I) .GT. 0) THEN
          ADDIN=ADDIN+1
         ADD3=ADD3+
     C  ((OBSCONI(I)-CHIMEANI(I))/CHIMEANI(I)**.5)**(SQUAREIT + 1.)
         ADD3A=ADD3
          END IF
         IF (CHIMEANO(I) .GT. 0) THEN
          ADDIN=ADDIN+1
          ADD3=ADD3+
     C  ((OBSCONO(I)-CHIMEANO(I))/CHIMEANO(I)**.5)**(SQUAREIT + 1.)
         END IF
C         IF (ADDIN .GT. 0) THEN
C         ADD3=ADD3/ADDIN
C          END IF
        TCHII=CHIMEANI(I)
        IF (TCHII .LT. .0001) THEN
        TCHII=.0001
        END IF
        TCHIO=CHIMEANO(I)
        IF (TCHIO .LT. .0001) THEN
        TCHIO=.0001
        END IF
 
        KSIGN=OBSCONI(I)/TCHII
        KSIGN2=OBSCONO(I)/TCHIO
        IF ((KSIGN .GT. 0) .AND. (KSIGN2 .GT. 0)) THEN
        ADD4=
     C 2*((OBSCONI(I) * LOG(KSIGN))**(SQUAREIT+1.)+
     C    (OBSCONO(I) * LOG(KSIGN2))**(SQUAREIT+1.))
         END IF
        IF (KSIGN .GT. 0) THEN
        NLRT=NLRT+
     C 2*MULTI*(OBSCONI(I) * LOG(KSIGN))
        LRT=LRT+
     C 2*(OBSCONI(I) * LOG(KSIGN))
        ADD4A=
     C 2*((OBSCONI(I) * LOG(KSIGN))**(SQUAREIT+1.))
        END IF
        IF (KSIGN2 .GT. 0) THEN
        LRT=LRT+
     C  2*(OBSCONO(I) * LOG(KSIGN2))
        NLRT=NLRT-
     C  2*MULTI*(OBSCONO(I) * LOG(KSIGN2))
        END IF

        IF (PERGROUP .EQ. 1) THEN
         ADD3=ADD3/(DEPARTN(I)-1.)
         ADD4=ADD4/(DEPARTN(I)-1.)
         ADD3A=ADD3A/(DEPARTN(I)-1.)
         ADD4A=ADD4A/(DEPARTN(I)-1.)
        END IF
         FCOMPAC6=FCOMPAC6+ADD3A
         FCOMPAC7=FCOMPAC7+ADD4A
         FCOMPAC3=FCOMPAC3+ADD3
         FCOMPAC4=FCOMPAC4+ADD4
        KCHISQRI(I)=((OBSCONI(I)-CHIMEANI(I))**2)/CHIMEANI(I) +
     C  KCHISQRI(I)
        KCHISQRO(I)=((OBSCONO(I)-CHIMEANO(I))**2)/CHIMEANO(I) +
     C  KCHISQRO(I)
        KCHISQR=KCHISQR+COVMAT(I,I)*COVMAT(I,I)

        IF ((CHIMEANI(I) .GT. 0) .AND. (CHIVARI(I) .GT. 0)) THEN
        PEARSON=PEARSON+((OBSCONI(I)-CHIMEANI(I))**2)/CHIMEANI(I) 
        EQUIPEAR=EQUIPEAR+((OBSCONI(I)-CHIMEANI(I))**2)/CHIVARI(I)
        END IF

        IF ((CHIMEANO(I) .GT. 0) .AND. (CHIVARO(I) .GT. 0)) THEN
        PEARSON=PEARSON+((OBSCONO(I)-CHIMEANO(I))**2)/CHIMEANO(I) 
        EQUIPEAR=EQUIPEAR+((OBSCONO(I)-CHIMEANO(I))**2)/CHIVARI(I)
c        INTENTIONAL USE OF CHIVARI INSTEAD OF CHIVARO. 
        END IF

        END IF
  221  CONTINUE
       DO 876 I=1,MAXDEPT
       IF (BLAUNUM(I) .GT. 0) THEN
       IF (BLAUDEN1(I) .GT. 0) THEN
       BCENT1(I)=BLAUNUM(I)/BLAUDEN1(I)
       END IF
       IF (BLAUDEN2(I) .GT. 0) THEN
       BCENT2(I)=BLAUNUM(I)/BLAUDEN2(I)
       END IF
       END IF
C       DO 877 J=1,(I-1.)
C       COVMAT(J,I)=COVMAT(I,J)
C       COVMAT2(J,I)=COVMAT2(I,J)
C       COVMAT3(J,I)=COVMAT3(I,J)
C       COVMAT4(J,I)=COVMAT4(I,J)
C00877   CONTINUE
00876   CONTINUE

       FCOMPAC9=NCOMPAC8/DCOMPAC9
       FCOMPAC8=NCOMPAC8/DCOMPAC8
       FCOMPACT=(CDIAG-MDIAG)/VDIAG**.5
       CLOSE(55)
       END IF
   62 FORMAT(I2)
  512 FORMAT(3(A20,1X))
  513 FORMAT(10X,3(A20,1X))
  517 FORMAT(10X,A40)
    7 FORMAT('RESULTING MATRIX OF WITHIN GROUP CONNECTIONS',/,
     C8X,A20,' ORDER')   
   77 FORMAT('MATRIX OF GROUP ASSOCIATIONS',/)
   10 FORMAT(5X,251(I5,1X))
  102 FORMAT(I2,251(I1))
  105 FORMAT(251(I1))
  193 FORMAT(/,A3,4(2X,A25),/)
  194 FORMAT(/,10(2X,A15),/)
  195 FORMAT(/,10(2X,F15.5),/)   
  192 FORMAT(I3,6X,I10,6X,6X,I10,6X,12X,F10.5,6X,6X,F10.5,6X,/)
  191 FORMAT(/,'SIMILARITY BETWEEN THE START AND END GROUPS:   ACTUAL 
     C  POSS  STANDARDIZED',/,45X,I10,I10,F10.5)
    8 FORMAT(5X,251(A5,1X))
  301 FORMAT(I4,1X,251(F5.2,1X))
  302 FORMAT(A4,1X,251(F5.2,1X))
  103 FORMAT(20(F7.3))
    9 FORMAT(/,'THE FINAL COMPACTNESS IS',F10.5)
  101 FORMAT(I2,251(I1))
  251 FORMAT(25(G10.5)) 
 0544 FORMAT(A16,25(G10.5)) 
      RETURN
      END
