 

      SUBROUTINE MEANVAR2 (NUMSUB,KOBS,COUNTS,KMEAN,KVAR)
      INCLUDE 'PARAM.H'
      REAL KMEAN(MAXKLIQ),KVAR(MAXKLIQ),KSUM(MAXKLIQ)
      INTEGER I,J,K,NUMSUB,COUNTS(MAXKLIQ)
      REAL KOBS(MAXKLIQ,MAXKLIQ)

      DO 2 I=1,NUMSUB
      KSUM(I)=0
      KVAR(I)=0

      DO 3 J=1,NUMSUB
       IF (KOBS(I,J) .GT. 0) THEN
       COUNTS(I)=COUNTS(I)+1
       KSUM(I)=KSUM(I)+KOBS(I,J)
       END IF
    3 CONTINUE
     
      IF (KSUM(I) .LE. 0.00000) THEN
      KMEAN(I)=0.0000
      KVAR(I)=0.0000
      ELSE
      KMEAN(I)=KSUM(I)/COUNTS(I)
      DO 4 K=1,COUNTS(I)
      KVAR(I)=KVAR(I)+(KMEAN(I)-KOBS(I,K))**2
    4 CONTINUE
      END IF
    2 CONTINUE
      RETURN
      END
