
      SUBROUTINE OUTCOORD(COORFILE,MAXDEPT,NUMDIM,COORD,WITHID,
     C NSUBID,ANGLE,RADIUS,NEWDEPT,ANCHOR,HIER,FIT,NSIM,PRINTK,ADDEND,
     C ISTRESS,ISTRESS2,ISTRESS3,PDIST,DISTFILE,WARP,GRANGE1,GRANGE2)
      INCLUDE 'PARAM.H'
      INTEGER MAXDEPT,U,Z,NUMDIM,WITHID,NSUBID(MAXKLIQ),TU,
     C NEWDEPT(MAXKLIQ),
     C ANCHOR(MAXKLIQ),DU,NSIM,PRINTK,ADDEND,PDIST,TH,HU,SYMLNK,STATUS,
     C SIXTEEN,ISI,COLOR,SHAPE,SIZE,TYPE

      REAL COORD(MAXKLIQ,2),ANGLE(MAXKLIQ),RADIUS(MAXKLIQ),
     C HIER(MAXKLIQ),FIT(MAXKLIQ),ISTRESS(MAXKLIQ),ISTRESS2(MAXKLIQ),
     C ISTRESS3(MAXKLIQ),DIFFANG,PI,RPDIST,WARP(MAXKLIQ),
     C GRANGE1(MAXKLIQ),GRANGE2(MAXKLIQ)
 
        REAL BLAUC(MAXKLIQ,MAXKLIQ),ZCOMPMAT(MAXKLIQ,MAXKLIQ)
        
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),
     C NEWMAT(MAXKLIQ,MAXKLIQ)


      COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF
 

      CHARACTER*12 COORFILE,SFILE,DISTFILE,LINKFILE,NDFILE
      CHARACTER*6 INFILE
      ISI=0
      IF (COORFILE(9:9) .EQ. 'i') THEN
      ISI=1
      DISTFILE='compgrp.iang'
      ELSE
      DISTFILE='compgrp.gang'
      END IF
      LINKFILE='inlist' // COORFILE(7:12)
      SIXTEEN=16
      SIXTEEN=UNLINK(LINKFILE)

      STATUS=SYMLNK(COORFILE,LINKFILE)

      INFILE=COORFILE(1:6)
      NDFILE=INFILE  // '.vna'
       PI=3.1415926
       OPEN(58,file=NDFILE)
      OPEN(56,file=COORFILE)
      SFILE=COORFILE(1:11) // 's'
      OPEN(57,file=SFILE)
      IF (PDIST .EQ. 1) THEN
      OPEN(23,file=DISTFILE)
      END IF

       IF (ADDEND .EQ. 1) THEN
        CALL MOVEEND(56)
        CALL MOVEEND(57)
        IF (PDIST .EQ. 1) THEN
        CALL MOVEEND(23)
        END IF
        END IF
       TYPE=1
C       WRITE(58,777) '*Node data'
C       WRITE(58,777) 'id type group'
C       DO 4545 TU=1,MAXDEPT
C       WRITE(58,1212) '"',NSUBID(TU),'" ',TYPE,NEWDEPT(TU)
C04545   CONTINUE
C
C       WRITE(58,220) '*Node properties'
C       WRITE(58,20) 'ID x y color shape size shortlabel'
       DO 28283 TU=1,MAXDEPT
        IF (WITHID .EQ. 1) THEN
        U=NSUBID(TU)
        ELSE
        U=TU
        END IF
      IF (ISI .EQ. 0) THEN
      WRITE(56,445) NEWDEPT(TU),U,ANCHOR(TU),ANGLE(TU),RADIUS(TU),
     C HIER(TU), (COORD(TU,Z) , Z=1,NUMDIM) ,WARP(TU), GRANGE1(TU),
     C GRANGE2(TU)
      WRITE(57,251) NEWDEPT(TU),U,FIT(TU),NSIM,PRINTK,ISTRESS(TU),
     C ISTRESS2(TU),ISTRESS3(TU)
     
      END IF

      IF (ISI .EQ. 1) THEN
      WRITE(56,445) NEWDEPT(TU),U,ANCHOR(TU),ANGLE(TU),RADIUS(TU),
     C HIER(TU), (COORD(TU,Z) , Z=1,NUMDIM) 
C      WRITE(58,21) '"',U,'"',(COORD(TU,Z) , Z=1,NUMDIM),COLOR,SHAPE,
C     C SIZE,U
   
      END IF

       IF (PDIST .EQ. 1) THEN
        DO 28282 TH=1,TU
        IF ((ANCHOR(TH) .EQ. 0) .AND. (ANCHOR(TU) .EQ. 0) .AND.
     C  (TH .NE. TU)) THEN
        IF (WITHID .EQ. 1) THEN
        HU=NSUBID(TH)
        ELSE
        HU=TH
        END IF
        DIFFANG=ABS(ANGLE(TU)-ANGLE(TH))
        IF (DIFFANG .GT. PI) THEN
        DIFFANG=2.0*PI-DIFFANG
        END IF
        RPDIST=SQRT((COORD(TU,1)-COORD(TH,1))**2+
     C            (COORD(TU,2)-COORD(TH,2))**2)

        WRITE(23,443) INFILE,U,NEWDEPT(TU),HU,NEWDEPT(TH),
     C  ANGLE(TU),ANGLE(TH),DIFFANG,MAXDEPT,RPDIST
        END IF
28282    CONTINUE
        END IF
28283  CONTINUE
      CLOSE(57)
      CLOSE(56)
      CLOSE(58)
      IF (PDIST .EQ. 1) THEN
      CLOSE(23)
      END IF
      
      RETURN
      
00777  FORMAT(A)
01212  FORMAT(A1,I5,A2,I5,1X,I5)

00020  FORMAT(A33)
00220  FORMAT(A16)

00021  FORMAT(A1,I5,A1,2F10.5,4(I5,1X))
C      WRITE(57,XX) '"',U,'"',(COORD(TU,Z) , Z=1,NUMDIM),COLOR,SHAPE,

00445  FORMAT(I5,1X,2(I10,1X),8(F20.10,1X))
00443  FORMAT(A6,4I10,3F10.5,I10,F10.5) 
00251  FORMAT(I5,1X,I10,1X,F10.5,1X,2(I10,1X),3(F10.5,1X))
      END
