
      SUBROUTINE PERXPER(COVMAT,NUMTEACH,NEWDEPT,EXT,NSUBID,LGROUP,
     C LMAXDEPT,MAXDEPT)
      INCLUDE 'PARAM.H'
      REAL COVMAT(MAXGR,MAXGR)
      INTEGER NUMTEACH,NEWDEPT(MAXKLIQ),I,J,NSUBID(MAXKLIQ),
     C LGROUP(MAXKLIQ),LMAXDEPT,MAXDEPT
      CHARACTER EXT*4,OUTFILE*12

      OUTFILE='grpxgrp.' // EXT
      OPEN(8,file=OUTFILE)
      DO 4 I=1,LMAXDEPT
      DO 5 J=1,I
      WRITE(8,100) LGROUP(I),LGROUP(J),COVMAT(LGROUP(I),LGROUP(J))
00005  CONTINUE
00004   CONTINUE
      CLOSE(8)

      OUTFILE='perxper.' // EXT
      OPEN(8,file=OUTFILE)

      DO 2 I=2,NUMTEACH
      DO 3 J=1,(I-1.)
      WRITE(8,100) NSUBID(I),NSUBID(J),COVMAT(NEWDEPT(I),NEWDEPT(J))
00003  CONTINUE
00002   CONTINUE
      CLOSE(8)
       RETURN
00100   FORMAT(2(I5,1X),F10.5)
       END
