      SUBROUTINE PISIM(MAXSIZE,PERGROUP,NUMPEOPL,TCHOICE,MAXFREQ,
     C OUTMAT,DEPART,QSEED,USEMARG,INDEPT,OUTDEPT,BYDENSE,SIMRAND,
     C PSIZE,QSIZE,BASEG,PKPG,QKPG,BYLAMN)
      INCLUDE 'PARAM.H'


      INTEGER D,I,J,DEPART(MAXKLIQ),D2,D3,OUTMAT(MAXKLIQ,MAXKLIQ),
     C        SIMRAND,THISD,
     C        D4,D5,COL,NUMGROUP,PERGROUP,NUMPEOPL,ONELESS,ACHOICE,
     C        MAXFREQ,MV,FREQS(MAXKLIQ),USEMARG,TID,NR,AC,DIDG,DIDNG,
     C       OPENS,HAVEMEM,FILLG,FILLNG,COUNTING,COUNTNNG,FG,NFG,
     C  COUNTG(MAXKLIQ),COUNTNON(MAXKLIQ),ING,GOTTEM,TG,IR(1),BYDENSE,
     C SORTEM(MAXKLIQ),U,TCHOICE,DIDEM,RANGEG,BASEG,RANGEC,MINCHOI,
     C ROOT,BYLAMN,MAXSIZE,OPENSX,COUNTK
       INTEGER*4
     C  MEMBERS(100,MAXGR),NONMEM(100,MAXKLIQ)
       DOUBLE PRECISION QSEED
       REAL DEVIATE(1),INDEPT(MAXKLIQ),OUTDEPT(MAXKLIQ),EXTRA,PORTION,
     C KPOSS,LOW,HIGH,PSIZE,QSIZE,PKPG,QKPG,KPOSS2,
     C ALPHA,BETA,GAMMA,DELTA,PROPIN,PROPOUT,R(1),LE

C       QSEED=5163.D0


       NR=1
       LOW=0
       HIGH=1
       DO 22 I=1,NUMPEOPL
       DO 33 J=1,NUMPEOPL
       OUTMAT(I,J)=0
00033   CONTINUE
00022    CONTINUE




      DO 84 MV=1,MAXFREQ
       FREQS(MV)=MV
   84 CONTINUE

       ONE=1

       IF ((PSIZE .GT. 0) .AND. (QSIZE .GT. 0)) THEN
       D=0
       DIDEM=0

       I=0
       DO WHILE (DIDEM .EQ. 0)
       I=I+1
       R(1)=GENBET(PSIZE,QSIZE)
       COUNTG(I)=0
       COUNTG(I)=INT(R(1)*MAXSIZE+ BASEG + .9999)
       IF (COUNTG(I) .GT. (NUMPEOPL-(D+BASEG))) THEN
       DIDEM=1
       COUNTG(I)=NUMPEOPL-D
       END IF

        DO 44 J=1,COUNTG(I) 
        D=D+1
        DEPART(D)=I
00044    CONTINUE

       END DO
       NUMGROUP=I

       ELSE

       D=0
      DO 2 I=1,NUMGROUP
       DO 3 J=1,PERGROUP
       D=D+1
       DEPART(D)=I
    3 CONTINUE
    2 CONTINUE

      CALL SRESORTO(DEPART,NUMPEOPL,QSEED)
        END IF
C       ON RAND COUNT N
 
       DO 333 J=1,NUMGROUP
       COUNTG(J)=0
       COUNTNON(J)=0
00333   CONTINUE

      DO 77 I=1,NUMPEOPL
      DO 88 J=1,(NUMGROUP-1.)
      TG=J
      IF (TG .GE. DEPART(I)) THEN 
       TG=TG+1
      END IF
      COUNTNON(TG)=COUNTNON(TG)+1.
      NONMEM(TG,COUNTNON(TG))=I
00088  CONTINUE
00077   CONTINUE

      DO 277 I=1,NUMPEOPL
      COUNTG(DEPART(I))=COUNTG(DEPART(I))+1.
      MEMBERS(DEPART(I),COUNTG(DEPART(I)))=I      
00277  CONTINUE

       ROOT=1
      DO 6 D4=1,NUMPEOPL
       IF ((PKPG .GT. 0) .AND. (QKPG .GT. 0)) THEN
       R(1)= GENBET(PKPG,QKPG)
       ACHOICE=INT(R(1)*PERGROUP+TCHOICE+.99999)
       ELSE
       ACHOICE=TCHOICE
        END IF

      THISD=DEPART(D4)


 
      IF (BYDENSE .EQ. 0) THEN
       KPOSS=ACHOICE
       KPOSS2=ACHOICE
      ELSE
       KPOSS=COUNTG(THISD)-1.
       KPOSS2=NUMPEOPL-COUNTG(THISD)
      END IF
       IF (BYLAMN .EQ. 1) THEN
       CALL CONVLAMN(INDEPT(THISD),(COUNTG(THISD)-1),
     C ACHOICE,NUMPEOPL,
     C ALPHA,BETA,GAMMA,DELTA,ROOT,LE)
       PROPIN=DELTA/KPOSS
       PROPOUT=BETA/KPOSS2


       ELSE
       PROPIN=INDEPT(THISD)
       PROPOUT=OUTDEPT(THISD)
       END IF

       IF (SIMRAND .EQ. 0) THEN
      PORTION=KPOSS*INDEPT(THISD)
      FG=INT(PORTION)
      EXTRA=PORTION-FG
      DEVIATE(1)=GENUNF(LOW,HIGH)
C       CALL GGUBS(QSEED,NR,DEVIATE)
      IF (DEVIATE(1) .LE. EXTRA) THEN
       THEN FG=FG+1
      END IF
      IF (FG .GT. (COUNTG(THISD) -1.)) THEN
      FG=COUNTG(THISD)-1.
      END IF
      NFG=ACHOICE-FG
      DO 8872 U=1,NUMPEOPL
      SORTEM(U)=IGNUIN(1,NUMPEOPL)
08872  CONTINUE
C      CALL GGUD(QSEED,NUMPEOPL,NUMPEOPL,SORTEM)
      COUNTK=1
      COUNTING=0
      COUNTNNG=0
      FILLG=0
      FILLNG=0
      DO WHILE ((COUNTK .LE. NUMPEOPL) .AND.
     C ((FILLG .EQ. 0) .OR. (FILLNG .EQ. 0)))
      IF ((FILLG .EQ. 0) .AND. (DEPART(SORTEM(COUNTK)) .EQ. THISD))
     C   THEN
       IF (COUNTING .LT. FG) THEN
        CALL SRESORTO(FREQS,MAXFREQ,QSEED)
        OUTMAT(D4,SORTEM(COUNTK))=FREQS(1)
        COUNTING=COUNTING+1
       ELSE
       FILLG=1
       END IF
      END IF
      IF ((DEPART(SORTEM(COUNTK)) .NE. THISD) .AND. 
     C (FILLNG .EQ. 0)) THEN
        IF (COUNTNNG .LT. NFG) THEN 
          CALL SRESORTO(FREQS,MAXFREQ,QSEED)
          OUTMAT(D4,SORTEM(COUNTK))=FREQS(1)
          COUNTNNG=COUNTNNG+1
        ELSE
          FILLNG=1
        END IF

      END IF

      COUNTK=COUNTK+1
      END DO

      ELSE
C       SIMRAND=1

      IF (BYDENSE .EQ. 0) THEN      
      OUTMAT(D4,D4)=99
      DIDG=1
      DIDNG=0
      IF (D4 .GT. 1) THEN
       OUTMAT((D4-1),(D4-1))=0
      END IF
      DO 99 AC=1,ACHOICE
      DEVIATE(1)=GENUNF(LOW,HIGH)
C       CALL GGUBS(QSEED,NR,DEVIATE)
      OPENS=COUNTG(THISD)-DIDG
      OPENSX=COUNTNON(THISD)-DIDNG
      IF ((OPENS .GT. 0) .AND. ((DEVIATE(1) .LE. PROPIN) .OR.
     C (OPENSX .LT. 1))) THEN
      ING=1
      IR(1)=IGNUIN(1,OPENS)
C      CALL GGUD(QSEED,OPENS,NR,IR)
      ELSE
      ING=0
      IR(1)=IGNUIN(1,OPENSX)
C      CALL GGUD(QSEED,(COUNTNON(THISD)-DIDNG),NR,IR)
      END IF

      GOTTEM=0
      DO WHILE (GOTTEM .EQ. 0)
       IF (ING .EQ. 1) THEN
      HAVEMEM=MEMBERS(THISD,IR(1))
       ELSE
        HAVEMEM=NONMEM(THISD,IR(1))
       END IF
        IF (OUTMAT(D4,HAVEMEM) .GT. 0) THEN
         IR(1)=IR(1)+1
        ELSE
        GOTTEM=1
        CALL SRESORTO(FREQS,MAXFREQ,QSEED)
        OUTMAT(D4,HAVEMEM)=FREQS(1)
        IF (ING .EQ. 1) THEN
        DIDG=DIDG+1
        ELSE 
        DIDNG=DIDNG+1
        END IF
        END IF
       END DO
00099   CONTINUE

      ELSE
C      BYDENSE

      DO 10 D3=1,NUMPEOPL
      IF (D4 .NE. D3) THEN
       IF (DEPART(D3) .EQ. DEPART(D4)) THEN
        PI=PROPIN
       ELSE
        PI=PROPOUT
       END IF
       DEVIATE(1)=GENUNF(LOW,HIGH)
C       CALL GGUBS(QSEED,NR,DEVIATE)
       IF (DEVIATE(1) .LE. PI) THEN 
       OUTMAT(D3,D4)=1
       ELSE 
       OUTMAT(D3,D4)=0
       END IF
      END IF
   10 CONTINUE
      END IF
C      BYDENSE
       END IF
C      SIMRAND

    6 CONTINUE
      OUTMAT(NUMPEOPL,NUMPEOPL)=0
      RETURN
      END
