      SUBROUTINE PRINTG(MAXDEPT,DEPARTN,NUMTEACH,
     C TCHOICE,NEWDEPT,MEANWT,VARWT,LABEL,TITLES,PRINTT,KEEPLIST,
     C FINAL,FSYMMAT,PRINTO,NSUBID,PHASE,IEXPECT,ISTD,ICON,STRUCTEQ,
     C NOWCLOSE,PERGROUP,QUANTYPE,SQUAREIT,OLDR,INFILE,
     C HOWWIDE,BETWMULT,QUICKEND,NSIM,BOUNDVAL,BLABOUND,HIWT,
     C  IGRATIO,NUMDIM,
     C CENTER,DANCHOR,DANCHOR2,MOVE2,ZSYMMAT,
     C STARTINC,BYINC,MAXINC,KEXP,NORMAL,MINVALG,
     C CENTERI,DANCHORI,DANCH2I,MOVE2I,ZSYMMATI,
     C STARTINI,BYINCI,MAXINCI,KEXPI,NORMALI,MINVALI,
     C RINCREM,MEASURE,EXTREME,DRADIUS,DRADIUSI,
     C BYANGLE,BYSCALE,BYANGLEI,BYSCALEI,MINPICT,
     C PCTCENG1,PCTCENG2,PCTCENI1,PCTCENI2,ROWWT,COLWT,SIMO,PRINTK,
     C BICOORD,HYPERG,LAST)
      INCLUDE 'PARAM.H'

C     C CENTER,IGRATIO,DANCHOR2,MOVE2,DANCHOR,ZSYMMAT,MAXINC,
C     C BYINC,STARTINC,NUMDIM,RINCREM,MEASURE,EXTREME,HYPERG,DRADIUS,
C     C KEXP,NORMAL,NORMALI,MINVALI,MINVALG)
 
       CHARACTER LABEL(MAXKLIQ)*9,TITLES(3)*20,PHASE*20,INFILE*16,
     C LINKFILE*16,NDFILE*16,IFILE*16,NFILE*16,ILABEL(MAXKLIQ)*20,
     C TEMPLAB*20,COLORS(300)*10
       CHARACTER*12 UCFILE,COORFILE,DISTFILE,PSTFILE,ODDSRFILE
       CHARACTER*8 CTACKON,VLABEL
       CHARACTER LABELS(300)*2

       INTEGER*2 ITACKON,SJ
       EQUIVALENCE (ITACKON,CTACKON(7:8))
       LOGICAL UPPER
      REAL MEANWT(MAXKLIQ),VARWT(MAXKLIQ),IEXPECT(MAXKLIQ),
     C ISTD(MAXKLIQ),ICON(MAXKLIQ),STOTCON,AMEAN,AVAR,MDIAG,VDIAG,
     C CDIAG,HIWT,WARP,TWARP,GWARP(MAXKLIQ),FCOMPACT,TBOUND,
     C HUBSIM,STDHS,OUTOF,ZABS,PCON,TWARPA,TWARPB,TWARPC,TWARPD,
     C CHNGSIM,CHNGSTD,NOWCLOSE(MAXKLIQ),VP,FIXR,OLDR,NOB,TWEIGHT,
     C GRANGE1(MAXKLIQ),ODDSR,XTNUM,XTMAX,CPL,CPLRT,
     C FCOMPAC8,FCOMPAC9,BLABOUND,BOUNDVAL,DRADIUS,DRADIUSI,
     C GRANGE2(MAXKLIQ),RNUMTCH,WODDSR,WODDSR2,
     C PVAL,PVAL2,PVAL3,ISTRESS2(MAXKLIQ),ISTRESS3(MAXKLIQ),
     C BETWMULT,ALNORM,PREDACC,PREDACC2,BCHNGSIM,BCHNGCON,
     C BCHNGSTD,PREDL,TOTCENT,ROWWT,COLWT,BCENT1(MAXKLIQ),
     C BCENT2(MAXKLIQ),XR1,LAMNDA(MAXKLIQ),TOTLAMND,RCHI,
     C NFIXR,TAI,TAO,TBI,TBO,GLAMNDA,LGLAMNDA,
     C RZERO,KEXP,XLAMNDA,GARBAGE,RANGEEIG(2),TLAMNDA,
     C PCTCENG1,PCTCENG2,PCTCENI1,PCTCENI2,
     C SAMPMEAN,SAMPSD,CSMEAN,CSSD,ZVAL,CZVAL,CPVAL,SPVAL,
     C SAMPMEA2,SAMPSD2,CSMEAN2,CSSD2,ZVAL2,CZVAL2,CPVAL2,
     C SPVAL2,ODDSA,ODDSB,ODDSC,ODDSD,WTHETA,WGLAMNDA,
     C TTAIE,TTAOE,TTBIE,TTBOE,TTAIO,TTAOO,TTBIO,TTBOO,
     C MINZ,MAX9,LTAO,LTBO,LTAI,LTBI,TTL,
     C QMAXX,QMAXY,QMINX,QMINY,MEANRAD,TOTRAD,LONGDIM,LDIMY,
     C LDIMX,MAXRAD(MAXKLIQ),
     C DMAXX(MAXKLIQ),DMINX(MAXKLIQ),DMAXY(MAXKLIQ),DMINY(MAXKLIQ)
      INTEGER NO

      
      INTEGER
     C CENTERI,DANCHORI,DANCH2I,MOVE2I,ZSYMMATI,SIMO,PRINTK,TFIXR,
     C SORTFLAG,ROOT,SIXTEEN,PI,NUMG,FRIENDS,COLOR,TYPE,SHAPE,SIZE,
     C STARTINI,BYINCI,MAXINCI,TF1,BYANGLE,BYSCALE,BYANGLEI,BYSCALEI,
     C TG1,T3,LB,BH,AOBSCONI(MAXKLIQ),AOBSCONO(MAXKLIQ),LAST,NUMDIM,
     C BOBSCONI(MAXKLIQ),BOBSCONO(MAXKLIQ),WRITSMAC,STATUS,SYMLNK,Z,
     C IXC,IYC,ONE,ZERO,TCOLOR,TLSIZE,WANTGR,LTYPE,NUMPT,
     C WANTCIRC,EXTRAL,BETWEEN,WITHIN,TEMPID,GOTLAB,CHECKI,QNET,
     C XNET1(MAXKLIQ),XNET2(MAXKLIQ),XNET3(MAXKLIQ),
     C TNET1,TNET2,TNET3

      REAL KEXPI,RACTG,RPRINTK,RNSIM,ACMEANI(MAXKLIQ),ACMEANO(MAXKLIQ),
     C BCMEANI(MAXKLIQ),BCMEANO(MAXKLIQ),TRUEDEPT(MAXKLIQ)
C Changed TRUEDEPT to real to go with SPSORT(slatec) RTC

      INTEGER MAXDEPT,DEPARTN(MAXKLIQ),NSIM,COMPARE,KPLACE(MAXKLIQ),
     C NUMTEACH,RCHOICE(MAXKLIQ),NEWDEPT(MAXKLIQ),GORDER(MAXKLIQ),
     C GROUP1,GROUP2,DMEMBERS(MAXKLIQ),THISPER,KTEMPS,I,J,STRUCTEQ,
     C KEEPLIST(MAXKLIQ),LMAXDEPT,LGROUP(MAXKLIQ),KORDER(MAXKLIQ),
     C K,LENGTH,NO2,G2,G3,NEWORDER(MAXKLIQ),PRINTT,FINAL,FSYMMAT,
     C PRINTO(100),SAMEG,I2,OBSCONO(MAXKLIQ),OBSCONI(MAXKLIQ),
     C TCHOICE(MAXKLIQ),NSUBID(MAXKLIQ),SAFFIL(MAXKLIQ),
     C SMAT(MAXKLIQ,MAXKLIQ),GENID(MAXKLIQ),REVID(MAXKLIQ),
     C INUM,MAXDEPTN,MAXCH,NDENOM,HOWWIDE,GSMAT(MAXKLIQ,MAXKLIQ),
     C GAFFIL(MAXKLIQ),HAVELAB(MAXKLIQ),KZERO,
     C IER,DDF,IVDF,G1,BOZO,PERGROUP,QUANTYPE,SQUAREIT,ACTG,U,
     C FLAGR,SLOTTD(MAXKLIQ),MEDDEPT,TD,AG1,AG2,AG3,
     C NOWWIDE,XTCOUNT,TOTCOUNT,MADECHOI,QUICKEND,OLDORD(MAXKLIQ),
     C ANCHOR(MAXKLIQ),TANCHOR(MAXKLIQ),ZSYMMAT,MAXINC,BYINC,
     C WITHID,DANCHOR,KENO,REVERSE,MAXK,CENTER,IANCHOR(MAXKLIQ),
     C DANCHOR2,MOVE2,RINCREM,MEASURE,EXTREME,STARTINC,IKPLACE(MAXKLIQ),
     C HYPERG,NORMAL,N3,N2,NORMALI,STRTTYPE,K2,SAMEG1,K1

       REAL ALLCON,CHNGCON,PC,FCOMPAC2,AVECENT(MAXKLIQ),
     C GCOORD(MAXKLIQ,2),RINUM,
     C ICOORD(MAXKLIQ,2),TEMPMAT(MAXGR,MAXGR),TICOORD(MAXKLIQ,2),
     C IANGLE(MAXKLIQ),TIANGLE(MAXKLIQ),IRADIUS(MAXKLIQ),
     C TIRADIUS(MAXKLIQ),GANGLE(MAXKLIQ),GRADIUS(MAXKLIQ),TMEANVAL,
     C IMEANVAL,GMEANVAL,NRATIO,ZICOORD(MAXKLIQ,2),FITG(MAXKLIQ),
     C ZIRADIUS(MAXKLIQ),MINVALI,MINVALG,MINPICT,FITI(MAXKLIQ),
     C BICOORD(MAXKLIQ,2),RMED,RTOTCENT,RMADECH,TFITI(MAXKLIQ),
     C XBIE,XAIE,XBOE,XAOE,
     C TBIE,TAIE,TBOE,TAOE,NA1,NA2,NA3,NA4,NA5,
     C INA1(MAXKLIQ),INA2(MAXKLIQ),INA3(MAXKLIQ),
     C INA4(MAXKLIQ),INA5(MAXKLIQ)

       REAL KSIGN,KCHISQR,ACHISQRI(MAXKLIQ),ACHISQRO(MAXKLIQ),
     C BCHISQRI(MAXKLIQ),BCHISQRO(MAXKLIQ),BCENTRAL(MAXKLIQ),
     C BCENTRA2(MAXKLIQ),
     C TOTCHII,TOTCHIO,LCHISQR(MAXKLIQ),GCENTRAL(MAXKLIQ),HUBM1,HUBM2,
     C HUBSTD1,HUBSTD2,TSS,WSS,VSS,VDF,VMS,VF,KCOMPACT,
     C GROUPMAT(MAXKLIQ,MAXKLIQ),IHIER(MAXKLIQ),GHIER(MAXKLIQ),
     C ISTRESS(MAXKLIQ),
     C ACOMPAC3,ACOMPAC4,BCOMPAC3,BCOMPAC4,THIER(MAXKLIQ),
     C FCOMPAC5,TOTPACT,TCOV,CCOV,ONDIAG,EVALFUN,FCOMPAC6,FCOMPAC7,
     C TCOV2,TOTPACT2,ONDIAG2,ONDIAG3,TOTPACT3,ADDPACT,ONDIAG4,
     C TOTPACT4,APEARSON,BPEARSON,AEQUPEAR,BEQUPEAR,ALRT,BLRT,
     C XPC,MEDIATE,GMAXVAL,IMAXVAL,IGRATIO,BOUND,ANLRT,BNLRT,
     C QA,QB,QC,PLRT,PL,TMAX,TNUM,LE,
     C PDELTA,PBETA,PGAMMA,PALPHA

       DOUBLE PRECISION STRESSB,STRESSA,STRESSC,STRESSD,
     C STRESS2B,STRESS2A,STRESS2C,STRESS2D,
     C STRESS3B,STRESS3A,STRESS3C,STRESS3D


      REAL COVMAT(MAXGR,MAXGR),
     C COVMAT2(MAXGR,MAXGR),
     C COVMAT3(MAXGR,MAXGR),
     C COVMAT4(MAXGR,MAXGR)

       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),
     C NEWMAT(MAXKLIQ,MAXKLIQ),REVMAT(MAXKLIQ,MAXKLIQ)

       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ),
     C ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF
       DATA KCOMPACT/0.0/,TWARPB/0.0/,FITG/MAXKLIQ*0.0/
       DATA ISTRESS/MAXKLIQ*0.0/,ISTRESS2/MAXKLIQ*0.0/
       DATA ISTRESS3/MAXKLIQ*0.0/
C NEXT SIX LINES TO ADDRESS UNITIALIZATION NEAR LINE 1853
       DATA STRESSA/0.0/,STRESSB/0.0/,STRESSC/0.0/,STRESSD/0.0/
       DATA STRESS2A/0.0/,STRESS2B/0.0/,STRESS2C/0.0/,STRESS2D/0.0/
       DATA STRESS3A/0.0/,STRESS3B/0.0/,STRESS3C/0.0/,STRESS3D/0.0/
       DATA SAMPMEA2/0.0/,SAMPSD2/0.0/,CSMEAN2/0.0/,CSSD2/0.0/
       DATA ZVAL2/0.0/,CZVAL2/0.0/,CPVAL2/0.0/,SPVAL2/0.0/
       DATA PREDACC2/0.0/,TWARPA/0.0/,TWARPC/0.0/,TWARPD/0.0/
       DO 11 I=1,MAXKLIQ
        DO 11 J=1,2
          ZICOORD(I,J) = 0.0
11     CONTINUE

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT



       IF (MAXDEPT .LT. MAXGR) THEN
       DO 27 I=1,MAXDEPT
        LGROUP(I)=I
        KPLACE(I)=I
00027    CONTINUE

      TF1=MAXKLIQ
       RZERO=0.000000000
      WRITE(33,512)
      WRITE(33,512) 'Summary: ', PHASE
      WRITE(33,512)
      WRITE(33,513) 'TITLE1','Title2','Title3'
      WRITE(33,513) (TITLES(T3) , T3=1,3)
      WRITE(33,512)

C      CALL REVERSO(NUMTEACH,REVMAT,MEANWT)
C      CALL ARCHOICE(NUMTEACH,REVMAT,RCHOICE,MAXCH,FIXR,FLAGR,
C     C MEANWT,VARWT)
C      CALL MEANVAR(NUMTEACH,PWEIGHTS,RCHOICE,MEANWT,VARWT)

C     QQQQ

      IF (MAXDEPT .GT. 1) THEN
      REVERSE=1
C      SUBROUTINE LOGIT(MAXDEPT,DEPARTN,NEWMAT,NUMTEACH,
C     C RCHOICE,NEWDEPT,MEANWT,VARWT,
C     C FINAL,FSYMMAT,FCOMPACT,KCHISQRI,KCHISQRO,
C     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,FCOMPAC2,
C     C FCOMPAC3,FCOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5,
C     C PERGROUP,QUANTYPE,SQUAREIT,EVALFUN,FCOMPAC6,FCOMPAC7,
C     C FCOMPAC8,FCOMPAC9,FIXR,PEARSON,EQUIPEAR,
C     C LRT,BCENT1,BCENT2,REVERSE,COVMAT,COVMAT2,COVMAT3,COVMAT4,
C     C HYPERG)
      FIXR=1
      CALL LOGIT(MAXDEPT,DEPARTN,REVMAT,NUMTEACH,
     C RCHOICE,NEWDEPT,MEANWT,VARWT,
     C FINAL,FSYMMAT,FCOMPACT,BCHISQRI,BCHISQRO,
     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,FCOMPAC2,
     C BCOMPAC3,BCOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5,
     C PERGROUP,QUANTYPE,SQUAREIT,EVALFUN,FCOMPAC6,FCOMPAC7,
     C FCOMPAC8,FCOMPAC9,FIXR,BPEARSON,BEQUPEAR,
     C BLRT,BCENT1,BCENT2,REVERSE,COVMAT,COVMAT2,COVMAT3,COVMAT4,
     C HYPERG,MAXDEPT,PRINTO(27),INFILE,SIMO,BNLRT,
     C BCMEANI,BCMEANO,BOBSCONI,BOBSCONO)
C      CALL LOGIT(MAXDEPT,DEPARTN,NEWMAT,NUMTEACH,
C     C RCHOICE,NEWDEPT,MEANWT,VARWT,
C     C FINAL,FSYMMAT,FCOMPACT,ACHISQRI,ACHISQRO,
C     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,FCOMPAC2,
C     C ACOMPAC3,ACOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5,
C     C PERGROUP,QUANTYPE,SQUAREIT,EVALFUN,FCOMPAC6,FCOMPAC7,
C     C FCOMPAC8,FCOMPAC9,FIXR,APEARSON,AEQUPEAR,
C     C ALRT,BCENT1,BCENT2,REVERSE,HYPERG)

      FIXR=OLDR
      CALL ARCHOICE(NUMTEACH,NEWMAT,RCHOICE,MAXCH,FIXR,FLAGR,
     C MEANWT,VARWT)
C      CALL MEANVAR(NUMTEACH,PWEIGHTS,RCHOICE,MEANWT,VARWT)
       INUM=NUMTEACH
       MADECHOI=NUMTEACH
      DO 983 I=1,NUMTEACH
       IF (DEPARTN(NEWDEPT(I)) .EQ. 1 ) THEN
        INUM=INUM-1.
       END IF
       IF (RCHOICE(I) .LE. 0) THEN
       MADECHOI=MADECHOI-1.
       END IF
00983  CONTINUE

      IF (FLAGR .NE. 1) THEN
       NFIXR=FIXR
       FIXR=OLDR
      END IF
      REVERSE=0
      CALL LOGIT(MAXDEPT,DEPARTN,NEWMAT,NUMTEACH,
     C RCHOICE,NEWDEPT,MEANWT,VARWT,
     C FINAL,FSYMMAT,FCOMPACT,ACHISQRI,ACHISQRO,
     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,FCOMPAC2,
     C ACOMPAC3,ACOMPAC4,ICON,IEXPECT,ISTD,FCOMPAC5,
     C PERGROUP,QUANTYPE,SQUAREIT,EVALFUN,FCOMPAC6,FCOMPAC7,
     C FCOMPAC8,FCOMPAC9,FIXR,APEARSON,AEQUPEAR,
     C ALRT,BCENT1,BCENT2,REVERSE,COVMAT,COVMAT2,COVMAT3,COVMAT4,
     C HYPERG,MAXDEPT,PRINTO(27),INFILE,SIMO,ANLRT,
     C ACMEANI,ACMEANO,AOBSCONI,AOBSCONO)

      IF (STRUCTEQ .EQ. 1) THEN 

C      SUBROUTINE SLOGIT(MAXDEPT,DEPARTN,ALLGROUP,NEWMAT,NUMTEACH,
C      C RCHOICE,NEWDEPT,
C     C FINAL,FSYMMAT,COVMAT,FCOMPACT,KCHISQRI,KCHISQRO,
C     C KCHISQR,MDIAG,VDIAG,GCENTRAL,CDIAG,TSS,WBSS,GROUPMAT)

      CALL SLOGIT(MAXDEPT,DEPARTN,NUMTEACH,
     C NEWDEPT,
     C COVMAT,FCOMPACT,
     C TSS,WSS,GROUPMAT,
     C ROWWT,COLWT,MAXDEPT)

C      SUBROUTINE SLOGIT(MAXDEPT,DEPARTN,NUMTEACH,
C     C NEWDEPT,COVMAT,FCOMPACT,TSS,WBSS,GROUPMAT,
C     C ROWWT,COLWT)

       END IF
      IF ((PRINTO(36) .GT. 0) .AND. (MAXDEPT .GT. 1)) THEN
      IF (PRINTO(36) .EQ. 1) THEN

      CALL SORTMAT(COVMAT,MAXDEPT,KPLACE,PRINTO(37),GHIER,MAXDEPT)
      END IF
      IF (PRINTO(36) .EQ. 2) THEN
      CALL SORTMAT(COVMAT2,MAXDEPT,KPLACE,PRINTO(37),GHIER,MAXDEPT)
      END IF
      IF (PRINTO(36) .EQ. 3) THEN
      CALL SORTMAT(COVMAT3,MAXDEPT,KPLACE,PRINTO(37),GHIER,MAXDEPT)
      END IF
      IF (PRINTO(36) .EQ. 4) THEN
      CALL SORTMAT(COVMAT4,MAXDEPT,KPLACE,PRINTO(37),GHIER,MAXDEPT)
      END IF
      CALL FIXMAT(COVMAT,MAXDEPT,KPLACE)
      CALL FIXMAT(COVMAT2,MAXDEPT,KPLACE)
      CALL FIXMAT(COVMAT3,MAXDEPT,KPLACE)
      CALL FIXMAT(COVMAT4,MAXDEPT,KPLACE)
      END IF
       END IF

      DO 65667 J=1,MAXDEPT
      IF (KPLACE(J) .LE. 0.00) THEN 
      KPLACE(J)=MAXDEPT+1
      END IF
65667 CONTINUE

      DO 65678 J=1,MAXDEPT
      GORDER(KPLACE(J))=J
65678 CONTINUE

      TAI=0
      TBO=0
      TBI=0
      TAO=0
      TAIE=0
      TBOE=0
      TBIE=0
      TAOE=0
      SAMEG1=0
      DO 2525 TG1=1,MAXDEPT  
      G1=GORDER(TG1)
      SAMEG1=SAMEG1+(DEPARTN(G1)*(DEPARTN(G1)-1))*MAXCH
      TLAMNDA=AOBSCONI(G1)*BOBSCONO(G1)
      TLAMNDA=TLAMNDA/(BOBSCONI(G1)*AOBSCONO(G1))
      LAMNDA(G1)=.00000001

      IF (ABS(TLAMNDA) .GT. .0001) THEN
      TTL=ABS(TLAMNDA)
C      TTL=TTL
C      IF (TTL .GT. .0001) THEN
      LAMNDA(G1)=LOG(TTL)
      END IF
      TAIE=TAIE+ACMEANI(G1) 
      TAOE=TAOE+ACMEANO(G1) 
      TBIE=TBIE+BCMEANI(G1)  
      TBOE=TBOE+BCMEANO(G1)  
      TAI=TAI+AOBSCONI(G1)
      TBO=TBO+BOBSCONO(G1)
      TBI=TBI+BOBSCONI(G1)
      TAO=TAO+AOBSCONO(G1)
02525  CONTINUE

       K2=0
       DO 6261 TG1=1,NUMTEACH
       K2=K2+RCHOICE(TG1)
06261   CONTINUE

       TNUM=NUMTEACH-50
        XTNUM=TNUM
        IF (NUMTEACH .GT. 80) THEN
        XTNUM=31
        END IF
          
       TMAX=FIXR-12+1
       XTMAX=TMAX
       IF (FIXR .GT. 17) THEN
        XTMAX=7
       END IF  
       
       PL=.790360+(.0051540)*XTNUM+(-.016847)*XTMAX+
     C (-.000027)*XTNUM**2.0+(.002689)*XTMAX**2.0+
     C (-.000424)*XTNUM*XTMAX
C       IF (FIXR .GT. 17) THEN
C       PL=PL-(.002689)*TMAX**2
C       END IF
C       IF (NUMTEACH .GT. 80) THEN
C       PL=PL+(.000027)*TNUM**2
C       END IF

C      PL IS THE PREDICTED ODDS RATIO  MAYBE NOT!
C       PL=2*PL
C      NOW PL IS THE PREDICTED THETA1
       ROOT=1

        K1=NUMTEACH*(NUMTEACH-1)-K2
C       LE=2.718281828**(2*PL)
C       QA=LE - 1
C       QB=-(LE*SAMEG1+LE*K2+K1-SAMEG1)
C       QC=LE*SAMEG1*K2
C       PDELTA=(-QB+SQRT(QB**2-4*QA*QC))/(2*QA)
C       PBETA=K2-PDELTA
C       PGAMMA=SAMEG1-PDELTA
C       PALPHA=K1-PGAMMA
C       IF ((PBETA .LE. 0) .OR. (PALPHA .LE. 0) .OR.
C     C     (PGAMMA .LE. 0)) THEN
C       PDELTA=(-QB-SQRT(QB**2-4*QA*QC))/(2*QA)
C       PBETA=K2-PDELTA
C       PGAMMA=SAMEG1-PDELTA
C       PALPHA=K1-PGAMMA
C       END IF 

C       CALL CONVLAMN(PL,SAMEG1,K2,(NUMTEACH*(NUMTEACH-1)*MAXCH),
C     C PALPHA,PBETA,PGAMMA,PDELTA,ROOT,LE)

C       PLRT=2*(TBO*LOG(TBO/PALPHA)+
C     C TAO*LOG(TAO/PBETA)+
C     C TBI*LOG(TBI/PGAMMA)+
C     C TAI*LOG(TAI/PDELTA))

C       GLAMNDA=TAI*TBO
C       GLAMNDA=GLAMNDA/(TBI*TAO)

       XTOTAL=NUMTEACH*(NUMTEACH-1)
       SAMEG0=XTOTAL-SAMEG1
       XBIE=K1*SAMEG1/XTOTAL
       XAIE=K2*SAMEG1/XTOTAL
       XBOE=K1*SAMEG0/XTOTAL
       XAOE=K2*SAMEG0/XTOTAL
       IF (PRINTO(36) .GT. 0) THEN 
      WRITE(33,4301) 'Subgroups have been reordered according to the'
      WRITE(33,4301) 'following scheme:'
      WRITE(33,4301)
      WRITE(33,4301) 'GROUP'
      WRITE(33,10) 'OLD', (I , I=1,MAXDEPT)
      WRITE(33,10) 'NEW' ,(KPLACE(I) , I=1,MAXDEPT)
      WRITE(33,4301)
      COORFILE=INFILE(1:6) // '.swtch'
   
      OPEN(58,file=COORFILE)
      DO 894 I=1,MAXDEPT
      WRITE(58,251) I,KPLACE(I)
00894  CONTINUE
      CLOSE(58)

C JJJJJ
      DO 12112 I=1,NUMTEACH
      NEWDEPT(I)=KPLACE(NEWDEPT(I))
12112  CONTINUE
        CALL ASSIGN2(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN)

       MAXDEPTN=1
       NO=1
      DO 82 I=1,MAXDEPT
         IF ((DEPARTN(I) .GT. 1) .AND. (DEPARTN(I) .LE. MAXGR)) THEN
      CALL ONEPIECE(I,DEPARTN(I),TEMPMAT,OLDORD,TF1)
      COMPARE=1
      CALL SORTMAT(TEMPMAT,DEPARTN(I),IKPLACE,COMPARE,THIER,TF1)
      DO 6567 J=1,DEPARTN(I)
      KORDER(IKPLACE(J))=OLDORD(J)
      IHIER(OLDORD(J))=THIER(J)
06567  CONTINUE
      END IF
        DO 83 J=1,DEPARTN(I)

         IF ((DEPARTN(I) .GT. 1) .AND. (DEPARTN(I) .LE. MAXGR)) THEN
        ALLGROUP(I,J)=KORDER(J)
      END IF
        NEWORDER(NO)=ALLGROUP(I,J)
        NO=NO+1
C       WRITE(555,251) I,J,NEWORDER(NO)
   83 CONTINUE
       IF (DEPARTN(I) .GT. MAXDEPTN) THEN
        MAXDEPTN=DEPARTN(I)
       END IF
   82 CONTINUE
C     LEFT OFF HERE ZXZXZX
       ELSE
       NO=1
       DO 222 J=1,MAXDEPT
       DO 2221 K=1,DEPARTN(J)
        NEWORDER(NO)=ALLGROUP(J,K)
        NO=NO+1
02221    CONTINUE
00222     CONTINUE
       END IF
      IF (PRINTO(11) .EQ. 1) THEN
      CALL BSPAN(DIFF,NUMTEACH,MAXDEPT,BOUNDVAL,KPLACE,NEWDEPT,
     C TITLES,'COMPACTNESS   ',
     C 'OTHER T     ',DEPARTN,NSUBID,INFILE,PRINTO(12),'C',PRINTO(27),
     C NSIM,PRINTK)
      IF (PRINTO(26) .EQ. 1) THEN
      TBOUND=BLABOUND*MAXWT
      CALL BSPAN(BLAUC,NUMTEACH,MAXDEPT,BLABOUND,KPLACE,NEWDEPT,
     C TITLES,'DENSITY      ',
     C 'OTHER T     ',DEPARTN,NSUBID,INFILE,PRINTO(12),'D',PRINTO(27),
     C NSIM,PRINTK)
       END IF

      END IF
C       MAXDEPT .GT. 1


      IF ((PRINTO(19) .EQ. 1) .AND. (FINAL .EQ. 2)) THEN
       OPEN(17,file='ucwn.vec')
      WRITE(17,27511) 3,NUMTEACH,MAXDEPT,MAXDEPTN
      WRITE(17,37511) (DEPARTN(J) , J=1,MAXDEPT)
      WRITE(17,37511) (NEWORDER(J) , J=1,NUMTEACH)
      WRITE(17,4308) 'uswn.DAT'
      CLOSE(17)
      END IF

      IF ((PRINTO(18) .EQ. 1) .AND. (FINAL .EQ. 2)) THEN
      CTACKON='ucgrop00'
      DO 8898 SJ=1,MAXDEPT
      OPEN(14,file='holdname')
      REWIND(14)
      WRITE(14,7760) 'ucgrop',SJ,'.DAT'
      CLOSE(14)
      OPEN(14,file='holdname')
      READ(14,7761) UCFILE
      
C      ITACKON=SJ
C      UCFILE= CTACKON // '.DAT'      
      OPEN(10,file=UCFILE)
      WRITE(10,21092) 4,DEPARTN(SJ),DEPARTN(SJ)
      WRITE(10,7512) (NSUBID(ALLGROUP(SJ,LB)) , LB=1,DEPARTN(SJ))
      DO 7324 G1=1,DEPARTN(SJ)
       WRITE(10,9101) (NEWMAT(ALLGROUP(SJ,G1),ALLGROUP(SJ,G2))
     C  , G2=1,DEPARTN(SJ))
07324   CONTINUE
       CLOSE(10)
08898   CONTINUE
       END IF


      CALL HUBIZE(NEWDEPT,NUMTEACH,RESULTM,STRUCTEQ)

      IF ((PRINTO(4) .EQ. 1) .AND. (FINAL .EQ. 2)) THEN
      OPEN(99,file='place.mat')    
      DO 243 BH = 1,NUMTEACH
      WRITE(99,105) (RESULTM(BH,K) , K=1,NUMTEACH)
  243  CONTINUE
      END IF


       IF (PRINTO(9) .EQ. 1) THEN
      OPEN(58,file='logit.dat')
      DO 1288 I=1,NUMTEACH
       DO 1289 I2=1,NUMTEACH
        SAMEG=0
        IF (NEWDEPT(I) .EQ. NEWDEPT(I2)) THEN
         SAMEG=1
        END IF
        WRITE(58,10251) NSUBID(I),
     C  NSUBID(I2),NEWMAT(I,I2),SAMEG,NEWDEPT(I),NEWDEPT(I2)
01289    CONTINUE
01288     CONTINUE
        CLOSE(58)
        END IF

      LENGTH=NUMTEACH+1
       IF (STRUCTEQ .EQ. 1) THEN
      DO 9277 NO2=1,MAXDEPT
      GAFFIL(NO2)=NO2
       DO 29927 J=1,NUMTEACH
        GSMAT(J,NO2)=INT(10*GROUPMAT(NO2,NEWORDER(J)))
29927   CONTINUE
09277    CONTINUE
       END IF

      DO 92 NO2=1,NUMTEACH
       DO 2992 J=1,NUMTEACH
        GENID(J)=J
        SMAT(NO2,J)=NEWMAT(NEWORDER(NO2),NEWORDER(J))
02992   CONTINUE
        SAFFIL(NO2)=NEWDEPT(NEWORDER(NO2))
        IF (SAFFIL(NO2) .LE. 0) THEN 
         SAFFIL(NO2)=9999
        END IF
00092    CONTINUE


      IF ((PRINTO(16) .EQ. 1) .AND. (FINAL .EQ. 2)) THEN
      OPEN(18,file='ucwnhub.DAT')
      OPEN(54,file='ucwn.DAT')
      WRITE(54,21092) 4,NUMTEACH,NUMTEACH
      WRITE(18,21092) 4,NUMTEACH,NUMTEACH
      WRITE(54,7513) (LB , LB=1,(NUMTEACH-1))
       WRITE(54,7514) NUMTEACH
      WRITE(18,7513) (LB , LB=1,(NUMTEACH-1))
       WRITE(18,7514) NUMTEACH
      DO 8866 I=1,NUMTEACH
      WRITE(18,9101) (RESULTM(I,J) , J=1,NUMTEACH)
      WRITE(54,9101) (NEWMAT(I,J) , J=1,NUMTEACH)
08866 CONTINUE
       CLOSE(18)
        CLOSE(54)
      END IF

C PSTAR OUTPUT HERE     
      PSTFILE=INFILE(1:6) // '.pst'
      IF ((PRINTO(16) .EQ. 3) .AND. (FINAL .EQ. 2)) THEN
      OPEN(54,file=PSTFILE)
      WRITE(54,4301) 'data for prepstar from ',INFILE(1:6),
     C '  Merge by internal ID from ',INFILE(1:6),'.place'
      DO 8856 I=1,NUMTEACH
      WRITE(54,94301) (NEWMAT(I,J) , J=1,NUMTEACH)
08856 CONTINUE
      WRITE(54,4301)
      WRITE(54,662) (NEWORDER(J), J=1,NUMTEACH)
      WRITE(54,94301) MAXDEPT
      WRITE(54,94301) (DEPARTN(J) , J=1,MAXDEPT)
      DO 8787 I=1,MAXDEPT
      DO 8989 J=1,MAXDEPT
      PI=0
      IF (J .EQ. I) THEN 
      PI=1
      END IF
      WRITE(54,762) PI
08989 CONTINUE
      WRITE(54,94301)
08787  CONTINUE
        CLOSE(54)
      END IF

      IF ((PRINTO(16) .EQ. 2) .AND. (FINAL .EQ. 2)) THEN
      OPEN(18,file='struchub.DAT')
      OPEN(54,file='struc.DAT')
      WRITE(54,9103) '(',NUMTEACH,'F4.0)'
      WRITE(18,9103)  '(',NUMTEACH,'F4.0)'
      DO 8826 I=1,NUMTEACH
      WRITE(18,9102) (RESULTM(I,J) , J=1,NUMTEACH)
      WRITE(54,9102) (NEWMAT(I,J) , J=1,NUMTEACH)
08826 CONTINUE
       CLOSE(18)
        CLOSE(54)

      END IF


C      SUBROUTINE MATPRINT(EXTRAID,DIVIDO,MAXDEPT,
C     CNUMTEACH,DOIT,AFFI,MATRIX,TITLE,NSUBID,IEXPECT,ISTD,ICON,
C     CNEWORD,STRUCTEQ,NOWCLOSE,NUMCOL,HOWWIDE)

      CALL MATPRINT(NEWORDER,1,MAXDEPT+1,NUMTEACH,PRINTO(2),SAFFIL,
     C SMAT,
     C 'CHOICES BY GROUPS                       ',
     C NSUBID,IEXPECT,ISTD,ICON,
     C NEWORDER,STRUCTEQ,NOWCLOSE,NUMTEACH,HOWWIDE,SAFFIL,DEPARTN,
     C PRINTO(42))
     
      IF (STRUCTEQ .EQ. 1) THEN
      NOWWIDE=3

      CALL MATPRINT(NEWORDER,1,MAXDEPT+1,NUMTEACH,PRINTO(20),SAFFIL,
     C GSMAT,
     C 'GROUP BLOCKMODELS (VAL=MEAN*10)         ',
     C NSUBID,IEXPECT,ISTD,ICON,
     C NEWORDER,STRUCTEQ,NOWCLOSE,MAXDEPT-1,NOWWIDE,GAFFIL,DEPARTN,
     C PRINTO(42))

       END IF


      CALL MATPRINT(GENID,0,MAXDEPT,NUMTEACH,PRINTO(3),NSUBID,NEWMAT,
     C 'CHOICES IN PERSON ORDER                 ',
     C NSUBID,IEXPECT,ISTD,ICON,
     C NEWORDER,STRUCTEQ,NOWCLOSE,NUMTEACH,HOWWIDE,NSUBID,DEPARTN,
     C PRINTO(42))

      CALL MATPRINT(GENID,0,MAXDEPT,NUMTEACH,PRINTO(4),NSUBID,RESULTM,
     C 'HUBERT MATRIX                           ',
     C NSUBID,IEXPECT,ISTD,ICON,
     C NEWORDER,STRUCTEQ,NOWCLOSE,NUMTEACH,HOWWIDE,NSUBID,DEPARTN,
     C PRINTO(42))

      CALL HUBVAR(NEWMAT,RESULTM,NUMTEACH,HUBSIM,STDHS,ALLCON,
     C HUBM1,HUBSTD1,TOTCOUNT)
      CALL HUBVAR(HUBERT,RESULTM,NUMTEACH,CHNGSIM,CHNGSTD,CHNGCON,
     C HUBM2,HUBSTD2,XTCOUNT)
      CHNGSIM=CHNGSIM/2
      CHNGCON=CHNGCON/2
      NDENOM=NUMTEACH-1.
      IF (STRUCTEQ .EQ. 1) THEN
       NDENOM=NDENOM+1.
      END IF
      OUTOF=MADECHOI*NDENOM/(FSYMMAT+1.)
C      OUTOF=NUMTEACH*(NUMTEACH-1)
        TOTCHII=0.0000
        TOTCHIO=0.0000
       NUMG=0
       DO 8788 TG1=1,MAXDEPT
       G1=GORDER(TG1)
       IF ((DEPARTN(G1) .GT. 1) .AND. (DEPARTN(G1) .LE. MAXGR)) THEN
C       IF (DEPARTN(G1) .GT. 1) THEN
       TOTCHII=TOTCHII+ACHISQRI(G1)+BCHISQRI(G1)
       TOTCHIO=TOTCHIO+ACHISQRO(G1)+BCHISQRO(G1)
       NUMG=NUMG+1
       END IF
08788   CONTINUE
      XPC=TOTCOUNT/OUTOF
      PC=ALLCON/OUTOF
      WRITE(33,194) 'N','N MADE CONN','NON-ISOLATES',
     C'POSS CONNECT'
      WRITE(33,1954) NUMTEACH,MADECHOI,INUM,OUTOF
      WRITE(33,194)
      WRITE(33,194) 'UNWEIGHTED'
      WRITE(33,194) 'CONNECTIONS','% CONNECT'
      WRITE(33,195) ALLCON,PC
      WRITE(33,194)
      WRITE(33,194) 'WEIGHTED'
      WRITE(33,194) 'CONNECTIONS','AVG CONNECT'
      XR1=TOTCOUNT
      WRITE(33,195) XR1,XPC

      IF (LAST .NE. 1) THEN

      WRITE(33,194)
      WRITE(33,194) 'COMPACTNESS'
      WRITE(33,194) 'HUBERT''S'
      WRITE(33,194) '# IN-GROUP CON','EXPECTED','   STD   ',
     C 'STANDARDIZED','P-VALUE'

      UPPER=.FALSE.
      PVAL=ALNORM(STDHS,UPPER)
      WRITE(33,195) HUBSIM,HUBM1,HUBSTD1,STDHS,(1.00000-PVAL)
      WRITE(33,194) '/ACTOR','/NON ISOLATE'
      WRITE(33,195) (STDHS/NUMTEACH),(STDHS/INUM)
      END IF

      WRITE(33,194)
      IF (STRUCTEQ .EQ. 1) THEN

      WRITE(33,194)
      WRITE(33,194) 'REGRESSION'
      WRITE(33,194)
      WRITE(33,2194) 'SOURCE','SS','DF','MS','F','P-VALUE'
      VLABEL='BETWEEN'
      VSS=TSS-WSS
      VDF=MAXDEPT**2.0 - 1
      IVDF=VDF
      VMS=VSS/VDF
      DDF=NUMTEACH**2.0-MAXDEPT**2.0
      VF=VMS/(WSS/(DDF))
      IF ( (VF .GT. 0) .AND. (IVDF .GT. 0) .AND. (DDF .GT. 0)) THEN
C      CALL CDFF (1,VP,VF,IVDF,DDF,IER,BOUND)
C      CALL MDFD (VF,IVDF,DDF,VP,IER)
      END IF
      WRITE(33,2195) VLABEL,VSS,VDF,VMS,VF
C     DIDN'T NEED VP -- DON'T WANT TO DO THE CALL
C     ,(1.000-VP)

      VLABEL='WITHIN'
      VSS=WSS
      VDF=NUMTEACH**2.0-MAXDEPT**2.0 
      VMS=VSS/VDF
      VF=0
      WRITE(33,2195) VLABEL,VSS,VDF,VMS

      VLABEL='TOTAL'
      VSS=TSS
      VDF=NUMTEACH**2
      VMS=VSS/VDF
      VF=0
      WRITE(33,2195) VLABEL,VSS,VDF,VMS
      WRITE(33,194)
      WRITE(33,194) '(R-SQUARE)'
      WRITE(33,195) FCOMPACT
      WRITE(33,1194) 
     C'Note for appproximate statistical testing of the fit of the'
      WRITE(33,1194) 
     C'groups to the pattern of connections it is'
      WRITE(33,1194) 
     C'advisable to use LISREL 7 (by Joreskog and Sorbom, 1989).'
      WRITE(33,1194) 
     C'Also, if actors make relatively few connections to other'
      WRITE(33,1194) 
     C'actors throughout the network it may be advisable to use'
      WRITE(33,1194) 
     C'PRELIS to prepare the essentially dichotimous data for LISREL'

      ELSE
      WRITE(33,194)
      IF (VDIAG .GT. 0) THEN
      IF (LAST .NE. 1) THEN
      WRITE(33,194) 'KLIQUE FINDER''S'
      WRITE(33,194) '# IN-GROUP CON','EXPECTED','   STD   ',
     C 'STANDARDIZED','P-VALUE'
  
      KCOMPACT= ((CDIAG-MDIAG)/VDIAG**.5)

      UPPER=.FALSE.
      PVAL=ALNORM(KCOMPACT,UPPER)
      WRITE(33,195) CDIAG,MDIAG,(VDIAG**.5),KCOMPACT,(1.00000-PVAL)

      WRITE(33,194) '/ACTOR','/NON ISOLATE'
      WRITE(33,195) (FCOMPACT/NUMTEACH),(FCOMPACT/INUM)
      END IF
      TFIXR=INT(FIXR)
      CALL SAMPDIST(NUMTEACH,TFIXR,SAMPMEAN,SAMPSD,CSMEAN,CSSD,
     C   KCOMPACT,ZVAL,SPVAL,CZVAL,CPVAL,PREDACC)
      IF (QUANTYPE .EQ. 1) THEN
      WRITE(33,194)
      WRITE(33,4301) 'SAMPLING DISTRIBUTION, BASED ON'
      WRITE(33,4301) 'ACTUAL NETWORK SIZE'
      IF ((NUMTEACH .LT. 20) .OR. (NUMTEACH .GT. 80))  THEN 
      WRITE(33,4301) 'Sampling distributions based on linear' 
      WRITE(33,4301) 'relationship between network size and '
      WRITE(33,4301) 'compactness.  Quadratic term not used'
      WRITE(33,4301) ' because network size was outside of'
      WRITE(33,4301) 'range of simulated data sets.'
      ELSE
      WRITE(33,4301) 'Sampling distributions based on linear and '
      WRITE(33,4301) 'quadratic relationship between network size'
      WRITE(33,4301) 'and compactness based on simulated data.'
      END IF
      WRITE(33,4301)

        IF ((MAXCH .LT. 3) .OR. (MAXCH .GT. 12)) THEN 
      WRITE(33,4301) 'Sampling distributions based on linear' 
      WRITE(33,4301) 'relationship between maximum connections and'
      WRITE(33,4301) 'compactness.  Quadratic term not used'
      WRITE(33,4301) ' because maximum connections was outside of'
      WRITE(33,4301) 'range of simulated data sets.'

      ELSE
      WRITE(33,4301) 'Sampling distributions based on linear and '
      WRITE(33,4301) 'quadratic relationship between maximum'
      WRITE(33,4301) 'connections and compactness based on' 
      WRITE(33,4301) 'simulated data.'
      WRITE(33,4301)     
      END IF
      WRITE(33,4301) 'See Frank (1993) ''Identifying Cohesive Subgroups'''
      WRITE(33,4301) 'Dissertation, Uiniversity of Chicago'

      WRITE(33,194)
      WRITE(33,194) 'PREDICTED'
      WRITE(33,194) 'SAMPLE MEAN','SAMPLE SD','Z','P-VALUE'
      WRITE(33,195) SAMPMEAN,SAMPSD,ZVAL,(1.00000-SPVAL)

      WRITE(33,194) 'CONSERVATIVE'
      WRITE(33,194) 'SAMPLE MEAN','SAMPLE SD','Z','P-VALUE'
      WRITE(33,195) CSMEAN,CSSD,CZVAL,(1.00000-CPVAL)
      WRITE(33,194)
      WRITE(33,4301) 'PREDICTED ACCURACY: MEAN PCT TRUE SUBGROUP'
      WRITE(33,4301) 'MEMBERS IN OBSERVED SUBGROUP + OR - 30%'
      WRITE(33,195) PREDACC

      CALL SAMPDIST(MADECHOI,TFIXR,SAMPMEA2,SAMPSD2,CSMEAN2,CSSD2,
     C   KCOMPACT,ZVAL2,SPVAL2,CZVAL2,CPVAL2,PREDACC2)
      WRITE(33,194)
      WRITE(33,4301) 'SAMPLING DISTRIBUTION, BASED ON'
      WRITE(33,4301) 'ACTORS WHICH INITIATED EXCHANGES'
      WRITE(33,194)
      WRITE(33,194) 'SAMPLE MEAN','SAMPLE SD','Z','P-VALUE'
      WRITE(33,195) SAMPMEA2,SAMPSD2,ZVAL2,(1.00000-SPVAL2)

      WRITE(33,194) 'CONSERVATIVE'
      WRITE(33,194) 'SAMPLE MEAN','SAMPLE SD','Z','P-VALUE'
      WRITE(33,195) CSMEAN2,CSSD2,CZVAL2,(1.00000-CPVAL2)
      WRITE(33,194)

      END IF


      IF (QUANTYPE .EQ. 5) THEN
       TAO=TOTCOUNT-TAI
       TBI=SAMEG1-TAI
       TBO=(NUMTEACH*(NUMTEACH-1)*MAXCH)-TOTCOUNT-TBI
       
       CALL CONVLAMN(PL,SAMEG1,TOTCOUNT,
     C (NUMTEACH*(NUMTEACH-1)*MAXCH),
     C PALPHA,PBETA,PGAMMA,PDELTA,ROOT,LE)
     
c       WRITE(33,25145) TBO,PALPHA,TAO,PBETA,TBI,PGAMMA,TAI,PDELTA
C        STOP
         MAX9=999999
         MINZ=.0001
         LTBO=0
        IF ((TBO .GT. MINZ) .AND. (PALPHA .GT. MINZ) 
     C  .AND. (TBO .LT. MAX9)
     C  .AND. (PALPHA .LT. MAX9)) THEN
         LTBO=LOG(TBO/PALPHA)
         END IF

         
         LTAO=0
        IF ((TAO .GT. MINZ) .AND. (PBETA .GT. MINZ) 
     C  .AND. (TAO .LT. MAX9)
     C  .AND. (PBETA .LT. MAX9)) THEN
         LTAO=LOG(TAO/PBETA)
         END IF


         LTBI=0
        IF ((TBI .GT. MINZ) .AND. (PGAMMA .GT. MINZ) 
     C  .AND. (TBI .LT. MAX9)
     C  .AND. (PGAMMA .LT. MAX9)) THEN
         LTBI=LOG(TBI/PGAMMA)
         END IF


         LTAI=0
        IF ((TAI .GT. MINZ) .AND. (PDELTA .GT. MINZ) 
     C  .AND. (TAI .LT. MAX9)
     C  .AND. (PDELTA .LT. MAX9)) THEN
         LTAI=LOG(TAI/PDELTA)
         END IF

       PLRT=2*(TBO*LTBO+TAO*LTAO+TBI*LTBI+TAI*LTAI)

C      IF ((TBO/PALPHA .GT. 0) .AND. (TAO/PBETA .GT. 0) 
C     C  .AND. (TBI/PGAMMA .GT. 0) .AND. (TAI/PDELTA .GT. 0)) THEN
C        IF (PDELTA .GT. 0) THEN
C       PLRT=2*(TBO*LOG(TBO/PALPHA)+
C     C TAO*LOG(TAO/PBETA)+
C     C TBI*LOG(TBI/PGAMMA)+
C     C TAI*LOG(TAI/PDELTA))
C        END IF
C        PLRT=2
C      END IF

       GLAMNDA=TAI*TBO
       GLAMNDA=GLAMNDA/(TBI*TAO)

      WRITE(33,194) 
      IF ((GLAMNDA .GT. .00001) .AND. (GLAMNDA .LT. 999999)) THEN
      WTHETA=LOG(GLAMNDA)/2
      WRITE(33,4308) 'VALUE OF THETA1 FOR THESE SUBGROUPS IS'
      WRITE(33,251) WTHETA
      END IF
      WRITE(33,194) 
       WRITE(33,4308) 'THETA1 IS TAKEN FROM THE FOLLOWING MODEL:'
       WRITE(33,4308) 'LOG P(Xii''=xii'')=theta0+theta1(samegroup)'
       WRITE(33,4308)
C       WRITE(33,4308) 'THETA1 ALSO CAN BE INTERPRETED AS HALF THE '
C       WRITE(33,4308) 'LOG-ODDS OF THE FOLLOWING TABLE:'
C       WRITE(33,4308) 
C       WRITE(33,4308) '                  CONNECTION'
C       WRITE(33,4308) '                 NO        YES'
C       WRITE(33,4308) '              ___________________'
C       WRITE(33,4308) '              |        |        |'
C       WRITE(33,4308) '           NO | ALPHA  | BETA   |'
C       WRITE(33,4308) 'IN SAME       |        |        |'
C       WRITE(33,4308) 'GROUP         |--------|--------|'
C       WRITE(33,4308) '              |        |        |'
C       WRITE(33,4308) '          YES | GAMMA  | DELTA  |'
C       WRITE(33,4308) '              |        |        |'
C       WRITE(33,4308) '              -------------------'
C       WRITE(33,4308)

      WRITE(33,4308) 'PREDICTED THETA (1 base) BASED ON SIMULATIONS.'
      WRITE(33,4308) 'VALUE BASED ON UNWEIGHTED DATA.'
      WRITE(33,195) PL
      

       IF ((FIXR .GT. 17) .OR. (NUMTEACH .GT. 80))  THEN
       IF (FIXR .GT. 17) THEN 
         WRITE(33,4308)
       WRITE(33,4308) 'MAXIMUM NUMBER OF RELATIONS FOR A GIVEN ACTOR,'
         WRITE(33,195) FIXR
        WRITE(33,4308) 'IS GREATER THAN THE VALUE OF 18'
        WRITE(33,4308) 'IN THE SIMULATIONS.'
       END IF

       IF (NUMTEACH .GT. 80) THEN 
         WRITE(33,4308)
       WRITE(33,4308) 'SIZE OF NETWORK,'
       WRITE(33,195) NUMTEACH
       WRITE(33,4308)  'IS GREATER THAN THE MAX OF 80'
        WRITE(33,4308) 'IN THE SIMULATIONS.'
       END IF
         WRITE(33,4308)
       WRITE(33,4308) 'WILL USE PREDICTION FOR THETA1base BASED ON'
C       WRITE(33,4308) 'ON LINEAR TERMS AND QUADRATIC TERMS WITH '
       WRITE(33,4308) 'MAXIMUM VALUES FROM SIMULATIONS.'
       WRITE(33,4308) 'INTERPRET WITH CAUTION!'
         WRITE(33,4308)
       WRITE(33,4308) 'CONSIDER GENERATING A UNIQUE SAMPLING'
       WRITE(33,4308) 'DISTRIBUTION BY TYPING:'
       WRITE(33,4308) 'setup sampdist2'
         WRITE(33,4308) 'THE FIRST NUMBER IN THE FILE'
         WRITE(33,4308) 'simulate.par IS THE NUMBER OF SIMULATIONS'
         WRITE(33,4308) 'TO RUN, MODIFY THIS IF YOU WANT.'
         WRITE(33,4308) 'THEN TYPE:'
         WRITE(33,4308) 'nice kliqfind yourfile s'
         WRITE(33,4308) 'AFTER IT IS DONE RUNNING, TYPE:'     
         WRITE(33,4308) 'sas sampdist'
         WRITE(33,4308) 'AND LOOK AT THE HISTOGRAM IN sampdist.lst'
         WRITE(33,4308) 'NOTE THAT YOU MIGHT WANT TO DO THIS IN'
         WRITE(33,4308) 'A SEPARATE DIRECTORY.'
       END IF

       WRITE(33,4308)

C      LAMNDA(G1)=.00000001

C      IF (ABS(TLAMNDA) .GT. .00000001) THEN
C      TTL=ABS(TLAMNDA)
C      TTL=TTL
C      IF (TTL .GT. .0001) THEN
C      LAMNDA(G1)=LOG(TTL)
C      END IF

        TGLAMNDA=.00000001      
       IF (GLAMNDA .GT. .00000001) THEN
        TGLAMNDA=LOG(GLAMNDA+.00000001)/2.00
        END IF
      WRITE(33,4308) 'ESTIMATE OF THETA (1 subgroup processes)'
      WRITE(33,195) (TGLAMNDA-PL)
       WRITE(33,4308)
      WRITE(33,4308) 'THE TOTAL THETA1 IS:'
      WRITE(33,195) TGLAMNDA
       WRITE(33,4308)
      WRITE(33,194) 
C      WRITE(33,4308) 'VALUE OF THETA1 FOR THESE SUBGROUPS IS'
C      WRITE(33,195) (LOG(GLAMNDA))/2.00
C      WRITE(33,194) 
C       WRITE(33,4308) 'THETA1 IS TAKEN FROM THE FOLLOWING MODEL:'
C       WRITE(33,4308) 'LOG P(Xii'=xii')=theta0+theta1(samegroup)'
       WRITE(33,4308)
       WRITE(33,4308) 'THETA1 ALSO CAN BE INTERPRETED AS HALF THE '
       WRITE(33,4308) 'LOG-ODDS OF THE FOLLOWING TABLE,'
       WRITE(33,4308) 'INCLUDING OBSERVED AND (EXPECTED) VALUES:'
       WRITE(33,4308) 
       WRITE(33,4308) '                      TIE'
       WRITE(33,4308) '                 NO        YES'
       WRITE(33,4308) '              ___________________'
       WRITE(33,4308) '              |        |        |'
       WRITE(33,4358) '           NO | ',TBO,'  | ',TAO,'  |'
       WRITE(33,4358) '              |(',PALPHA,') |(',PBETA,') |'
       WRITE(33,4308) 'IN SAME       |        |        |'
       WRITE(33,4308) 'SUBGROUP      |--------|--------|'
       WRITE(33,4308) '              |        |        |'
       WRITE(33,4358) '          YES | ',TBI,'  | ',TAI,'  |'
       WRITE(33,4358) '              |(',PGAMMA,') |(',PDELTA,') |'
       WRITE(33,4308) '              |        |        |'
       WRITE(33,4308) '              -------------------'
       WRITE(33,4308)

C      WRITE(33,4308) 'CORRESPONDING ODDS RATIO'
C      WRITE(33,195) LE
         ODDSR=TAI*TBO/(TAO*TBI)
       WRITE(33,4308)
       WRITE(33,4308) '         ODDS RATIO, LOG ODDS, (LOG ODDS/2)'
       WRITE(33,4308) '-------------------------------------------'
       IF (ODDSR .LE. 0) THEN
       ODDSR=.01
       END IF
       IF (ODDSR .GT. .0000001) THEN 
       WRITE(33,7273) 'Observed|',ODDSR,
     C LOG(ODDSR+.0000001),(LOG(ODDSR+.0000001))/2
       OPEN(58,FILE='alltheta.txt')
       CALL MOVEEND(58)
C      QZQZ
       WRITE(58,'(A,1X,F15.5)')infile,ODDSR
       CLOSE(58)
       END IF
         IF (PBETA*PGAMMA .GT. 0) THEN
         ODDSR=PDELTA*PALPHA/(PBETA*PGAMMA)
         END IF
         IF (PBETA*PGAMMA .EQ. 0) THEN
         ODDSR=99999
         END IF
              
       WRITE(33,4308)
       IF (ODDSR .LE. 0) THEN
       ODDSR=.01
       END IF
       IF ((ODDSR .GT. .0000001) .AND. (ODDSR .LT. 999999)) THEN 
       WODDSR=LOG(ODDSR+.0000001)
       WODDSR2=WODDSR/2       
       WRITE(33,7273) 'Expected|',ODDSR,WODDSR,WODDSR2
       END IF
       WRITE(33,4308)

       WRITE(33,4308)


C      WRITE(33,195) (TGLAMNDA-PL)
      TG1=1
C      RCHI=PLRT-(ALRT+BLRT)
      RCHI=PLRT
      PVAL=.5
C      IF (RCHI .LE. 2.705) THEN
C      WRITE(33,4301) 'P-VALUE > .1'
C      END IF

      IF (RCHI .GT. 2.705) THEN
       PVAL=.1
      END IF

      IF (RCHI .GT. 3.841) THEN
       PVAL=.05
      END IF

      IF (RCHI .GT. 5.024) THEN
       PVAL=.025
      END IF

      IF (RCHI .GT. 6.635) THEN
       PVAL=.01
      END IF

      IF (RCHI .GT. 7.879) THEN
       PVAL=.005
      END IF

      IF (RCHI .GT. 10.828) THEN
       PVAL=.001
      END IF

      WRITE(33,4308) 'APPROXIMATE TEST OF CONCENTRATION OF TIES'
       WRITE(33,4308) 'WITHIN SUBGROUPS BASED ON'
       WRITE(33,4308) 'SIZE OF THETA1 subgroup processes:'
       WRITE(33,4308)


       WRITE(33,4308)
       WRITE(33,4308) '      THETA1 |'
       WRITE(33,4308) '    SUBGROUP | APPROX |  APPROX'
       WRITE(33,4308) '    PROCESSES|  LRT   | P-VALUE'

      WRITE(33,2518) (TGLAMNDA-PL),PLRT,PVAL
       WRITE(33,4308)
       PERMPVAL=PVAL


       WRITE(33,4308)

C       WRITE(33,4308) 'CONSERVATIVE THETA (1 base)'
       CPL=PL+.032
C       WRITE(33,195) CPL
C      WRITE(33,4308)
C      WRITE(33,4308) 'APPROX LRT BASED ON CONSERVATIVE '
C      WRITE(33,4308) 'PREDICTED THETA (1 base)'
       CALL CONVLAMN(CPL,SAMEG1,TOTCOUNT,(NUMTEACH*(NUMTEACH-1)*MAXCH),
     C PALPHA,PBETA,PGAMMA,PDELTA,ROOT,LE)
C        WRITE(33,25145) TBO,PALPHA,TAO,PBETA,TBI,PGAMMA,TAI,PDELTA
C         STOP 
C     
        IF ((TBO/PALPHA .GT. .001) .AND. (TAO/PBETA .GT. .001) 
     C  .AND. (TBI/PGAMMA .GT. .001) .AND. (TAI/PDELTA .GT. .001)) THEN
       CPLRT=2*(TBO*LOG(TBO/PALPHA)+
     C TAO*LOG(TAO/PBETA)+
     C TBI*LOG(TBI/PGAMMA)+
     C TAI*LOG(TAI/PDELTA))
         END IF

C      WRITE(33,195) CPLRT
       WRITE(33,4308)
C      WRITE(33,4308) 'COMPARE TO CHI-SQUARE ON 1 DF'
C        WRITE(33,4308)
C        WRITE(33,4308) 'APPROX P-VALUE IS:'


      TG1=1
C      RCHI=PLRT-(ALRT+BLRT)
      RCHI=CPLRT
      PVAL=.5
C      IF (RCHI .LE. 2.705) THEN
C      WRITE(33,4301) 'P-VALUE > .1'
C      END IF
      IF (RCHI .GT. 2.705) THEN
       PVAL=.1
      END IF

      IF (RCHI .GT. 3.841) THEN
       PVAL=.05
      END IF

      IF (RCHI .GT. 5.024) THEN
       PVAL=.025
      END IF

      IF (RCHI .GT. 6.635) THEN
       PVAL=.01
      END IF

      IF (RCHI .GT. 7.879) THEN
       PVAL=.005
      END IF

      IF (RCHI .GT. 10.828) THEN
       PVAL=.001
      END IF


C      WRITE(33,195) (PVAL)

      WRITE(33,4308) 'APPROXIMATE TEST OF CONCENTRATION OF TIES'
       WRITE(33,4308) 'WITHIN SUBGROUPS BASED ON CONSERVATIVE'
       WRITE(33,4308) 'PREDICTED VALUE FOR THETA1'
       WRITE(33,4308)
       WRITE(33,4308) '      THETA1 |'
       WRITE(33,4308) '    SUBGROUP | APPROX |  APPROX'
       WRITE(33,4308) '    PROCESSES|  LRT   | P-VALUE'

       WRITE(33,2518) (TGLAMNDA-CPL),CPLRT,PVAL
       WRITE(33,4308)


       WRITE(33,4308)
       WRITE(33,4308) 'These p-values are based on a likelihood'
        WRITE(33,4308) 'ratio test between the models:'
       WRITE(33,4308)
       WRITE(33,4308) 'LOG P(Xii''=xii'')=theta0+theta1base(samegroup)'
       WRITE(33,4308)
       WRITE(33,4308)
     C     'LOG P(Xii''=xii'')=theta0+theta1base(samegroup) +'
       WRITE(33,4308) ' theta1 subgroup processes(samegroup) '
       WRITE(33,4308)
       WRITE(33,4308) 'A SMALL P-VALUE INDICATES THAT ONE CAN'
       WRITE(33,4308) 'REJECT THE NULL HYPOTHESIS THAT '
       WRITE(33,4308) ' theta1 subgroup processes IS ZERO.'
       WRITE(33,4308) 'AND WE TAKE THIS AS EVIDENCE THAT ACTORS'
       WRITE(33,4308) 'ENGAGE IN EXCHANGES WITHIN SUBGROUPS AT '
       WRITE(33,4308) 'A RATE THAT IS UNLIKELY TO HAVE OCCURRED'
       WRITE(33,4308) 'BY CHANCE ALONE.'

      MAXSIZE=0
      DO 62614 J=1,MAXDEPT
      IF (DEPARTN(J) .GT. MAXSIZE) THEN
      MAXSIZE=DEPARTN(J)
      END IF
62614 CONTINUE
         IF ((GLAMNDA .GT. .0000001) .AND. (GLAMNDA .LT. 9999999)) THEN
         WGLAMNDA=LOG(GLAMNDA+.0000001)/2
      PREDACC=1.4572+.7009*(PL-.8993) + 1.1977*(WGLAMNDA-PL-.3692)
     C + .0867*(MAXSIZE-5.737) + .0038*(NUMTEACH-51.7488)
         END IF
      WRITE(33,4308)
      WRITE(33,4308)
      WRITE(33,4308) '-----------------------------------------------'
      WRITE(33,4308)
      WRITE(33,4308)

      WRITE(33,4301) 'PREDICTED ACCURACY: LOG ODDS OF COMMON SUBGROUP'
      WRITE(33,4301) 'MEMBERSHIP, + OR - .5734 (FOR A 95% CI)'
      WRITE(33,8195) PREDACC
       WRITE(33,4308)
       WRITE(33,4308) 'The Log odds applies to the following table:'
       WRITE(33,4308)
       WRITE(33,4308) '                  OBSERVED SUBGROUP'
       WRITE(33,4308) '                  DIFFERENT   SAME'
       WRITE(33,4308) '                 ___________________'
       WRITE(33,4308) '                 |        |        |'
       WRITE(33,4308) '       DIFFERENT |   A    |   B    |'
       WRITE(33,4308) 'KNOWN            |        |        |'
       WRITE(33,4308) 'SUBGROUP         |--------|--------|'
       WRITE(33,4308) '                 |        |        |'
       WRITE(33,4308) '            SAME |   C    |   D    |'
       WRITE(33,4308) '                 |        |        |'
       WRITE(33,4308) '                 -------------------'
       WRITE(33,4308)
      WRITE(33,4301) 'THE LOGODDS TRANSLATES TO AN ODDS RATIO OF '
      WRITE(33,195) (EXP(PREDACC))
       WRITE(33,4308)
      WRITE(33,4301) 'WHICH INDICATES THE INCREASE IN THE ODDS'
      WRITE(33,4301) 'THAT KLIQUEFINDER WILL ASSIGN TWO ACTORS TO'
      WRITE(33,4301) 'THE SAME SUBGROUP IF THEY ARE TRULY IN THE '
      WRITE(33,4301) 'IN THE SAME SUBGROUP.'
      END IF



      END IF

      WRITE(33,194)
       GLAMNDA=TAI*TBO
       GLAMNDA=GLAMNDA/(TBI*TAO)
      IF (LAST .NE. 1) THEN
      WRITE(33,194) 'MEASURES OF FIT'
      WRITE(33,194) 'PEARSON','LIKE RATIO','SUM (ZI**2)',
     C 'ALT LIKE RATIO','ODDS RATIOS','THETA1'
      IF (GLAMNDA .GT. 0.00001) THEN
      WRITE(33,195) (APEARSON+BPEARSON),(ALRT+BLRT),
     C (AEQUPEAR+BEQUPEAR)/2.,(ANLRT+BNLRT),GLAMNDA,
     C LOG(GLAMNDA)/2
      END IF
      WRITE(33,194) 'DEGREES OF FREEDOM'
      WRITE(33,195) (NUMG)
      WRITE(33,194) 'P-VALUES'
      RCHI=APEARSON+BPEARSON
C      IF (RCHI .GT. 0) THEN
      IF ((RCHI .GT. 1) .AND. (RCHI .LT. 99999)) THEN 
      CALL MDCH(RCHI,NUMG,PVAL,IER)
      END IF
      RCHI=ALRT+BLRT
      IF ((RCHI .GT. 1) .AND. (RCHI .LT. 99999)) THEN 
C      IF (RCHI .GT. 0) THEN
      CALL MDCH(RCHI,NUMG,PVAL2,IER)
      END IF
      RCHI=AEQUPEAR+BEQUPEAR

      IF ((RCHI .GT. 1) .AND. (RCHI .LT. 99999)) THEN 
      CALL MDCH(RCHI,NUMG,PVAL3,IER)
      END IF
      WRITE(33,195) (PVAL),(PVAL2),(PVAL3)


      WRITE(33,194) 'SUM OF Zi','P-VALUE'
      UPPER=.FALSE.
      PVAL=ALNORM(FCOMPAC2,UPPER)
      WRITE(33,195) FCOMPAC2,(1.0000-PVAL)
      WRITE(33,194) '/ACTOR','/NON ISOLATE'
      WRITE(33,195) (FCOMPAC2/NUMTEACH),(FCOMPAC2/INUM)
      WRITE(33,194)

      WRITE(33,194) 'SUM OF Zi/Ng'
      WRITE(33,195) FCOMPAC5
      WRITE(33,194) '/ACTOR','/NON ISOLATE'
      WRITE(33,195) (FCOMPAC5/NUMTEACH),(FCOMPAC5/INUM)
      WRITE(33,194)
      END IF

      END IF

      WRITE(33,62)
      IF (PRINTT .EQ. 2) THEN
C  191 FORMAT(/,'SIMILARITY BETWEEN THE START AND END GROUPS:   ACTUAL 
C     C  POSS  STANDARDIZED',/,43X,I7,3X,I7,3X,F10.5)
      WRITE(33,191) CHNGSIM,CHNGCON,CHNGSTD
      WRITE(33,62)
      END IF
      BCHNGSIM=CHNGSIM
      BCHNGCON=CHNGCON
      BCHNGSTD=CHNGSTD

C      IF (STRUCTEQ .EQ. 1) THEN
C      WRITE(33,77) ' SUM OF SQUARES '
C      ELSE
C      WRITE(33,77) ' ASSOCIATIONS -- COMPACTNESS'
C      END IF

       LMAXDEPT=MAXDEPT
        CALL REMOVEO2(LMAXDEPT,DEPARTN,LGROUP,1,QUICKEND)

       WRITE(33,4301)
C      IF ((FINAL .EQ. 2) .AND. (PRINTO(13) .EQ. 1)) THEN
C      DO 3293 G1=2,LMAXDEPT
C       WRITE(510,103) (COVMAT(LGROUP(G1),LGROUP(U)) ,
C     C  U=1,G1-1)
C 3293  CONTINUE
C       END IF

      IF ((PRINTO(17) .EQ. 1) .AND. (FINAL .EQ. 2)) THEN
      OPEN(4,file='ucgc.DAT')
      WRITE(4,21091) 4,LMAXDEPT,LMAXDEPT
      WRITE(4,7511) (LB , LB=1,LMAXDEPT)
      DO 7323 G1=2,LMAXDEPT
       WRITE(4,7103) (COVMAT(LGROUP(G1),LGROUP(U)) ,
     C  U=1,G1-1)
07323   CONTINUE
      END IF

       IF ((SIMO .EQ. 1) .OR. (PRINTO(27) .EQ. 1)) THEN
      TD=0
      DO 3113 G1=1,LMAXDEPT

      IF ((DEPARTN(LGROUP(G1)) .GT. 1) .AND. 
     C (DEPARTN(LGROUP(G1)) .LE. MAXGR))  THEN
      TD=TD+1
      TRUEDEPT(TD)=DEPARTN(LGROUP(G1))
      SLOTTD(TD)=TD
      END IF
03113   CONTINUE
      ACTG=TD
      SORTFLAG=2
      IF (TD .GT. 1) THEN
      CALL SPSORT(TRUEDEPT,TD,SLOTTD,SORTFLAG,IER)
      MEDDEPT=TRUEDEPT(INT(TD/2.))
            END IF
       ONDIAG=0
       ONDIAG2=0
       ONDIAG3=0
       ONDIAG4=0
       TOTPACT=0
       TOTPACT2=0
       DO 7787  G2=1,LMAXDEPT
       ONDIAG=ONDIAG+COVMAT(G2,G2)
       ONDIAG2=ONDIAG2+COVMAT2(G2,G2)
       ONDIAG3=ONDIAG3+COVMAT3(G2,G2)
       ONDIAG4=ONDIAG4+COVMAT4(G2,G2)
       IF ((DEPARTN(G2) .GT. 0) .AND. (DEPARTN(G2) .LE. MAXGR)) THEN
       TOTPACT=TOTPACT+COVMAT(G2,G2)/DEPARTN(G2)
       TOTPACT2=TOTPACT2+COVMAT2(G2,G2)/DEPARTN(G2)
       END IF
07787   CONTINUE


       END IF
      NUMDIM=2
      IF ((FINAL .EQ. 2) .AND. (PRINTO(38) .EQ. 1) .AND. 
     C (NUMDIM .GT. 0))  THEN
      LINKFILE='inlist.list'
      SIXTEEN=16
      SIXTEEN=UNLINK(LINKFILE)
      STATUS=SYMLNK(INFILE,LINKFILE)

C      DANCHOR=1
C      ZSYMMAT=1
C      STARTINC=6
C      MAXINC=22
C      BYINC=4
C      IGRATIO=7.5

      IMEANVAL=0
C      CENTER=1

C      MOVE2=0
      IMAXVAL=HIWT

      DO 7723 I=1,MAXDEPT
      DO 77231 J=1,NUMDIM
      GCOORD(I,J)=0
77231  CONTINUE
07723   CONTINUE

      IF (PRINTO(39) .EQ. 1) THEN

      IF (NORMAL .EQ. 1) THEN
      N2=1
      ELSE
      N2=0
      END IF

      DO 7721 I=1,NUMTEACH
      DO 77212 J=1,NUMDIM
      ICOORD(I,J)=0
      ZICOORD(I,J)=0
77212 CONTINUE
      IANGLE(I)=0
      IRADIUS(I)=0

      ZIRADIUS(I)=0
      IANCHOR(I)=1
C       MINVALI=.75
C       MINVALG=.10
07721  CONTINUE


      DO 82821 I=1,MAXDEPT

         IF ((DEPARTN(I) .GT. 1) .AND. (DEPARTN(I) .LE. MAXGR)) THEN
      CALL ONEPIECE(I,DEPARTN(I),TEMPMAT,OLDORD,TF1)
       IF (BYANGLE .EQ. 2) THEN
       WRITSMAC=1
       TWARP=0
      CALL PLOTMAT(TEMPMAT,DEPARTN(I),DANCHORI,NUMDIM,
     C STARTINI,ZSYMMATI,TICOORD,MAXINCI,BYINCI,TMEANVAL,NUMTEACH,
     C TIANGLE,TIRADIUS,CENTERI,TANCHOR,DANCH2I,MOVE2I,IMAXVAL,
     C DRADIUSI,
     C KEXPI,NORMALI,MINVALI,TF1,BYANGLEI,BYSCALEI,MINPICT,
     C PCTCENI1,PCTCENI2,WRITSMAC,TWARP,RANGEEIG)
C       CALL RUNSMAC
       WRITSMAC=2
      CALL PLOTMAT(TEMPMAT,DEPARTN(I),DANCHORI,NUMDIM,
     C STARTINI,ZSYMMATI,TICOORD,MAXINCI,BYINCI,TMEANVAL,NUMTEACH,
     C TIANGLE,TIRADIUS,CENTERI,TANCHOR,DANCH2I,MOVE2I,IMAXVAL,
     C DRADIUSI,
     C KEXPI,NORMALI,MINVALI,TF1,BYANGLEI,BYSCALEI,MINPICT,
     C PCTCENI1,PCTCENI2,WRITSMAC,TWARP,RANGEEIG)
       END IF
       TWARP=1
C       IF (IMAXVAL .LE. 1) THEN
C       TWARP=0
C       END IF 
       WRITSMAC=3
      CALL PLOTMAT(TEMPMAT,DEPARTN(I),DANCHORI,NUMDIM,
     C STARTINI,ZSYMMATI,TICOORD,MAXINCI,BYINCI,TMEANVAL,NUMTEACH,
     C TIANGLE,TIRADIUS,CENTERI,TANCHOR,DANCH2I,MOVE2I,IMAXVAL,
     C DRADIUSI,
     C KEXPI,NORMALI,MINVALI,TF1,BYANGLEI,BYSCALEI,MINPICT,
     C PCTCENI1,PCTCENI2,WRITSMAC,TWARP,RANGEEIG)

       GWARP(I) =0
       GRANGE1(I)=0
       GRANGE2(I)=0
       IF (DEPARTN(I) .GT. 0) THEN
       GWARP(I)=TWARP
       GRANGE1(I)=RANGEEIG(1)
       GRANGE2(I)=RANGEEIG(2)
       END IF

      IF (TMEANVAL .GT. IMEANVAL) THEN
      IMEANVAL=TMEANVAL
      END IF
      DO 6769 J=1,DEPARTN(I)
      DO 6799 K=1,NUMDIM
      ZICOORD(OLDORD(J),K)=TICOORD(J,K)
06799 CONTINUE
      IANGLE(OLDORD(J))=TIANGLE(J)
      IANCHOR(OLDORD(J))=TANCHOR(J)
      ZIRADIUS(OLDORD(J))=TIRADIUS(J)
06769  CONTINUE
       END IF
82821   CONTINUE
      IF (NORMALI .EQ. 0) THEN
      IMEANVAL=HIWT
      END IF
      IF (NORMALI .EQ. 2) THEN
      IMEANVAL=-LOG(.01)
      END IF
      IF ((NORMALI .EQ. 3) .AND. (HIWT .GT. 0) 
     C .AND. (MINVALI .GT. 0)) THEN
      IMEANVAL=LOG(HIWT)-LOG(ABS(MINVALI))
       END IF
      IF (NORMALI .EQ. -3) THEN
      IMEANVAL=HIWT
       END IF

      END IF
C      IF (PRINTO(39) .EQ. 1) THEN

      IF (MAXDEPT .GT. 1)  THEN
      
      IF  (PRINTO(30) .EQ. 1) THEN
      GMAXVAL=0
       IF (BYANGLE .EQ. 2) THEN
       WRITSMAC=1
      CALL PLOTMAT(COVMAT,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,N2,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPA,RANGEEIG)

       WRITSMAC=2
      CALL PLOTMAT(COVMAT,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,N2,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPA,RANGEEIG)

       END IF
       TWARPA=1
       WRITSMAC=3
      CALL PLOTMAT(COVMAT,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,N2,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPA,RANGEEIG)


      DISTFILE=INFILE(1:6) // '.agang'
      COORFILE=INFILE(1:6) // '.acord'
      WITHID=0
      CALL OUTCOORD(COORFILE,MAXDEPT,NUMDIM,GCOORD,WITHID,LGROUP,
     C GANGLE,GRADIUS,LGROUP,ANCHOR,GHIER,FITG,NSIM,PRINTK,PRINTO(27),
     C ISTRESS,
     C ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,GRANGE2)


      IF (PRINTO(39) .EQ. 1) THEN
      NRATIO=GMAXVAL/(IGRATIO*IMEANVAL)
      IF (PRINTO(41) .EQ. 1) THEN
C      RINCREM=10
C      MEASURE=2
C      EXTREME=1

      CALL ROTATE(ICOORD,GCOORD,NUMTEACH,MAXDEPT,IANGLE,ZIRADIUS,
     C RINCREM,MEASURE,DEPARTN,NRATIO,EXTREME,IMEANVAL,IRADIUS)

      ELSE

        DO 8783 I=1,MAXDEPT
        DO 8785 J=1,DEPARTN(I)
        DO 8784 K=1,NUMDIM
      ICOORD(ALLGROUP(I,J),K)=GCOORD(I,K)+
     C ZICOORD(ALLGROUP(I,J),K)*NRATIO
08784  CONTINUE
      IRADIUS(ALLGROUP(I,J))=ZIRADIUS(ALLGROUP(I,J))
     C *GMEANVAL/(IGRATIO*IMEANVAL)

08785   CONTINUE
08783    CONTINUE
      END IF

      COORFILE=INFILE(1:6) // '.aicrd'
      DISTFILE=INFILE(1:6) // '.adist'
      WITHID=1

      CALL KSTRESS(STRESSA,ICOORD,NORMALI,NUMTEACH,IMAXVAL,
     C MINVALI,KEXPI,STRESS2A,FITI,ISTRESS,STRESS3A,
     C ISTRESS2,ISTRESS3,ZICOORD,DISTFILE,PRINTO,NEWDEPT,NSUBID,
     C ODDSA)
      WRITE(33,7474) 'The stress associated with ',COORFILE,' is '
     C ,STRESSA

      WRITE(33,7474) 'The warp associated with ',COORFILE,' is '
     C ,TWARPA

      DISTFILE=INFILE(1:6) // '.aiang'
      CALL OUTCOORD(COORFILE,NUMTEACH,NUMDIM,ICOORD,
     C WITHID,NSUBID,IANGLE,IRADIUS,NEWDEPT,IANCHOR,IHIER,FITI,
     C NSIM,PRINTK,PRINTO(27),ISTRESS,
     C ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,GRANGE2)
      END IF
C      PRINTO(39)
      END IF
C      (PRINTO(30) .EQ. 1) THEN

C to here


      IF (PRINTO(32) .EQ. 1) THEN 
      GMAXVAL=HIWT
       IF (BYANGLE .EQ. 2) THEN
       WRITSMAC=1
       CALL PLOTMAT(COVMAT3,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,NORMAL,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPB,RANGEEIG)

       WRITSMAC=2
       CALL PLOTMAT(COVMAT3,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,NORMAL,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPB,RANGEEIG)
       END IF
       TWARPB=1
       WRITSMAC=3
       CALL PLOTMAT(COVMAT3,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,NORMAL,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPB,RANGEEIG)

      COORFILE=INFILE(1:6) // '.bcord'
      DISTFILE=INFILE(1:6) // '.bgang'
      WITHID=0
      CALL OUTCOORD(COORFILE,MAXDEPT,NUMDIM,GCOORD,WITHID,LGROUP,
     C GANGLE,GRADIUS,LGROUP,ANCHOR,GHIER,FITG,NSIM,PRINTK,PRINTO(27),
     C ISTRESS,
     C ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,GRANGE2)
 


      IF (PRINTO(39) .EQ. 1) THEN
      IF ((NORMAL .EQ. 2) .AND. (MINVALG .GT. 0)) THEN
      GMAXVAL=-LOG(ABS(MINVALG))
      END IF
      IF ((NORMAL .EQ. 3) .AND. (HIWT .GT. 0) 
     C .AND. (MINVALG .GT. 0)) THEN
      GMAXVAL=LOG(HIWT)-LOG(MINVALG)
       END IF

      IF (NORMAL .EQ. -3) THEN
       GMAXVAL=HIWT
       END IF


       TOTRAD=0.0
       DO 5654 I=1,NUMTEACH
       TOTRAD=TOTRAD+ZIRADIUS(I)
05654  CONTINUE
       MEANRAD=TOTRAD/NUMTEACH
       QMAXY=0.0
       QMINY=0.0
        WRITE(33,'(A)') 'GROUP          WARP'

       DO 56567 I=1,MAXDEPT
       WRITE(33,'(I10,F10.5)') I,GWARP(I)
       IF (GCOORD(I,1) .GT. QMAXY) THEN 
       QMAXY=GCOORD(I,1)
       END IF
       
       IF (GCOORD(I,1) .LT. QMINY) THEN 
       QMINY=GCOORD(I,1)
       END IF
       IF (GCOORD(I,2) .GT. QMAXX) THEN 
       QMAXX=GCOORD(I,2)
       END IF
       
       IF (GCOORD(I,2) .LT. QMINX) THEN 
       QMINX=GCOORD(I,2)
       END IF
56567 CONTINUE
       LDIMY=ABS(QMAXY-QMINX)
       LDIMX=ABS(QMAXX-QMINX)
       LONGDIM=LDIMY
       IF (LDIMX .GT. LDIMY) THEN
       LONGDIM=LDIMX
       END IF
       TR=12.00
       TIGRATIO=LONGDIM/(TR*MEANRAD)
       NRATIO=1.00

       IF (ABS(IGRATIO) .GT. 0.000001) THEN
       NRATIO=TIGRATIO*IGRATIO
       END IF

C     NRATIO=GMAXVAL/(IGRATIO*IMEANVAL)
      IF (PRINTO(41) .EQ. 1) THEN
C      RINCREM=10
C      MEASURE=2
C      EXTREME=1

      CALL ROTATE(ICOORD,GCOORD,NUMTEACH,MAXDEPT,IANGLE,ZIRADIUS,
     C RINCREM,MEASURE,DEPARTN,NRATIO,EXTREME,IMEANVAL,IRADIUS)

      ELSE

        DO 28783 I=1,MAXDEPT
        DO 28785 J=1,DEPARTN(I)
        DO 28784 K=1,NUMDIM
      ICOORD(ALLGROUP(I,J),K)=GCOORD(I,K)+
     C ZICOORD(ALLGROUP(I,J),K)*NRATIO
28784  CONTINUE
      IRADIUS(ALLGROUP(I,J))=ZIRADIUS(ALLGROUP(I,J))
     C *GMEANVAL/(IGRATIO*IMEANVAL)

28785   CONTINUE
28783    CONTINUE
      END IF

      COORFILE=INFILE(1:6) // '.bicrd'
      DISTFILE=INFILE(1:6) // '.bdist'
      WITHID=1
        IFILE=INFILE(1:6)  // '.ilabel' 
        NFILE=INFILE(1:6)  // '.xnet' 
                NDFILE=INFILE(1:6)  // '.vna'
         DO 54549 I=1,NUMTEACH
        Write(ILABEL(I), '(I5)')  NSUBID(I)
        HAVELAB(I)=0
C        ,NSUBID(I),
C     C  NSUBID(I),NSUBID(I),NSUBID(I)
54549   CONTINUE

C        AFILE=INFILE(1:6)  // '.natt' 

C        OPEN(58,file=AFILE)
C        OPEN(59,file='CHECKIT')
C        DO 54654 I=1,NUMTEACH
C        READ (58,'(I10,1X,A20,5f10.5)',END=54545) 
C        READ (58,*,END=54546) TEMPID,NA1,NA2,NA3,NA4,NA5
C        GOTLAB=0
C        CHECKI=1
C        DO WHILE ((GOTLAB .EQ. 0) .AND. (CHECKI .LE. NUMTEACH))
C        IF (TEMPID .EQ. NSUBID(CHECKI)) THEN
C        GOTLAB=1
C        INA1(CHECKI)=NA1
C        INA2(CHECKI)=NA2
C        INA3(CHECKI)=NA3
C        INA4(CHECKI)=NA4
C        INA5(CHECKI)=NA5
C        END IF
C        CHECKI=CHECKI+1     
C        END DO
        
C54654   CONTINUE
c qqq
C54546   CLOSE(58)
        QNET=1
        OPEN (58,file=NFILE)
        DO 45456 I=1,10000
        READ (58,*,END=62646) XNET1(QNET),XNET2(QNET),XNET3(QNET)
        QNET=QNET+1
45456    CONTINUE
62646   CLOSE(58)        
        

        OPEN(58,file=IFILE)
C        OPEN(59,file='CHECKIT')
        DO 5454 I=1,NUMTEACH
*        READ (58,'(I10,1X,A20,5f10.5)',END=54545) 
        READ (58,'(I10,1X,A20)',END=54545) TEMPID,TEMPLAB
        GOTLAB=0
        CHECKI=1
        DO WHILE ((GOTLAB .EQ. 0) .AND. (CHECKI .LE. NUMTEACH))
C        WRITE(59,'(5I10,A20)') I,CHECKI,GOTLAB,TEMPID,
C     C  NSUBID(CHECKI),TEMPLAB 
        IF (TEMPID .EQ. NSUBID(CHECKI)) THEN
        GOTLAB=1
        HAVELAB(CHECKI)=1
        ILABEL(CHECKI)=TEMPLAB
        END IF
        CHECKI=CHECKI+1     
        END DO
       
05454   CONTINUE
c qqq
54545   CLOSE(58)


        OPEN(58,file=NDFILE,BLANK='NULL')
C      WRITE(58,'(A)') 'TR LONGDIM MEANRAD GMAXVAL IMEANVAL 
C     C NRATIO IGRATIO QMAXY QMAXX QMINY QMINX'
C      WRITE(58,'(10F10.5)') TR,LONGDIM,MEANRAD,GMAXVAL,IMEANVAL,
C     C NRATIO,IGRATIO,QMAXY,QMAXX,QMINY,QMINX

C       CALL MOVEEND(58)
      COLOR=255
      SHAPE=1
      SIZE=10
C      NUMDIM=2


C XX 
      
      LABELS(1)='A'
      LABELS(2)='B'
      LABELS(3)='C'
      LABELS(4)='D'
      LABELS(5)='E'
      LABELS(6)='F'
      LABELS(7)='G'
      LABELS(8)='H'
      LABELS(9)='I'
      LABELS(10)='J'
      LABELS(11)='K'
      LABELS(12)='L'
      LABELS(13)='M'
      LABELS(14)='N'
      LABELS(15)='O'
      LABELS(16)='P'
      LABELS(17)='Q'
      LABELS(18)='R'
      LABELS(19)='S'
      LABELS(20)='T'
      LABELS(21)='U'
      LABELS(22)='V'
      LABELS(23)='W'
      LABELS(24)='X'
      LABELS(25)='Y'
      LABELS(26)='Z'
      LABELS(27)='a'
      LABELS(28)='b'
      LABELS(29)='c'
      LABELS(30)='d'
      LABELS(31)='e'
      LABELS(32)='f'
      LABELS(33)='g'
      LABELS(34)='h'
      LABELS(35)='i'
      LABELS(36)='j'
      LABELS(37)='k'
      LABELS(38)='l'
      LABELS(39)='m'
      LABELS(40)='n'
      LABELS(41)='o'
      LABELS(42)='p'
      LABELS(43)='q'
      LABELS(44)='r'
      LABELS(45)='s'
      LABELS(46)='t'
      LABELS(47)='u'
      LABELS(48)='v'
      LABELS(49)='w'
      LABELS(50)='x'
      LABELS(51)='y'
      LABELS(52)='z'
      LABELS(53)='AA'
      LABELS(54)='BB'
      LABELS(55)='CC'
      LABELS(56)='DD'
      LABELS(57)='EE'
      LABELS(58)='FF'
      LABELS(59)='GG'
      LABELS(60)='HH'
      LABELS(61)='II'
      LABELS(62)='JJ'
      LABELS(63)='KK'
      LABELS(64)='LL'
      LABELS(65)='MM'
      LABELS(66)='NN'
      LABELS(67)='OO'
      LABELS(68)='PP'
      LABELS(69)='QQ'
      LABELS(70)='RR'
      LABELS(71)='SS'
      LABELS(72)='TT'
      LABELS(73)='UU'
      LABELS(74)='VV'
      LABELS(75)='WW'
      LABELS(76)='XX'
      LABELS(77)='YY'
      LABELS(78)='ZZ'
      LABELS(79)='AB'
      LABELS(80)='AC'
      LABELS(81)='AD'
      LABELS(82)='AE'
      LABELS(83)='AF'
      LABELS(84)='AG'
      LABELS(85)='AH'
      LABELS(86)='AI'
      LABELS(87)='AJ'
      LABELS(88)='AK'
      LABELS(89)='AL'
      LABELS(90)='AM'
      LABELS(91)='AN'
      LABELS(92)='AO'
      LABELS(93)='AP'
      LABELS(94)='AQ'
      LABELS(95)='AR'
      LABELS(96)='AS'
      LABELS(97)='AT'
      LABELS(98)='AU'
      LABELS(99)='AV'
      LABELS(100)='AW'
      LABELS(101)='AX'
      LABELS(102)='AY'
      LABELS(103)='AZ'
      LABELS(104)='BA'
      LABELS(105)='BB'
      LABELS(106)='BC'
      LABELS(107)='BD'
      LABELS(108)='BE'
      LABELS(109)='BF'
      LABELS(110)='BG'
      LABELS(111)='BH'
      LABELS(112)='BI'
      LABELS(113)='BK'
      LABELS(114)='BL'
      LABELS(115)='BM'
      LABELS(116)='BN'
      LABELS(117)='BO'
      LABELS(118)='BP'
      LABELS(119)='BQ'
      LABELS(120)='BR'
      LABELS(121)='BS'
      LABELS(122)='BT'
      LABELS(123)='BU'
      LABELS(124)='BW'
      LABELS(125)='BX'
      
          
      colors(1)='16711680'
      colors(2)='16576'
      colors(3)='16744512'
      colors(4)='49407'
      colors(5)='4227200'
      colors(6)='16760832'
      colors(7)='4259776'
      colors(8)='12632128'
      colors(9)='12583167'
      colors(10)='65408'
      colors(11)='8421376'
      colors(12)='16761024'
      colors(13)='8388672'
      colors(14)='12615935'
      colors(15)='128'
      colors(16)='4210688'
      colors(17)='4227264'
      colors(18)='64'
      colors(19)='16744703'
      colors(20)='12599424'
      colors(21)='8453888'
      colors(22)='16777152'
      colors(23)='8421440'
      colors(24)='8454143'
      colors(25)='12583040'
      colors(26)='8404992'
      colors(27)='4243648'
      colors(28)='12599360'
      colors(29)='16777215'
      colors(30)='12632192'
      colors(31)='65280'
      colors(32)='12583104'
      colors(33)='4243520'
      colors(34)='255'
      colors(35)='4194432'
      colors(36)='12615680'
      colors(37)='4210880'
      colors(38)='16728128'
      colors(39)='12648447'
      colors(40)='16744576'
      colors(41)='0'
      colors(42)='49344'
      colors(43)='4227136'
      colors(44)='8388863'
      colors(45)='16512'
      colors(46)='4194304'
      colors(47)='16728256'
      colors(48)='12615744'
      colors(49)='16639'
      colors(50)='32896'
      colors(51)='12582912'
      colors(52)='8405184'
      colors(53)='4194368'
      colors(54)='16761087'
      colors(55)='16777088'
      colors(56)='4259584'
      colors(57)='32960'
      colors(58)='16777024'
      colors(59)='16728319'
      colors(60)='8405120'
      colors(61)='12648192'
      colors(62)='12615872'
      colors(63)='8453952'
      colors(64)='4259839'
      colors(65)='16760960'
      colors(66)='49152'
      colors(67)='16744640'
      colors(68)='8437824'
      colors(69)='33023'
      colors(70)='12648320'
      colors(71)='12599296'
      colors(72)='12648384'
      colors(73)='16448'
      colors(74)='65535'
      colors(75)='16711808'
      colors(76)='8388608'
      colors(77)='8454080'
      colors(78)='8405056'
      colors(79)='16711935'
      colors(80)='8388736'
      colors(81)='4243456'
      colors(82)='8421568'
      colors(83)='32832'
      colors(84)='12632319'
      colors(85)='4243584'
      colors(86)='16744448'
      colors(87)='16711872'
      colors(88)='4259648'
      colors(89)='8438015'
      colors(90)='4259712'
      colors(91)='16384'
      colors(92)='8437952'
      colors(93)='65344'
      colors(94)='8421631'
      colors(95)='8437888'
      colors(96)='12632064'
      colors(97)='12599488'
      colors(98)='16760896'
      colors(99)='4210943'
      colors(100)='4210816'
      colors(101)='32768'
      colors(102)='4194496'
      colors(103)='12582976'
      colors(104)='8405247'
      colors(105)='12615808'
      colors(106)='16728064'
      colors(107)='12632256'
      colors(108)='4210752'
      colors(109)='4194559'
      colors(110)='8421504'
      colors(111)='4227072'
      colors(112)='65472'
      colors(113)='49216'
      colors(114)='4227327'
      colors(115)='49280'
      colors(116)='8437760'
      colors(117)='192'
      colors(118)='16711744'
      colors(119)='12599551'
      colors(120)='8454016'
      colors(121)='16776960'
      colors(122)='8388800'
      colors(123)='12648256'
      colors(124)='4243711'
      colors(125)='16728192'    

      
c   
        NUMPT=8
        WANTGR=1

       WRITE(58,777) '*node data'
       WRITE(58,777) 'id type group WARP RADIUS NA1 NA2 NA3 NA4 NA5'
       WANTCIRC=0
       
        IF (WANTGR .GT. 0.0) THEN
       TYPE=2
       DO 2823 I=1,MAXDEPT
C       WRITE(58,'(3X,A2,A2,A6,1x,I1,1X,I3)') '"0',
C     C  LABELS(I),'black"',TYPE,I
       WRITE(58,'(3X,A2,A2,A1,1x,I1,1X,I3,5F10.5)') '"0',
     C  LABELS(I),'"',TYPE,I,GWARP(I),GRADIUS(I)

       IF (WANTCIRC .EQ. 1) THEN
       DO 2924 J=1,NUMPT
       WRITE(58,'(3X,A2,A2,I2.2,A1,1x,I1,1X,I3,1X,F10.5)') '"0',
     C  LABELS(I),J,'"',TYPE,I,GWARP(I),GRADIUS(I)
02924  CONTINUE
        END IF
       
        MAXRAD(I)=0
02823  CONTINUE
        END IF
       TYPE=1

       QIMINX=0.00
       QIMINY=0.00
       QIMAXX=0.00
       QIMAXY=0.00
        KZERO=0       
       DO 4545 I=1,NUMTEACH
       IF (ICOORD(I,1) .GT. QIMAXX) THEN
       QIMAXX=ICOORD(I,1)
       END IF
       IF (ICOORD(I,1) .LT. QIMINX) THEN
       QIMINX=ICOORD(I,1)
       END IF
       IF (ICOORD(I,2) .GT. QIMAXY) THEN
       QIMAXY=ICOORD(I,2)
       END IF
       IF (ICOORD(I,2) .LT. QIMINY) THEN
       QIMINY=ICOORD(I,2)
       END IF
       IF (HAVELAB(I) .EQ. 1) THEN 
       WRITE(58,'(I8,1x,I1,1x,I3,1X,2F10.5,A)') NSUBID(I),
     C TYPE,NEWDEPT(I),IRADIUS(I),IRADIUS(I),ILABEL(I)
       ELSE
       WRITE(58,'(I8,1x,I1,1x,I3,1X,2F10.5,1X,A5,1x,4I2)') NSUBID(I),
     C TYPE,NEWDEPT(I),IRADIUS(I),IRADIUS(I),ILABEL(I),KZERO,
     C KZERO,KZERO,KZERO
       END IF

     
04545   CONTINUE
        LDIM=QIMAXX-QIMINX
        IF ((QIMAXY-QIMINY) .GT. LDIM) THEN
        LDIM=QIMAXY-QIMINY
        END IF

        WRITE(58,'(A)') '"IGRATIO" 3 0'
        WRITE(58,'(A)') '"EVIDENCE" 3 0'
        WRITE(58,'(A)') '"DATA="  3 0'

       WRITE(58,220) '*Node properties'
       WRITE(58,*) 'ID x y color shape size active shortlabel' 
C     C NA1 NA2 NA3 NA4 NA5'
       IF (WANTGR .EQ. 1) THEN
        DO 877 I=1,MAXDEPT
        DMINX(I)=0
        DMAXX(I)=0
        DMINY(I)=0
        DMAXY(I)=0
00877   CONTINUE
        DO 8182 I=1,NUMTEACH
        IF (IRADIUS(I) .GT. MAXRAD(NEWDEPT(I))) THEN
        MAXRAD(NEWDEPT(I))=IRADIUS(I)
        END IF
        CTG1=GCOORD(NEWDEPT(I),1)
        CTG2=GCOORD(NEWDEPT(I),2)
        IF ((ICOORD(I,1)-CTG1) .GT. DMAXX(NEWDEPT(I))) THEN
        DMAXX(NEWDEPT(I)) = ICOORD(I,1)-CTG1
        END IF
        IF ((ICOORD(I,1)-CTG1) .LE. DMINX(NEWDEPT(I))) THEN
         DMINX(NEWDEPT(I)) = ICOORD(I,1)-CTG1
        END IF
        IF ((ICOORD(I,2)-CTG2) .GT. DMAXY(NEWDEPT(I))) THEN
        DMAXY(NEWDEPT(I)) = ICOORD(I,2)-CTG2
        END IF
        IF ((ICOORD(I,2)-CTG2) .LE. DMINY(NEWDEPT(I))) THEN
         DMINY(NEWDEPT(I)) = ICOORD(I,2)-CTG2
        END IF
 
08182   CONTINUE
        PI=3.14159265
        COLOR=0
       DO 28231 I=1,MAXDEPT
       RANGEX=DMAXX(I)-DMINX(I)
       RANGEY=DMAXY(I)-DMINY(I)
       DIAM=DMAXX(I)-DMINX(I)
       IF ((DMAXY(I)-DMINY(I)) .GT. DIAM) THEN
       DIAM = DMAXY(I)-DMINY(I)
       END IF
       SIZE=INT(450.0*DIAM/LDIM)
       IF (SIZE .LE. 30.0) THEN
       SIZE=30.0
       END IF
       
       CTG1=GCOORD(I,1)+DMAXX(I)-RANGEX/2.0
       CTG2=GCOORD(I,2)+DMAXY(I)-RANGEY/2.0
c        write(58,*) 'CTG1,GCOORD(I,1),DMAXX(I),RANGEX/2.0,
c     C CTG2,GCOORD(I,2),DMAXY(I),RANGEY/2.0'
c     
c        write(58,*) CTG1,GCOORD(I,1),DMAXX(I),RANGEX/2.0,
c     C CTG2,GCOORD(I,2),DMAXY(I),RANGEY/2.0
        
C       WRITE(33,*) 'I,DMAXX(I),DMINX(I),DMAXY(I),DMINY(I),DIAM'
C       WRITE(33,*) I,DMAXX(I),DMINX(I),DMAXY(I),DMINY(I),DIAM
C              WRITE(58,
C     C '(4X,A2,A2,A6,1X,F10.5,1X,F10.5,1X,I8,1X,I1,1X,I8,1X,A2,1X,A4)')
C     C '"0', LABELS(I),'black"',CTG2,CTG1,
C     C COLOR,SHAPE,SIZE,LABELS(I),'TRUE'
              WRITE(58,
     C '(4X,A2,A2,A1,1X,F15.5,1X,F15.5,1X,I8,1X,I1,1X,I8,
     C   1X,A4,1X,A2)')
     C '"0', LABELS(I),'"',CTG2,CTG1,
     C 16777215,SHAPE,SIZE,'TRUE',LABELS(I)
       IF (WANTCIRC .EQ. 1) THEN
       DO 82924 J=1,NUMPT
       TJ=J-1.0
       TNP=NUMPT+0.0
       OUTRAD=1.2*DIAM
       IF (OUTRAD .LE. 3.0) THEN
       OUTRAD=3.0
       END IF
       ANGLE=(2.00*PI*(TJ)/(TNP))
       CTG1=OUTRAD*SIN(ANGLE)+GCOORD(I,1)
       CTG2=OUTRAD*COS(ANGLE)+GCOORD(I,2)
              WRITE(58,
     C '(4X,A2,A2,I2.2,A1,1X,F15.5,1X,F15.5,1X,
     C  I8,1X,I1,1X,I8,1X,A2,1X,A4)')
     C '"0', LABELS(I),J,'"',CTG2,CTG1,
     C 0,SHAPE,1,'""','TRUE'
82924  CONTINUE
        END IF

28231  CONTINUE
      END IF
       SIZE=10
       ONE=1
        DO 4646 I=1,NUMTEACH
        TCOLOR=NEWDEPT(I)
        IF (TCOLOR .LE. 0) THEN TCOLOR=0
       WRITE(58,
     C '(I8,1X,F15.5,1X,F15.5,1X,A8,1X,I1,1X,I3,1X,A5,1X,A20)')
     C NSUBID(I),ICOORD(I,2),ICOORD(I,1),
     C COLORS(TCOLOR),SHAPE,SIZE,' TRUE',ILABEL(I)
04646   CONTINUE

        WRITE(58,'(A,1X,F20.5,1X,F15.5,1X,I8,1X,I1,1X,I2,2A,F7.2,A)')
     C  '"IGRATIO"',QIMINX,.9*QIMINY,16777215,8,SIZE,' TRUE',
     C  ' "Distances within vs between groups:',NRATIO,'"'
        
C  ZZZZ
        WRITE(58,'(A,1X,F20.5,1X,F15.5,1X,I8,1X,I1,1X,I2,2A,F7.2,A)')
     C  '"EVIDENCE"',QIMINX,1.1*QIMINY,16777215,8,SIZE,' TRUE'
     C  ,' "Clusters p-val ',PERMPVAL,'"'
             WRITE(58,'(A,1X,F20.5,1X,F15.5,1X,I8,1X,I1,1X,I2,2A,A6,A)')
     C  '"DATA="',QIMINX,.8*QIminY,16777215,8,SIZE,' TRUE'
     C  ,' "DATA=',infile,'"'


       ONE=1
       ZERO=0
       FRIENDS=1
       WRITE(58,*) '*Tie data'
       WRITE(58,803) 'from to any strength actor between within group 
     C  xnet'
        WANTCIRC=0
        wantgr=1
        IF (WANTGR .EQ. 1) THEN
       DO 5155 I=1,MAXDEPT
C       WRITE(58,'(4X,A2,A2,A9,A2,A6,1X,I1,1X,I3,1X,I1)') 
C     C '"0',LABELS(I),'black" "0',LABELS(I),'white"',ZERO,ONE,0,ONE
       DO 5755 J=1,MAXDEPT
       IF (I .NE. J) THEN
       TLSIZE=1
       TLSIZE=TLSIZE+INT(20.0*COVMAT3(I,J))
       IF (TLSIZE .GT. 0) THEN
       WRITE(58,'(4X,A2,A2,A4,A2,A1,1X,I1,1X,I3,1X,I1,1X,I1,
     C 1X,I1,1X,I1)') 
     C '"0',LABELS(I),'" "0',LABELS(J),'"',ONE,TLSIZE,ZERO,ZERO,
     C ZERO,ONE
        END IF
       IF (WANTCIRC .EQ. 1) THEN
        DO 5766 K=2,NUMPT
       WRITE(58,'(4X,A2,A2,I2.2,A4,A2,I2.2,A1,1X,I1,1X,I3,1X,I1)') 
     C '"0',LABELS(I),K-1,'" "0',LABELS(I),K,'"',ONE,TLSIZE,ZERO
05766    CONTINUE        
       WRITE(58,'(4X,A2,A2,I2.2,A4,A2,I2.2,A1,1X,I1,1X,I3,1X,I1)') 
     C '"0',LABELS(I),NUMPT,'" "0',LABELS(I),1,'"',ONE,TLSIZE,ZERO
        END IF
        END IF
05755 CONTINUE
05155  CONTINUE
        END IF

       DO 25228 I=1,NUMTEACH
       DO 25329 J=1,NUMTEACH
       IF ((J .NE. I) .AND. (NEWMAT(I,J) .GT. 0)) THEN
       BETWEEN=1
       WITHIN=0
   
       IF (NEWDEPT(I) .EQ. NEWDEPT(J)) THEN 
       BETWEEN=0
       WITHIN=1
       END IF
       WRITE(58,'(I8,1X,I8,1X,I1,1X,I3,1X,I1,1X,I1,1X,I1,1X,I1)') 
     C NSUBID(I),NSUBID(J),ONE,NEWMAT(I,J),ONE,BETWEEN,WITHIN,ZERO
       END IF
25329 CONTINUE
25228 CONTINUE

      DO 25230 I=1,QNET-1
       WRITE(58,'(I8,1X,I8,1X,I1,1X,I3,1X,I1,1X,I1,1X,I1,1X,I1,1X,I3)') 
     C XNET1(I),XNET2(I),ONE,ZERO,ZERO,ZERO,ZERO,ZERO,XNET3(I)
25230 CONTINUE
        WRITE(58,'(A)')'"IGRATIO" "EVIDENCE" 1 1 1'
 
         WRITE(58,'(A)')'"IGRATIO" "DATA=" 1 1 1'
       WRITE(58,*) '*Tie properties'
      WRITE(58,*) 'FROM TO color size headcolor headsize active'
      WANTGR=1
      IF (WANTGR .EQ. 1) THEN
      COLOR=16777215
      DO 7155 I=1,MAXDEPT
        IF (WANTCIRC .EQ. 1) THEN
        DO 5767 K=2,NUMPT
       WRITE(58,'(A2,A2,I2.2,A4,A2,I2.2,A1,1X,I8,1X,I3,1X,I8,1X,A7)') 
     C '"0',LABELS(I),K-1,'" "0',LABELS(I),K,'"',0,2,
     C  0,' 0 TRUE'
05767    CONTINUE        
       WRITE(58,'(A2,A2,I2.2,A4,A2,I2.2,A1,1X,I8,1X,I3,1X,I8,1X,A7)') 
     C '"0',LABELS(I),NUMPT,'" "0',LABELS(I),1,'"',0,2,
     C  0,' 0 TRUE'
       END IF

C       WRITE(58,'(A2,A2,A9,A2,A6,1X,I8,1X,I3,1X,I8,1X,A7)') 
C     C '"0',LABELS(I),'black" "0',LABELS(I),'white"',COLOR,0,
C     C  COLOR,' 0 TRUE'
       COLOR=12632256

        DO 7235 J=1,MAXDEPT
         IF (I .NE. J) THEN
         TLSIZE=1
         TLSIZE=1+INT(40.0*COVMAT3(I,J))
         IF (TLSIZE .GT. 0) THEN

             WRITE(58,'(A2,A2,A4,A2,A1,1X,I8,1X,I3,1X,I8,1X,A7)') 
     C '"0',LABELS(I),'" "0',LABELS(J),'"',COLOR,TLSIZE,
     C  COLOR,' 0 TRUE'
         END IF 
        END IF
      
07235 CONTINUE
07155 CONTINUE
       END IF
       
      DO 27228 I=1,NUMTEACH
       DO 27329 J=1,NUMTEACH
       IF ((J .NE. I) .AND. (NEWMAT(I,J) .GT. 0)) THEN
       TLSIZE=1
       IF (HIWT .GT. 1) THEN 
       TLSIZE=INT(4*NEWMAT(I,J)/HIWT)
       END IF
       COLOR=0
       LTYPE=0
       IF (NEWDEPT(I) .NE. NEWDEPT(J)) THEN
       COLOR=12632256
       LTYPE=1
       END IF
       WRITE(58,'(I8,1X,I8,1X,I8,1X,I2,1X,A8)') 
     C NSUBID(I),NSUBID(J),COLOR,TLSIZE,'0 8 TRUE'
       END IF
27329 CONTINUE
27228 CONTINUE
 
       WRITE(58,'(A)')'"IGRATIO" "EVIDENCE" 16777215 1 0 8 TRUE'
       WRITE(58,'(A)')'"IGRATIO" "DATA=" 16777215 1 0 8 TRUE'


       CLOSE(58)

      CALL KSTRESS(STRESSB,ICOORD,NORMALI,NUMTEACH,IMAXVAL,
     C MINVALI,KEXPI,STRESS2B,FITI,ISTRESS,STRESS3B,
     C ISTRESS2,ISTRESS3,ZICOORD,DISTFILE,PRINTO,NEWDEPT,NSUBID,
     C ODDSB)
      WRITE(33,7474) 'The stress associated with ',COORFILE,' is ',
     C STRESSB
      WRITE(33,7474) 'The warp associated with ',COORFILE,' is ',
     C TWARPB

      DISTFILE=INFILE(1:6) // '.biang'
      CALL OUTCOORD(COORFILE,NUMTEACH,NUMDIM,ICOORD,
     C WITHID,NSUBID,IANGLE,IRADIUS,NEWDEPT,IANCHOR,IHIER,FITI,
     C NSIM,PRINTK,PRINTO(27),ISTRESS,
     C ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,GRANGE2)

       
      DO 7272 I=1,NUMTEACH
       DO 72721 J=1,NUMDIM
      BICOORD(I,J)=ICOORD(I,J)
72721  CONTINUE
07272   CONTINUE
      END IF
C      PRINTO(39)

      END IF


      IF (PRINTO(31) .EQ. 1) THEN 
       GMAXVAL=0
      IF (BYANGLE .EQ. 2) THEN
      WRITSMAC=1
      CALL PLOTMAT(COVMAT2,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,N2,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPC,RANGEEIG)

      WRITSMAC=2
      CALL PLOTMAT(COVMAT2,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,N2,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPC,RANGEEIG)
      END IF
       TWARPC=1
      WRITSMAC=3
      CALL PLOTMAT(COVMAT2,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,N2,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPC,RANGEEIG)
      COORFILE=INFILE(1:6) // '.ccord'
      DISTFILE=INFILE(1:6) // '.cgang'
      WITHID=0
      CALL OUTCOORD(COORFILE,MAXDEPT,NUMDIM,GCOORD,WITHID,LGROUP,
     C GANGLE,GRADIUS,LGROUP,ANCHOR,GHIER,FITG,NSIM,PRINTK,PRINTO(27),
     C ISTRESS,
     C ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,GRANGE2)


      IF (PRINTO(39) .EQ. 1) THEN
C      IMEANVAL=HIWT
      NRATIO=GMAXVAL/(IGRATIO*IMEANVAL)
      IF (PRINTO(41) .EQ. 1) THEN
C      RINCREM=10
C      MEASURE=2
C      EXTREME=1

      CALL ROTATE(ICOORD,GCOORD,NUMTEACH,MAXDEPT,IANGLE,ZIRADIUS,
     C RINCREM,MEASURE,DEPARTN,NRATIO,EXTREME,IMEANVAL,IRADIUS)

      ELSE

        DO 38783 I=1,MAXDEPT
        DO 38785 J=1,DEPARTN(I)
        DO 38784 K=1,NUMDIM
      ICOORD(ALLGROUP(I,J),K)=GCOORD(I,K)+
     C ZICOORD(ALLGROUP(I,J),K)*NRATIO
38784  CONTINUE
      IRADIUS(ALLGROUP(I,J))=ZIRADIUS(ALLGROUP(I,J))
     C *GMEANVAL/(IGRATIO*IMEANVAL)

38785   CONTINUE
38783    CONTINUE
      END IF

      COORFILE=INFILE(1:6) // '.cicrd'
      DISTFILE=INFILE(1:6) // '.cdist'
      WITHID=1
      CALL KSTRESS(STRESSC,ICOORD,NORMALI,NUMTEACH,IMAXVAL,
     C MINVALI,KEXPI,STRESS2C,FITI,ISTRESS,STRESS3C,
     C ISTRESS2,ISTRESS3,ZICOORD,DISTFILE,PRINTO,NEWDEPT,NSUBID,
     C ODDSC)
      WRITE(33,7474) 'The stress associated with ',COORFILE,' is ',
     C STRESSC
      WRITE(33,7474) 'The warp associated with ',COORFILE,' is ',
     C TWARPC

      DISTFILE=INFILE(1:6) // '.ciang'
      CALL OUTCOORD(COORFILE,NUMTEACH,NUMDIM,ICOORD,
     C WITHID,NSUBID,IANGLE,IRADIUS,NEWDEPT,IANCHOR,IHIER,FITI,
     C NSIM,PRINTK,PRINTO(27),ISTRESS,
     C ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,GRANGE2)
      END IF
C      PRINTO(39)

      END IF

      IF (PRINTO(33) .EQ. 1) THEN
      GMAXVAL=1
      IF (BYANGLE .EQ. 2) THEN
       WRITSMAC=1
      CALL PLOTMAT(COVMAT4,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,NORMAL,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPD,RANGEEIG)

       WRITSMAC=2
      CALL PLOTMAT(COVMAT4,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,NORMAL,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPD,RANGEEIG)
       END IF 
       TWARPD=1
       WRITSMAC=3
      CALL PLOTMAT(COVMAT4,MAXDEPT,DANCHOR,NUMDIM,
     C STARTINC,ZSYMMAT,GCOORD,MAXINC,BYINC,GMEANVAL,MAXDEPT,
     C GANGLE,GRADIUS,CENTER,ANCHOR,DANCHOR2,MOVE2,GMAXVAL,DRADIUS,
     C KEXP,NORMAL,MINVALG,MAXDEPT,BYANGLE,BYSCALE,MINPICT,
     C PCTCENG1,PCTCENG2,WRITSMAC,TWARPD,RANGEEIG)


      COORFILE=INFILE(1:6) // '.dcord'
      DISTFILE=INFILE(1:6) // '.dgang'
      WITHID=0
      CALL OUTCOORD(COORFILE,MAXDEPT,NUMDIM,GCOORD,WITHID,LGROUP,
     C GANGLE,GRADIUS,LGROUP,ANCHOR,GHIER,FITG,NSIM,PRINTK,PRINTO(27),
     C ISTRESS,ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,
     C GRANGE2)


      IF (PRINTO(39) .EQ. 1) THEN
      IF ((NORMAL .EQ. 2) .AND. (MINVALG .GT. 0))  THEN
      GMAXVAL=-LOG(ABS(MINVALG))
      END IF
      IF ((NORMAL .EQ. 3) .AND. (GMAXVAL .GT. 0) 
     C  .AND. (MINVALG .GT. 0)) THEN
      GMAXVAL=LOG(GMAXVAL)-LOG(ABS(MINVALG))
       END IF
      IF (NORMAL .EQ. -3) THEN
       GMAXVAL=GMAXVAL/ABS(MINVALG)
       END IF

      NRATIO=GMAXVAL/(IGRATIO*IMEANVAL)
      IF (PRINTO(41) .EQ. 1) THEN
C      RINCREM=10
C      MEASURE=2
C      EXTREME=1

      CALL ROTATE(ICOORD,GCOORD,NUMTEACH,MAXDEPT,IANGLE,ZIRADIUS,
     C RINCREM,MEASURE,DEPARTN,NRATIO,EXTREME,IMEANVAL,IRADIUS)

      ELSE

        DO 48783 I=1,MAXDEPT
        DO 48785 J=1,DEPARTN(I)
        DO 48784 K=1,NUMDIM
      ICOORD(ALLGROUP(I,J),K)=GCOORD(I,K)+
     C ZICOORD(ALLGROUP(I,J),K)*NRATIO
48784  CONTINUE
      IRADIUS(ALLGROUP(I,J))=ZIRADIUS(ALLGROUP(I,J))
     C *GMEANVAL/(IGRATIO*IMEANVAL)

48785   CONTINUE
48783    CONTINUE
      END IF

      COORFILE=INFILE(1:6) // '.dicrd'
      DISTFILE=INFILE(1:6) // '.ddist'
      WITHID=1
      CALL KSTRESS(STRESSD,ICOORD,NORMALI,NUMTEACH,IMAXVAL,
     C MINVALI,KEXPI,STRESS2D,FITI,ISTRESS,STRESS3D,
     C ISTRESS2,ISTRESS3,ZICOORD,DISTFILE,PRINTO,NEWDEPT,NSUBID,
     C ODDSD)
      WRITE(33,7474) 'The stress associated with ',COORFILE,' is ',
     C STRESSD
      WRITE(33,7474) 'The warp associated with ',COORFILE,' is ',
     C TWARPD

      DISTFILE=INFILE(1:6) // '.diang'
      CALL OUTCOORD(COORFILE,NUMTEACH,NUMDIM,ICOORD,
     C WITHID,NSUBID,IANGLE,IRADIUS,NEWDEPT,IANCHOR,IHIER,FITI,
     C NSIM,PRINTK,PRINTO(27),ISTRESS,
     C ISTRESS2,ISTRESS3,PRINTO(43),DISTFILE,GWARP,GRANGE1,GRANGE2)
      END IF
C      PRINTO(39)
 
      END IF

       END IF
C   IF (MAXDEPT .GT. 1) 
       END IF
C      IF ((FINAL .EQ. 2) .AND. (PRINTO(38) .EQ. 1) .AND. 
C     C (NUMDIM .GT. 0))  THEN

      IF ((FINAL .EQ. 2) .AND. (PRINTO(13) .EQ. 1)) THEN
      OPEN(59,file='MDSSCALE.CMD')
      WRITE(59,4301) 'NOTE ''',TITLES(1),TITLES(2),TITLES(3),
     C '  ',INFILE,
     C ''''
      WRITE(59,4301) 'USE MDSD'
      WRITE(59,4301) 'OUTPUT MDSO'
      WRITE(59,4301) 'SCALE'
      CLOSE(59)
      IF (PRINTO(30) .EQ. 1) THEN
      CALL MDSCMD('Compactness','corr ','A',TITLES,LMAXDEPT,INFILE,
     C LGROUP,COVMAT)
      END IF
      IF (PRINTO(32) .EQ. 1) THEN 
      CALL MDSCMD('Density    ','bcorr ','B',TITLES,LMAXDEPT,INFILE,
     C LGROUP,COVMAT3)
      END IF
      IF (PRINTO(31) .EQ. 1) THEN 
      CALL MDSCMD('Sum of Zi  ','ccorr ','C',TITLES,LMAXDEPT,INFILE,
     C LGROUP,COVMAT2)
      END IF
      IF (PRINTO(33) .EQ. 1) THEN 
      CALL MDSCMD('Within grp ','dcorr ','D',TITLES,LMAXDEPT,INFILE,
     C LGROUP,COVMAT4)
      END IF

      END IF

      IF ((PRINTO(30) .EQ. 1) .AND. (LMAXDEPT .GT. 0)) THEN
      CALL GROUPASC (COVMAT,LMAXDEPT,LGROUP,DEPARTN,
     C 0,1,INUM,NUMTEACH,INFILE,'dat ',PRINTO(34),LABEL,PRINTO(27),0,
     C NSIM,FINAL,MAXDEPT,PRINTK,LAMNDA)

      IF (PRINTO(35) .EQ. 1) THEN
      CALL PERXPER(COVMAT,NUMTEACH,NEWDEPT,'dat ',NSUBID,LGROUP,
     C LMAXDEPT,MAXDEPT)
      END IF

       WRITE(33,4301)
      WRITE(33,3308) 'NETLEV'
      WRITE(33,3307) (GCENTRAL(GORDER(G1)) , G1=1,LMAXDEPT)
       WRITE(33,4301)
      END IF
      IF ((PRINTO(31) .EQ. 1) .AND. (LMAXDEPT .GT. 0)) THEN
       WRITE(33,4301)
      WRITE(33,77) ' ASSOCIATIONS (SUM OF Zi) '
      CALL GROUPASC (COVMAT2,LMAXDEPT,LGROUP,DEPARTN,
     C 0,1,INUM,NUMTEACH,INFILE,'cdat',PRINTO(34),LABEL,PRINTO(27),0,
     C NSIM,FINAL,MAXDEPT,PRINTK,LAMNDA)
      IF (PRINTO(35) .EQ. 1) THEN
      CALL PERXPER(COVMAT2,NUMTEACH,NEWDEPT,'cdat',NSUBID,LGROUP,
     C LMAXDEPT,MAXDEPT)
      END IF
      END IF

       IF ((PRINTO(32) .EQ. 1) .AND. (LMAXDEPT .GT. 0)) THEN
          WRITE(33,4301)
       WRITE(33,4301) 'MEAN WITHIN GROUP CONNECTION (DENSITY)'
       WRITE(33,251)
      IF (FLAGR .EQ. 1) THEN
       WRITE(33,8282) FIXR,' GREATER THAN OR EQUAL TO ',OLDR
     C ,' FORMER '
      ELSE
       WRITE(33,8282) NFIXR,' LESS THAN ',OLDR,' LATTER '
       FIXR=OLDR
      END IF
       WRITE(33,251)
   
      CALL GROUPASC (COVMAT3,LMAXDEPT,LGROUP,DEPARTN,
     C 0,1,INUM,NUMTEACH,INFILE,'bdat',PRINTO(34),LABEL,PRINTO(27),1,
     C NSIM,FINAL,MAXDEPT,PRINTK,LAMNDA)
      IF (PRINTO(35) .EQ. 1) THEN
      CALL PERXPER(COVMAT3,NUMTEACH,NEWDEPT,'bdat',NSUBID,LGROUP,
     C LMAXDEPT,MAXDEPT)
      END IF
       WRITE(33,62)
       WRITE(33,4301) 'NETWORK WIDE MEAN WITHIN GROUP CONNECTION'
       WRITE(33,195) FCOMPAC9
       WRITE(33,62)
       END IF

       WRITE(33,62)
       IF ((PRINTO(33) .EQ. 1) .AND. (LMAXDEPT .GT. 0)) THEN
       WRITE(33,4301)
       WRITE(33,4301) 'PCT CONNECTIONS THAT OCCUR WITHIN GROUP'
      CALL GROUPASC (COVMAT4,LMAXDEPT,LGROUP,DEPARTN,
     C 0,0,INUM,NUMTEACH,INFILE,'ddat',PRINTO(34),LABEL,PRINTO(27),1,
     C NSIM,FINAL,MAXDEPT,PRINTK,LAMNDA)
      IF (PRINTO(35) .EQ. 1) THEN
      CALL PERXPER(COVMAT4,NUMTEACH,NEWDEPT,'ddat',NSUBID,LGROUP,
     C LMAXDEPT,MAXDEPT)
      END IF
      WRITE(33,4301) 'NETWORK WIDE PCT CONNECTIONS IN GROUPS'
       WRITE(33,195) FCOMPAC8
       END IF

       WRITE(33,62)
       WRITE(33,4301)
       
       IF ((FINAL .EQ. 2) .AND. (PRINTO(27) .EQ. 1)) THEN
       PREDL=1.0620+3.8052*ONDIAG3/ACTG+.0041*NUMTEACH+
     C .2711*NUMTEACH/ACTG-.1424*TFIXR
        RINUM=INUM
         RNSIM=NSIM
        RPRINTK=PRINTK
        RACTG=ACTG
        RMED=MEDDEPT
        RTOTCENT=TOTPACT
        RMADECH=MADECHOI 


      TTAIE=0
      TTAOE=0
      TTBIE=0
      TTBOE=0
      TTAIO=0
      TTAOO=0
      TTBIO=0
      TTBOO=0

      DO 3353 TG1=1,MAXDEPT
          G1=GORDER(TG1)

       TTAIE=TTAIE+ACMEANI(G1)
       TTAOE=TTAOE+ACMEANO(G1)
       TTBIE=TTBIE+BCMEANI(G1)
       TTBOE=TTBOE+BCMEANO(G1)
       TTAIO=TTAIO+AOBSCONI(G1)
       TTAOO=TTAOO+AOBSCONO(G1)
       TTBIO=TTBIO+BOBSCONI(G1)
       TTBOO=TTBOO+BOBSCONO(G1)
03353   CONTINUE

       CALL KFIT(NUMTEACH,TFITI,ODDSB)
C       WRITE(19,25144) KCOMPACT,STDHS,FCOMPAC2,FCOMPAC5,ONDIAG,
C     C RACTG,(ONDIAG/ACTG),
C     C TOTPACT,RACTG,(TOTPACT/ACTG),ONDIAG2,(ONDIAG2/ACTG),
C     C TOTPACT2,(TOTPACT2/ACTG),RINUM,
C     C FCOMPAC8,ONDIAG3,(ONDIAG3/ACTG),
C     C FCOMPAC9,(ONDIAG4/ACTG),RMED,RTOTCENT,XPC,RMADECH,
C     C CHNGSIM,CHNGCON,CHNGSTD,(APEARSON+BPEARSON),(ALRT+BLRT),
C     C STRESSA,STRESSB,STRESSC,STRESSD,
C     C STRESS2A,STRESS2B,STRESS2C,STRESS2D,
C     C BCHNGSIM,BCHNGCON,BCHNGSTD,RNSIM,RPRINTK,
C     C STRESS3A,STRESS3B,STRESS3C,STRESS3D,
C     C SAMPMEAN,SAMPSD,CSMEAN,CSSD,ZVAL,CZVAL,CPVAL,SPVAL,
C     C SAMPMEA2,SAMPSD2,CSMEAN2,CSSD2,ZVAL2,CZVAL2,CPVAL2,
C     C SPVAL2,PREDACC,PREDACC2,PREDL,(ANLRT+BNLRT),
C     C TTAIE,TTAOE,TTBIE,TTBOE,TTAIO,TTAOO,TTBIO,TTBOO,
C     C GLAMNDA,ODDSB,TWARPA,TWARPB,TWARPC,TWARPD
        OPEN(15,FILE='sampdist.dat')
C        CALL MOVEEND(15) 
        RNUMTCH=NUMTEACH
        IF (GLAMNDA .GT. 0) THEN
        WRITE(15,25145) (LOG(GLAMNDA)/2),GLAMNDA,RNUMTCH
        END IF
C        CLOSE(15)  


        END IF
       
       IF (PRINTO(15) .EQ. 1) THEN 
       WRITE(33,4308)
       WRITE(33,4308) 'You requested the logit analysis via'
       WRITE(33,4308) 'printo(15).  This feature has been suspended'
       WRITE(33,4308) 'and replaced with standard output -- '
       WRITE(33,4308) 'look for the Approximate LRT test.'
       PRINTO(15)=0
       END IF

       IF (PRINTO(15) .EQ. 1) THEN 
       WRITE(33,517)
       WRITE(33,4308)

       WRITE(33,517) 'LOGIT ANALYSIS'
       WRITE(33,4308)
       WRITE(33,4308) 'BELOW ARE REPORTED RESIDUALS FROM A '
       WRITE(33,4308) 'LOGIT ANALYSIS.  YOU WILL SEE FIVE COLUMNS'
       WRITE(33,4308) ' ASSOCIATED WITH EACH GROUP.'
       WRITE(33,4308) 'THE FIRST FOUR COLUMNS CORRESPOND TO THE CELLS'
       WRITE(33,4308) 'OF THE BOX BELOW:'
       WRITE(33,4308) 
       WRITE(33,4308) '                  CONNECTION'
       WRITE(33,4308) '                 NO        YES'
       WRITE(33,4308) '              ___________________'
       WRITE(33,4308) '              |        |        |'
       WRITE(33,4308) '           NO | OUTNOC | OUTCH  |'
       WRITE(33,4308) 'IN SAME       |        |        |'
       WRITE(33,4308) 'GROUP         |--------|--------|'
       WRITE(33,4308) '              |        |        |'
       WRITE(33,4308) '          YES | INNOC  | INCH   |'
       WRITE(33,4308) '              |        |        |'
       WRITE(33,4308) '              -------------------'
       WRITE(33,4308) 
       WRITE(33,4308) 'THUS, INCHI FOR GROUP 1'
       WRITE(33,4308) 'REPRESENTS THE SQUARED RESIDUAL ASSOCIATED'
       WRITE(33,4308) 'FOR CONNECTIONS MADE BY ACTORS IN GROUP 1'
       WRITE(33,4308) 'WITH ACTORS IN GROUP 1.'
       WRITE(33,4308)
       WRITE(33,4308) 'THE LOGIT MODEL FOR A SINGLE GROUP, G, WOULD BE:' 
       WRITE(33,4308) 'CONNECTION (1 OR 0) = B1*SAMEG + e'
       WRITE(33,4308) 

       WRITE(33,4308) 'THE LOGLINEAR MODEL FOR A SINGLE GROUP, G,'
       WRITE(33,4308) ' WOULD BE:' 
       WRITE(33,4308) 'COUNT (ACTUAL #) = B1*CONNECT + B2*SAMEG + e'
       WRITE(33,4308) 
       WRITE(33,4308) 'WHERE ACTOR I, THE INITIATOR, IS IN GROUP G'
       WRITE(33,4308) 
       WRITE(33,4308) 'AND'
       WRITE(33,4308) 'SAMEG =1 IF ACTOR J, THE OBJECT, IS IN GROUP G'
       WRITE(33,4308) 'SAMEG =0 IF ACTOR J IS NOT IN GROUP G'
       WRITE(33,4308) 
       WRITE(33,4308) 'CONNECT =1 IF ACTOR I AND ACTOR J ARE CONNECTED'
       WRITE(33,4308) 'CONNECT =0  OTHERWISE'
       WRITE(33,4308) 
       WRITE(33,4308) 'THE RESIDUALS CORRESPOND TO THE LOGLINEAR MODEL'
       WRITE(33,4308) 

       WRITE(33,4308) 'THE LAST COLUMN REPRESENTS THE SUM OF THE'
       WRITE(33,4308) 'PRECEEDING FOUR COLUMNS'

       WRITE(33,4308) 
       WRITE(33,517) 'SQUARED RESIDS'
       WRITE(33,517)
       WRITE(33,2517) 'GROUP','INCH','OUTCH','INNOC','OUTNOC','TOTCHI'



      TOTCHII=0.0000
      TOTCHIO=0.0000
      DO 334 TG1=1,MAXDEPT
       G1=GORDER(TG1)
       IF ((DEPARTN(G1) .GT. 1) .AND. (DEPARTN(G1) .LE. MAXGR)) THEN
       LCHISQR(G1)= ACHISQRI(G1)+ACHISQRO(G1)+BCHISQRI(G1)+
     C BCHISQRO(G1)
       WRITE(33,2301) G1,ACHISQRI(G1),ACHISQRO(G1),BCHISQRI(G1),
     C BCHISQRO(G1),LCHISQR(G1)
       TOTCHII=TOTCHII+ACHISQRI(G1)+BCHISQRI(G1)
       TOTCHIO=TOTCHIO+ACHISQRO(G1)+BCHISQRO(G1)
       END IF
  334 CONTINUE

       WRITE(33,517) 
       WRITE(33,517) 'SQUARE ROOT RESIDS'
       WRITE(33,2517) 'GROUP','INCH','OUTCH','INNOC','OUTNOC','TOTCHI'
      DO 3340 TG1=1,MAXDEPT
          G1=GORDER(TG1)
       IF ((DEPARTN(G1) .GT. 1) .AND. (DEPARTN(G1) .LE. MAXGR)) THEN
       WRITE(33,2301) G1, SQRT(ACHISQRI(G1)),
     C SQRT(ACHISQRO(G1)),SQRT(BCHISQRI(G1)),
     C SQRT(BCHISQRO(G1)),SQRT(LCHISQR(G1))
       END IF
 3340 CONTINUE

       WRITE(33,517) 
       WRITE(33,517) 'TOTALS'
      WRITE(33,4308)
      WRITE(33,2517) 'INCHI','OUTCHI','TOT','NORMSQ','KCHISQR'
      IF (FCOMPACT .GT. 0) THEN 
      WRITE(33,2518) TOTCHII,TOTCHIO,(TOTCHII+TOTCHIO),
     C FCOMPACT**2,KCHISQR
      END IF
      WRITE(33,4308)
      WRITE(33,4308) 'INCHI  = INCH  + INNOC'
      WRITE(33,4308) 'OUTCHI = OUTCH + OUTNOC'
      WRITE(33,4308) 'TOT    = INCHI + OUTCHI'
       WRITE(33,4308)  '********************************************'
       WRITE(33,4308) 'NOTE THAT TOT = THE CHI-SQUARE VALUE'
       WRITE(33,4308)  'ASSOCIATED WITH THE LOGIT OR LOGLINEAR MODELS'
       WRITE(33,4308)  'DESCRIBED ABOVE'
       WRITE(33,4308)  '********************************************'
      WRITE(33,4308) 'NORMSQ = COMPACTNESS * COMPACTNESS'
      WRITE(33,4308) 'KCHISQR = SUM OVER ALL GROUPS'
      WRITE(33,4308) '            COMPACTNESS(g)*COMPACTNESS(g)'
       WRITE(33,517) 

       WRITE(33,517) 'LRT'
      OPEN(52,file='glim.dat')
       WRITE(33,2517) 'GROUP','INCH','OUTCH','INNOC','OUTNOC','TOT*2',
     C  'LAMNDA'

      TOTLAMND=0
      
      DO 3343 TG1=1,MAXDEPT
          G1=GORDER(TG1)


       IF ((DEPARTN(G1) .GT. 1) .AND. (DEPARTN(G1) .LE. MAXGR)) THEN
       TAI=AOBSCONI(G1)/ACMEANI(G1)
       TAO=AOBSCONO(G1)/ACMEANO(G1)
       TBI=BOBSCONI(G1)/BCMEANI(G1)
       TBO=BOBSCONO(G1)/BCMEANO(G1)
       IF ((TAI .GT. 0) .AND. (TAO .GT. 0) .AND. 
     C (TBI .GT. 0) .AND. (TBO .GT. 0)) THEN
       XLAMNDA=       
     C 2*(ABS(AOBSCONI(G1))*LOG(TAI)+
     C ABS(AOBSCONO(G1))*LOG(TAO)+
     C ABS(BOBSCONI(G1))*LOG(TBI)+
     C ABS(BOBSCONO(G1))*LOG(TBO))
        
       TOTLAMND=TOTLAMND+XLAMNDA
       WRITE(33,2301) G1, 
     C ABS(AOBSCONI(G1))*LOG(TAI),
     C ABS(AOBSCONO(G1))*LOG(TAO),
     C ABS(BOBSCONI(G1))*LOG(TBI),
     C ABS(BOBSCONO(G1))*LOG(TBO),
     C XLAMNDA,LAMNDA(G1)
        END IF
       SAMEG=1
       WRITE(52,10251) G1,SAMEG,SAMEG*G1,AOBSCONI(G1),
     C (AOBSCONI(G1)+BOBSCONI(G1))
       SAMEG=0
       WRITE(52,10251) G1,SAMEG,SAMEG*G1,AOBSCONO(G1),
     C (BOBSCONO(G1)+AOBSCONO(G1))

       END IF
C       GARBAGE=9999999999
 3343 CONTINUE
       WRITE(33,2517) 'TOTAL'
       WRITE(33,2517) '*********','*********','*********','*********',
     C TOTLAMND
      CLOSE(52)


       WRITE(33,517) 'LRT OBJECTIVE FUNCTION'
       WRITE(33,2517) 'GROUP','INCH','OUTCH','INNOC','OUTNOC','TOT*2'
      TOTLAMND=0
      DO 7343 TG1=1,MAXDEPT
          G1=GORDER(TG1)

       IF ((DEPARTN(G1) .GT. 1) .AND. (DEPARTN(G1) .LE. MAXGR)) THEN
C       IF (DEPARTN(G1) .GT. 1) THEN
       TAI=AOBSCONI(G1)/ACMEANI(G1)
       TAO=AOBSCONO(G1)/ACMEANO(G1)
       TBI=BOBSCONI(G1)/BCMEANI(G1)
       TBO=BOBSCONO(G1)/BCMEANO(G1)
       IF ((TAI .GT. 0) .AND. (TAO .GT. 0) .AND. 
     C (TBI .GT. 0) .AND. (TBO .GT. 0)) THEN
       XLAMNDA=
     C ABS(2*(ABS(AOBSCONI(G1)*LOG(TAI))+
     C ABS(AOBSCONO(G1)*LOG(TAO))+
     C ABS(BOBSCONI(G1)*LOG(TBI))+
     C ABS(BOBSCONO(G1)*LOG(TBO))))
       TOTLAMND=TOTLAMND+XLAMNDA
       WRITE(33,2301) G1, 
     C ABS(AOBSCONI(G1)*LOG(TAI)),
     C ABS(AOBSCONO(G1)*LOG(TAO)),
     C ABS(BOBSCONI(G1)*LOG(TBI)),
     C ABS(BOBSCONO(G1)*LOG(TBO)),
     C XLAMNDA
         END IF
       END IF
C       GARBAGE=9999999999
 7343 CONTINUE
       WRITE(33,2517) 'TOTAL'
       WRITE(33,2517) '*********','*********','*********','*********',
     C TOTLAMND

       
       END IF
       END IF
00777  FORMAT(A)
01212  FORMAT(I5,I5,1X,I5)

00020  FORMAT(A33)
00220  FORMAT(A16)

00021  FORMAT(I5,2F10.5,4(I5,1X))
00804  FORMAT(I5,I5,1X,I1,1X,I5)
00803  FORMAT(A)

07474  FORMAT(A27,A12,A4,F10.5)
11221  FORMAT(I5,' MEDIATES BETWEEN ',I5,' AND ',I5)
08282  FORMAT(' THE LARGEST NUMBER',
     C  ' OF CONNECTIONS INITIATED BY ANY ACTOR IS ',F8.4,/,
     C  'WHICH IS ',A,
     C  'THE PRESPECIFIED MAXIMUM OF ',F8.4,' .',/,
     C  'THE',A,'WILL BE'
     C  ,' USED IN CALCULATING DENSITY MEASURES.')
07761   FORMAT(A12)
07760   FORMAT(A6,I2.2,A4)
09102   FORMAT(251(I4))
09103    FORMAT(A1,I3.3,A5)
09101   FORMAT(251(I4.4,1X))
07513 FORMAT(251('AC',I3.3,',',$))
07514  FORMAT ('AC',I3.3)
07511 FORMAT(251('GP',I3.3,','))
27511 FORMAT(I1,',',251(I3.3,','))
37511 FORMAT(251(I3.3,','))
07512 FORMAT(251('AC',I3.3,','))
21091 FORMAT(I1,',',I3,',',I3,',N,TM')
21092 FORMAT(I1,',',I3,',',I3,',N,NM')
04301 FORMAT(20(A))
94301 FORMAT(251(I4.1,1X))
04302 FORMAT(20(A,$))
04303 FORMAT('V',I3.3,',')
04304 FORMAT(') (',I3,'*#7)')
04358 FORMAT(A,F5.0,A,F5.0,A)
  
   62 FORMAT(I2)
00662 FORMAT(251(I3,1x))
 762  FORMAT(I1,$)
  512 FORMAT(3(A20,1X))
  513 FORMAT(5(A20,1X))
  517 FORMAT(10X,A40)
 2518 FORMAT(20(F10.2))
 2517 FORMAT(20(A10))
 2301 FORMAT(I9,1X,251(F9.2,1X))
  301 FORMAT(251(F7.2))
03311 FORMAT(I6,1X,10(25F7.4,/))

03308 FORMAT(A7,$)
04308 FORMAT(A)
07273 FORMAT(A,4F10.5)
    7 FORMAT('MATRIX OF WITHIN GROUP ASSOCIATIONS',/,
     C8X,A20,' ORDER')   
   77 FORMAT('MATRIX OF GROUP',A)
  102 FORMAT(I2,251(I1))
  105 FORMAT(251(I1))
02194 FORMAT(25(A10))
02195 FORMAT(A10,25(F10.3))
  193 FORMAT(/,A3,4(2X,A25),/)
  192 FORMAT(I3,6X,I10,6X,6X,I10,6X,12X,F10.5,6X,6X,F10.5,6X,/)
  191 FORMAT(/,'SIMILARITY BETWEEN THE START AND END GROUPS:   ACTUAL 
     C  POSS  STANDARDIZED',/,43X,F7.0,3X,F7.0,3X,F10.5)

03307 FORMAT(50(F7.2,$))
03301 FORMAT(I6,1X,10(25F7.2,/))
    8 FORMAT(10(25(A6,1X),/))
   10 FORMAT(A7,10(25(I6,1X),/))
 2302 FORMAT(A4,3X,10(25(I6,1X),/))
  194 FORMAT(/,10(2X,A15),/)
 1194 FORMAT(/,10(2X,A15),/)
  195 FORMAT(/,10(2X,G15.5),/) 
 8195 FORMAT(/,10(2X,G50.5),/) 
01954 FORMAT(/,3I15,10(2X,F15.5),/)   


  302 FORMAT(A4,1X,251(F5.2,1X))

  103 FORMAT(251(F7.3))
04404 FORMAT(251(F7.4))
07103 FORMAT(BZ,251(F7.3,1X),BN)
    9 FORMAT(/,'THE CURRENT COMPACTNESS IS',F10.5)
  101 FORMAT(I3,251(I1))
  251 FORMAT(25(G10.5)) 
10251 FORMAT(25I10)
44144 FORMAT(150(F15.5)) 
25145 FORMAT(150(F30.10)) 
   
      RETURN
      END
