
       SUBROUTINE PROBS (MAXGROUP,NUMTEACH,DEPARTN,PAGB,
     C NEWDEPT,RCHOICE,WHOLEGRP,INPER,INGROUP2,MBI)
      INCLUDE 'PARAM.H'

       INTEGER I,J,PERS,GROUP,IER,MBI,IER2,MAXDEPT

       INTEGER  MAXGROUP,NUMTEACH,DEPARTN(MAXKLIQ),
     C  RCHOICE(MAXKLIQ),NEWDEPT(MAXKLIQ),THISN,
     C  WHOLEGRP,BEGPER,ENDPER,BEGGRP,ENDGRP,INGROUP2,INPER,
     C NEWNUM,TARGET,OUTCON(MAXKLIQ),G,REMCH,NODO
       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF


       REAL*4 PAGB(MAXKLIQ,MAXKLIQ),TOTNUM(MAXKLIQ)

       REAL PK,PS,KTHETA,NUMCHOIC,INGROUP,OSLOTS,RTHISN,
     C GCONN(MAXKLIQ),TCONN,TSLOTS,TCONN2,GCONN2(MAXKLIQ),
     C KTHETA2,TTHETA,PK2,PS2,INCM,
     C TOTP(MAXKLIQ),KTHETA3,THETA1(MAXKLIQ),THETA2(MAXKLIQ),
     C G1,G2,ACHOICE(MAXKLIQ,MAXKLIQ),TCHOICE(MAXKLIQ)

       DOUBLE PRECISION PEQK,PLEK,PEQK2,PLEK2
      MAXDEPT=MAXGROUP
      MBI=MBI+1
      INGROUP=0.000
      NUMCHOIC=0.000
      DO 4 I=1,NUMTEACH
      TCHOICE(I)=0
      TOTP(I)=0
      DO 5 J=1,MAXGROUP
       ACHOICE(I,J)=0
00005  CONTINUE
00004   CONTINUE

       OSLOTS=0.000
      DO 11 J=1,MAXGROUP
      GCONN(J)=0.000
      GCONN2(J)=0.000
00011 CONTINUE

 
      DO 2 I =1, NUMTEACH
       DO 3 J=1, NUMTEACH
        IF (NEWMAT(I,J) .GE. 1) THEN 
          NUMCHOIC=NUMCHOIC+NEWMAT(I,J)
          GCONN2(NEWDEPT(I))=GCONN2(NEWDEPT(I))+NEWMAT(I,J)
          GCONN2(NEWDEPT(J))=GCONN2(NEWDEPT(J))+NEWMAT(I,J)

          TCHOICE(I)=TCHOICE(I)+NEWMAT(I,J)
          TCHOICE(J)=TCHOICE(J)+NEWMAT(I,J)
          ACHOICE(I,NEWDEPT(J))=ACHOICE(I,NEWDEPT(J))+NEWMAT(I,J)
          ACHOICE(J,NEWDEPT(I))=ACHOICE(J,NEWDEPT(I))+NEWMAT(I,J)
          IF  (NEWDEPT(I) .EQ. NEWDEPT(J)) THEN
           INGROUP=INGROUP+1
          GCONN(NEWDEPT(I))=GCONN(NEWDEPT(I))+NEWMAT(I,J)
          END IF
        END IF
00003   CONTINUE
00002  CONTINUE
C          INCM=INGROUP*(NUMTEACH-1)*NUMTEACH/(NUMCHOIC*OSLOTS)


        DO 08 J=1,MAXDEPT
        THETA1(J)=2*GCONN(J)/GCONN2(J)
        THETA2(J)=(GCONN2(J)-2*GCONN(J))/(NUMCHOIC-GCONN(J))
00008    CONTINUE
        DO 09 I=1,NUMTEACH
        DO 10 G=1,MAXDEPT
        IF ((DEPARTN(G) .LT. 1) .OR. 
     C  ((DEPARTN(G) .EQ. 1) .AND. (NEWDEPT(I) .EQ. G))) THEN
        PAGB(I,G)=0.000
        ELSE
        NODO=0
        REMCH=TCHOICE(I)-ACHOICE(I,G)
        IF (ACHOICE(I,G) .LE. 0) THEN 
        G1=0
        G2=1
        NODO=1
        END IF
        IF ((NODO .EQ. 0) .AND. (REMCH .LE. 0)) THEN 
        G1=1
        G2=0
        NODO=1
        END IF
        IF (NODO .EQ. 0) THEN
        G1=DEPARTN(G)*(THETA1(G)**ACHOICE(I,G)) *  
     C  (1-THETA1(G))**(TCHOICE(I)-ACHOICE(I,G))

        G2=(NUMTEACH-DEPARTN(G))*
     C   (THETA2(G)**ACHOICE(I,G)) *  
     C  (1-THETA2(G))**(TCHOICE(I)-ACHOICE(I,G))
         END IF
        PAGB(I,G)=G1/(G1+G2)
        IF ((PAGB(I,G) .GE. 0 ) .AND. (PAGB(I,G) .LT. 999999)) THEN
        HAPPY=1
        ELSE
        PAGB(I,G)=0.000
        END IF
   
        TOTP(I)=TOTP(I)+PAGB(I,G)
        END IF
00010    CONTINUE
00009     CONTINUE

         DO 13 I=1,NUMTEACH
         DO 12 J=1,MAXDEPT
          
          PAGB(I,J)=PAGB(I,J)/TOTP(I)
00012      CONTINUE
00013       CONTINUE
         RETURN
         END
