              
    

C      
C
C     SUBROUTINE FOR RANDOMLY ASSIGNING ACTORS TO GROUPS
      SUBROUTINE RANDASSG (ELEMENTS,NUMELEM,RSEED,NUMGROUP)
      INCLUDE 'PARAM.H'
      INTEGER ELEMENTS(MAXKLIQ),NUMELEM,FAKETCH,NUMGROUP
      INTEGER OELEMENT(MAXKLIQ),Z,J,K,I,CONVERT(MAXKLIQ),RITER
      DOUBLE PRECISION RSEED
      INTEGER RANDARRY(MAXKLIQ),OLDPOS(MAXKLIQ),D,PERGROUP
C
C   NOW THE RANDARRY IS AN ARRAY OF RANDOM NUMBERS OF LENGTH NUMELEM
C
      PERGROUP=3
      D=1

      DO 2 I=1,NUMGROUP
       DO 3 J=1,PERGROUP
       ELEMENTS(D)=I
       D=D+1
    3 CONTINUE
    2 CONTINUE

      DO WHILE (D .LE. NUMELEM)
      ELEMENTS(D)=99
      D=D+1
      END DO

C   

      DO 4 K=1,NUMELEM
      OELEMENT(K)=ELEMENTS(K)
    4 CONTINUE
      FAKETCH=NUMELEM
      CALL GGPER(RSEED,FAKETCH,RANDARRY)
      DO 5 Z=1,NUMELEM
      IF (OELEMENT(RANDARRY(Z)) .EQ. 99) THEN
      OELEMENT(RANDARRY(Z)) = 0
      END IF
      ELEMENTS(Z)=OELEMENT(RANDARRY(Z))
      
      WRITE(18,219) Z,RANDARRY(Z),OELEMENT(Z),ELEMENTS(Z)
    5 CONTINUE
  219 FORMAT(I3,1X,I5,1X,I5,1X,I3)
      RETURN
      END
