C      END SUBROUTINE REMOVEO2

      SUBROUTINE REMOVEO4(MAXDEPT,DEPARTN,LGROUP,LOWVAL,I,QUICKEND)
      INCLUDE 'PARAM.H'
       INTEGER MAXDEPT,DEPARTN(MAXKLIQ),I,J,K,LGROUP(MAXKLIQ),LOWVAL,
     C  LASTLIST(MAXKLIQ),LL,LK,QUICKEND
      IF (QUICKEND .EQ. 1) THEN
      DO 99 I=1,MAXDEPT
      LGROUP(I)=I
00099  CONTINUE
      ELSE
      I=1
      LL=1
      TMAXDEPT=MAXDEPT
      DO 00027 K=1,TMAXDEPT
       IF (DEPARTN(K) .GT. LOWVAL)  THEN
        LGROUP(K)=I
        I =I + 1
       END IF
       IF ((DEPARTN(K) .EQ. LOWVAL) .AND. (LOWVAL .GT. 0) ) THEN
        LASTLIST(LL)=K
        LL=LL+1
       END IF
       IF (DEPARTN(K) .EQ. 0) THEN
        LGROUP(K)=MAXDEPT+1
        END IF
00027    CONTINUE
        I=I-1
        DO 00028 LK=1,(LL-1)
         LGROUP(LASTLIST(LK))=I+LK
00028     CONTINUE
        MAXDEPT=I+LL
        LGROUP(MAXDEPT)=MAXDEPT
       END IF
      RETURN
C
      END
