C      END SUBROUTINE REMOVEO
C

C        CALL REMOVEO2(LMAXDEPT,DEPARTN,LGROUP,1)

      SUBROUTINE REMOVEO2(MAXDEPT,DEPARTN,LGROUP,LOWVAL,QUICKEND)
      INCLUDE 'PARAM.H'
       INTEGER MAXDEPT,DEPARTN(MAXKLIQ),I,J,K,LGROUP(MAXKLIQ),
     C LOWVAL,QUICKEND

      I=1
      DO 00027 K=1,MAXDEPT
       IF (DEPARTN(K) .GT. LOWVAL)  THEN
        LGROUP(I)=K
        I =I + 1
       END IF
00027    CONTINUE
        MAXDEPT=I-1
      RETURN
      END
