C      END FUNCTION ISOGROUP
C
C

C     SUBROUTINE FOR RESTORTING ELEMENTS OF GROUP LIST
      SUBROUTINE RESORTO (ELEMENTS,NUMELEM,RSEED)
      INCLUDE 'PARAM.H'
      INTEGER ELEMENTS(MAXKLIQ),NUMELEM,FAKETCH
      INTEGER OELEMENT(MAXKLIQ),Z,J,K,I,CONVERT(MAXKLIQ),RITER
      DOUBLE PRECISION RSEED
      INTEGER RANDARRY(MAXKLIQ),OLDPOS(MAXKLIQ),TRUENUM
C
C   NOW THE RANDARRY IS AN ARRAY OF RANDOM NUMBERS OF LENGTH NUMELEM
C
      TRUENUM=1
      DO 3 K=1,NUMELEM
      IF (ELEMENTS(K) .GE. 1) THEN
      OELEMENT(TRUENUM)=ELEMENTS(TRUENUM)
      TRUENUM=TRUENUM+1
       END IF       
    3 CONTINUE
       TRUENUM=TRUENUM-1
      FAKETCH=NUMELEM
      CALL GGPER(RSEED,TRUENUM,RANDARRY)

      DO 4 Z=1,TRUENUM
      ELEMENTS(Z)=OELEMENT(RANDARRY(Z))
C      WRITE(18,219) Z,RANDARRY(Z),OELEMENT(Z),ELEMENTS(Z)
    4 CONTINUE
  219 FORMAT(I3,1X,I5,1X,I5,1X,I3)
      RETURN
      END
