    
        SUBROUTINE SAMPDIST(NUMTEACH,MAXCONN,SAMPMEAN,SAMPSD,CSMEAN,
     C   CSSD,ACTVAL,ZVAL,PVAL,CZVAL,CPVAL,PREDACC)
        INTEGER NUMTEACH,MAXCONN

        REAL SAMPMEAN,SAMPSD,CSMEAN,CSSD,ACTVAL,PVAL,ZVAL,CZVAL,CPVAL,
     C  TN,TM,PREDACC

        LOGICAL UPPER

        TN=NUMTEACH-66.51515
        TM=MAXCONN-9.30303
        SAMPMEAN=14.3463+.1881*TN-.2519*TM
        IF ((NUMTEACH .GE. 20) .AND. (NUMTEACH .LE. 80)) THEN
        SAMPMEAN=SAMPMEAN -.000414*TN**2
        IF ((MAXCONN .GE. 3) .AND. (MAXCONN .LE. 12)) THEN 
        SAMPMEAN=SAMPMEAN -.00946*TN*TM
        END IF
        END IF
        IF ((MAXCONN .GE. 3) .AND. (MAXCONN .LE. 12)) THEN 
         SAMPMEAN=SAMPMEAN + .008706*TM**2
        END IF
        SAMPSD=.91109+.00975*TN-.011579*TM
        ZVAL=(ACTVAL-SAMPMEAN)/SAMPSD
        UPPER=.FALSE.
        PVAL=ALNORM(ZVAL,UPPER)
        CSMEAN=SAMPMEAN+2*.319
        CSSD=SAMPSD+2*.0911
        CZVAL=(ACTVAL-CSMEAN)/CSSD
        UPPER=.FALSE.
        CPVAL=ALNORM(CZVAL,UPPER)
        PREDACC=.4572-.000176*TN -.00419*TM+.029787*ZVAL
        RETURN
        END 
