     

       SUBROUTINE SASCENT (CHANGEC,STOPVAL,LOWMEM,NUMTEACH,
     C MADECHNG,ISO,ISOLIST,NEWDEPT,MEANWT,VARWT,WPIK,
     C NEARVAL,DEPARTN,MAXDEPT,
     C RCHOICE,DMEMBERS,QUITIT,LASTCHNG,NSUBID,
     C ATITLE,MKCOUNT2,PRINTO,BOUNDVAL,PCTILE,
     C DIRECT,TWXPX,DSYMMAT,STARTTRY,IEXPECT,ISTD,ICON,
     C ACTRSQR,NOWCLOSE,STRUCTEQ,QUICKEND,ROWWT,COLWT,TQUANT,
     C SQUAREIT,SOLUT,NETLEV,PERGROUP,INFILE,BLABOUND,MAXCH,MUTDYAD,
     C NONEG,MAXSEED,ATTACHI,HALFDYAD,DISSOLVE,HYPERG)

      INCLUDE 'PARAM.H'

      CHARACTER ATITLE(3)*20, IHEAD(4)*30,INFILE*16
      REAL IEXPECT(MAXKLIQ),ISTD(MAXKLIQ),ICON(MAXKLIQ),
     C MEANWT(MAXKLIQ),VARWT(MAXKLIQ),WPIK,NOB,
     C ROWWT,COLWT,FINEVAL,DVAL

      INTEGER LOOKP
      DOUBLE PRECISION SUMCLOSE
      
      REAL CHOSEMN(MAXKLIQ),ONEARVAL,SS(MAXKLIQ,MAXKLIQ),
     C CHOSEVR(MAXKLIQ),AMEAN,AVAR,SRIU2(MAXKLIQ),GMEAN(MAXKLIQ),
     C GVAR(MAXKLIQ),TOTE,TOTCON,TOTV,CURVAR(MAXKLIQ),CURMEAN(MAXKLIQ),
     C PLUSVAR(MAXKLIQ),PLUSMEAN(MAXKLIQ),OLDGZ(MAXKLIQ),
     C CHANGEZ,IADDCON,XNEWCON,NEWZ,TADDCON,
     C INDIVZ,IE,IVAR,KSIGN,BDENOM,TARGETR,DELTA5

      REAL CDEPT,NEARVAL,BESTD(MAXKLIQ),CHANGEC(MAXKLIQ),BOUNDVAL,
     C NOWCLOSE(MAXKLIQ),LOWCOMP,STOPVAL,LASTCHNG,
     C ORDCLOSE(MAXKLIQ),PCTILE,DIRECT,TWXPX,GPCTILE,GNEARVAL,
     C SYMMAT,LOWCONN,RBESTD(MAXKLIQ),
     C GROUPMAT(MAXKLIQ,MAXKLIQ),LOWNOW,PENALTY,PENNUM,
     C DIFF(MAXKLIQ,MAXKLIQ),SRI(MAXKLIQ),SSRI(MAXKLIQ),XSRI(MAXKLIQ),
     C KRATIO,KELGC,KNUMTEAC,XEXPECT,XICON,XISTD,USEBOUND,
     C GVPLUS(MAXKLIQ),GMPLUS(MAXKLIQ),GVSUB(MAXKLIQ),IVSUB(MAXKLIQ),
     C GMSUB(MAXKLIQ),IMSUB(MAXKLIQ),TOBFUN,TSS,WSS,WBSS,XNEARVAL,
     C TIDELTKA(MAXKLIQ),IDELTKA,IDELTKB,IDELTKC,IDELTMA,IDELTMB,
     C IDELTMC,IDELTVA,IDELTVB,IDELTVC,DTOTV,DTOTK,DTOTE,
     C TBLAUC,BLAUC(MAXKLIQ,MAXKLIQ),BLABOUND,
     C TEMPDEN,GCHOICE,NEXTPREF(MAXKLIQ),LONER,RPI,DUMBO,
     C TNEWCON,ADDCON,DMAXD,NOPRINT

C     C ALLC2(MAXKLIQ,MAXKLIQ),TOTPC(MAXKLIQ),PROBCON(MAXKLIQ,MAXKLIQ)
C
C        CALL KMULTMA3(ZCOMPMAT,ELGC,RCHOICE,DIRECT,TWXPX,DSYMMAT,
C     C ONLIST,1,PERSON1,PERSON2,ELGLIST,LOWMEM)

      INTEGER LOWMEM,NUMTEACH,ISO,ISOLIST(MAXKLIQ),NSUBID(MAXKLIQ),
     C DEPARTN(MAXKLIQ),NEWDEPT(MAXKLIQ),MAXDEPT,USESEED(MAXKLIQ),
     C MAXSEED,RCHOICE(MAXKLIQ),MADECHNG,B,HAVEISO,HYPERG,
     C Z,KCOUNT2,MKCOUNT2,PRINTO(100),NUMIN,ELGLIST(MAXKLIQ),ELGC,
     C ONLIST(MAXKLIQ),DONEO(MAXKLIQ),CONMEM,RP1,RP2,ACTRSQR,WANTSS,
     C SOLUT,UNO,NETLEV,KDEPT,PERGROUP,IAMELG(MAXKLIQ),
     C BBOUNDG(MAXKLIQ,MAXKLIQ),BCOUNTG(MAXKLIQ),IR,TCHOICE,GC,
     C DONEIT,PAIRUP(MAXKLIQ,MAXKLIQ),DISBAND(MAXKLIQ),TPAIR,
     C KGB,I,J,CHECK,FIXIT,P,P2,BLT,K1,K2,SAMEG1,CHANGEN,QUITIT,DSYMMAT

      INTEGER SKIPIT,DMEMBERS(MAXKLIQ),THISMEM,TEMPS,OLDLOWM,STRUCTEQ,
     C FOUNDONE,NEWMEMS(MAXKLIQ),OLDDEPT,LDEPART,LDEPTN,NGROUP,
     C THED(MAXKLIQ),NOPICK,DNUM(MAXKLIQ),OLOWMEM,INEWGRP(MAXKLIQ),
     C HALFDYAD,LGROUP(MAXKLIQ),LMAXDEPT,JB,IB,BD,BG,COUNTG(MAXKLIQ),
     C BOUNDG(MAXKLIQ,MAXKLIQ),
     C SLOTA(MAXKLIQ),THEVAL,PERSON1,PERSON2,CREATOG(MAXKLIQ),TRY,DOIT,
     C RESTART(MAXKLIQ),ATTACHL(MAXKLIQ),DIDIT,NOTYET,TPER,
     C SLOTB(MAXKLIQ),NEWONE,
     C STARTTRY,IH,NOWSTOP,CUTOFF,NEEDNEW,CINEWGRP(MAXKLIQ),
     C CCREATOG(MAXKLIQ),OLDCON(MAXKLIQ),NEWCON(MAXKLIQ,MAXKLIQ),
     C QUICKEND,CONTIN,HAVESEED,QUANTYPE,SQUAREIT,MAXCH,MUTDYAD,
     C HADTO,NONEG,TEMPCON,THISDEPT,CZ,BZ,ATTACHI,DPLUS1,DISSOLVE,
     C DS,THISND,NEXTTHED(MAXKLIQ),OTHER,TKC,ZDEPT(MAXKLIQ),
     C SORTFLAG,IER,TQUANT
         REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       INTEGER ALLGROUP(MAXKLIQ,MAXKLIQ),HUBERT(MAXKLIQ,MAXKLIQ),
     C RESULTM(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF
       DATA OLOWMEM/0/,CINEWGRP/MAXKLIQ*0/,CCREATOG/MAXKLIQ*0/
       DATA FINEVAL/0.0/,SRI/MAXKLIQ*0/,ZDEPT/MAXKLIQ*0/
       DATA GVSUB/MAXKLIQ*0/,IVSUB/MAXKLIQ*0/,GVAR/MAXKLIQ*0/
       DATA GMSUB/MAXKLIQ*0/,IMSUB/MAXKLIQ*0/,GMEAN/MAXKLIQ*0/
       DATA TIDELTKA/MAXKLIQ*0/,DTOTK/0/,DTOTE/0/,DTOTV/0/,TBLAUC/0/
       DATA HADTO/0/


C       WRITE(521,102) 'BEGINNING OF ASCENT'
C       WRITE(521,251) NEWMAT
        OPEN(20,file='obfun.dat')
        QUANTYPE=TQUANT
        BLT=0
        PENALTY=0
        IF (QUANTYPE .LT. 0) THEN
        QUANTYPE=ABS(QUANTYPE)
        BLT=1
        PENNUM=NUMTEACH*(NUMTEACH-1)
        PENALTY=-LOG(PENNUM)
        END IF 
        GPCTILE=PCTILE
        GNEARVAL=NEARVAL
         USEBOUND=NEARVAL
         TKC=MKCOUNT2
         LOWNOW=0
C        IF (QUANTYPE .EQ. 4) THEN
C         LOWNOW=-999
C        END IF

          IHEAD(1)=' ATTACHING ISOLATES'
          IHEAD(2)=' FINISHING ASCENT'
          IHEAD(3)=' FINAL PLACEMENTS'

       WRITE(33,03252) 
       WRITE(33,102) 'ASCENT'
       WRITE(33,2102) 

       DO 874 KGB=1,MAXDEPT
         INEWGRP(KGB)=0
         CREATOG(KGB)=0
  874  CONTINUE
         K1=0
         K2=0
        DO 00876 KGB=1,NUMTEACH
         K2=K2+RCHOICE(KGB)*MEANWT(KGB)
         USESEED(KGB)=0
         RESTART(KGB)=0
         IEXPECT(KGB)=0
         ICON(KGB)=0
         ISTD(KGB)=0
00876     CONTINUE
         K1=MAXCH*NUMTEACH*(NUMTEACH-1)-K2

C      IF (DEBUG(21) .EQ. 1) THEN 
C      IF (DEBUG(24) .EQ. 1) THEN

      TRY=1
        DO 717 I=1,NUMTEACH
        ATTACHL(I)=1
        DO 7173 GC=1,NUMTEACH
        PAIRUP(I,GC)=0
07173    CONTINUE
00717    CONTINUE

      ONEARVAL=NEARVAL
      NOB=1.00000
      IF (STRUCTEQ .EQ. 1) THEN
         TSS=0
         WANTSS=1
         DMAXD=1
         KDEPT=DEPARTN(1)
         DEPARTN(1)=NUMTEACH
      CALL GETMEAN(ATTACHL,NUMTEACH,GROUPMAT,MAXDEPT,
     C DEPARTN,WANTSS,SS,WSS,1.0,0.0)
          DEPARTN(1)=KDEPT
          DO 010 J=1,NUMTEACH
          TSS=TSS+SS(1,J)
00010      CONTINUE

           TOBFUN=1-WSS/TSS
       END IF

      DO WHILE (TRY .LE. STARTTRY)
      KCOUNT2=0
      MADECHNG=1
      OLDLOWM=0
      ISO=1
      ISOLIST(1)=0
      CONMEM=1
      LOWMEM=NUMTEACH+1 
      LOWCONN=200.000      
      CHANGEC(LOWMEM)=MAXKLIQ
      DIDIT=1
      NOWSTOP=0


      DO WHILE ((NOWSTOP .EQ. 0) .AND.
     C (KCOUNT2 .LT. MKCOUNT2) .AND. (DIDIT  .GT. 0))

      LASTCHNG=CHANGEC(LOWMEM)
      LOWCOMP=-200.000
      NOPRINT=0
      SUMCLOSE=0.0      
      NUMIN=0
      ELGC=1
      DIDIT=0

      WANTSS=0
      IF (PRINTO(23) .EQ. 1) THEN
      WANTSS=1
      END IF

      IF (STRUCTEQ .EQ. 1) THEN
      CALL GETMEAN(NEWDEPT,NUMTEACH,GROUPMAT,MAXDEPT,
     C DEPARTN,WANTSS,SS,WSS,ROWWT,COLWT)
      TOBFUN=1-WSS/TSS
      ELSE
C      SUBROUTINE GETRS(NEWMAT,NEWDEPT,NUMTEACH,MAXDEPT,
C     C DEPARTN,WANTSS,RCHOICE,SRI,SSRI,OLDCON,ALLGROUP,XSRI,
C     C MEANWT,VARWT,SRIU2,GMEAN,GVAR)

      CALL GETRS2(NEWDEPT,NUMTEACH,MAXDEPT,
     C DEPARTN,WANTSS,RCHOICE,SRI,SSRI,OLDCON,XSRI,
     C MEANWT,VARWT,SRIU2,GMEAN,GVAR,GVPLUS,GMPLUS,GVSUB,
     C IVSUB,GMSUB,IMSUB,DTOTK,DTOTE,DTOTV,TIDELTKA,QUANTYPE,
     C TOBFUN,SQUAREIT,NETLEV,PERGROUP,PRINTO(23),CURVAR,CURMEAN,
     C PLUSVAR,PLUSMEAN,OLDGZ,HYPERG,BLT,MAXCH,SAMEG1,K1,K2,
     C COLWT,ROWWT)
      END IF
       IF ((QUANTYPE .EQ. 5) .AND. (NETLEV .EQ. 1)) THEN
       LOWNOW=TOBFUN
       END IF 

         HAVESEED=0
      IF (MADECHNG .EQ. 1) THEN
      IF (PRINTO(23) .EQ. 1) THEN
      WRITE(33,89898) ' THE OBJECTIVE FUNCTION AT ITERATION',
     C KCOUNT2,  ' IS ',TOBFUN
      IF (PRINTO(24) .EQ. 1) THEN
      WRITE(6,89898) ' THE OBJECTIVE FUNCTION AT ITERATION',
     C KCOUNT2,  ' IS ',TOBFUN
      END IF
C      WRITE(6,89898) ' THE OBJECTIVE FUNCTION IS ',TOBFUN
      WRITE(20,251) KCOUNT2,TOBFUN
       END IF
       END IF

      DO 28, I=1,NUMTEACH
         IDELTMB=0
         NEXTPREF(I)=-999
         NEXTTHED(I)=NEWDEPT(I)
         IDELTVB=0
         IDELTKB=0

         IDELTMA=0
         IDELTVA=0
         IDELTKA=0
         SLOTB(I)=I
         SLOTA(I)=I
        J=NEWDEPT(I)
        IF (DEPARTN(J) .GT. 1) THEN
        NEWONE=0
        IDELTVA=GVSUB(J)-IVSUB(I)-GVAR(J)
        IDELTMA=GMSUB(J)-IMSUB(I)-GMEAN(J)
        IDELTKA=-TIDELTKA(I)

C       CALL DIFFCOMP(NEWMAT,I,J,NUMTEACH,NEWCON(I,J),
C     C DEPARTN(J),ACTRSQR,SSRI(J),SRI(J),OLDCON(J),
C     C ALLGROUP,RCHOICE(I),DIFF(I,J),NEWONE,GMEAN(J),GVAR(J),
C     C SRIU2(J),XSRI(J),MEANWT(I),VARWT(I),ROWWT,COLWT,QUANTYPE,
C     C SQUAREIT,IEXPECT(I),ICON(I),ISTD(I),(GVSUB(J)-IVSUB(I)),
C     C (GMSUB(J)-IMSUB(I)),IDELTKA,IDELTMA,IDELTVA,MAXCH)
       TESTTOT=DTOTV + IDELTVA + IDELTVB 
       IF (TESTTOT .GT. .00001) THEN
       NOWCLOSE(I)=TOBFUN - 
     C (DTOTK + IDELTKA+IDELTKB - DTOTE - IDELTMA - IDELTMB)/
     C  SQRT(DTOTV + IDELTVA + IDELTVB)
         END IF
C    C  (DTOTV + IDELTVA + IDELTVB)**.5

         END IF

       IF (DEPARTN(NEWDEPT(I)) .EQ. 1) THEN 
       NOWCLOSE(I)=LOWNOW+PENALTY
         IF (RESTART(I) .EQ. 0) THEN
         HAVESEED=1
         END IF
       END IF
       IF (ATTACHL(I) .EQ. 1) THEN
        DIDIT=DIDIT+1
       SKIPIT=0
C       WRITE(214,251) MADECHNG
       IF (MADECHNG .EQ. 0 )THEN
         NOPRINT=1
         DO 18 CHECK=1,ISO
          IF ((ISOLIST(CHECK) .GT. 0) .AND.
     C (ISOLIST(CHECK) .LE. 251)) THEN
          NOWCLOSE(ISOLIST(CHECK))=LOWNOW
           END IF
          IF (I .EQ. ISOLIST(CHECK)) THEN
            SKIPIT=1
            DIDIT=DIDIT-1
          END IF
   18    CONTINUE
        ELSE
         DO 19 FIXIT=1,ISO
          ISOLIST(FIXIT)=0
   19    CONTINUE
         ISO=1
       END IF
       IF (SKIPIT .EQ. 0) THEN
       BESTD(I)=-100000.0
       THED(I)=NEWDEPT(I)
      DO 34 J=1,MAXDEPT
       TCHOICE=RCHOICE(I)+SRI(J)
       IF ((TRY .EQ. 1) .OR. (DEPARTN(J) .GE. 1)) THEN
         CHOSEMN(J)=0.000
         CHOSEVR(J)=0.00
         TPAIR=1
         IF (ALLGROUP(J,1) .GT. 0) THEN
         TPAIR=ALLGROUP(J,1)
         END IF
                IF (((TRY .NE. 2) .AND.
     C   (((RCHOICE(I) .EQ. 0) .AND. (DEPARTN(J) .LT. 2) .AND.
     C      (MUTDYAD .EQ. 1) .AND. (TRY .NE. 2)) .OR.
     C   ((RCHOICE(I) .EQ. 0) .AND. (DEPARTN(J) .LT. 2) .AND.
     C    (PAIRUP(I,TPAIR) .EQ. 1)) .OR.
     C ((RCHOICE(TPAIR) .EQ. 0) .AND. (DEPARTN(J) .LT. 2) .AND.
     C    (PAIRUP(TPAIR,I) .EQ. 1)))) .OR.
     C    (((J .EQ. NEWDEPT(I)) .AND. (DEPARTN(NEWDEPT(I)) .EQ. 1)))
     C   .OR. (DEPARTN(J) .LT. 1) .OR. (TCHOICE .LE. 0))
     C    THEN
     
C       IF (((TRY .NE. 2) .AND.
C     C   (((RCHOICE(I) .EQ. 0) .AND. (DEPARTN(J) .LT. 2) .AND.
C     C      (MUTDYAD .EQ. 1) .AND. (TRY .NE. 2)) .OR.
C     C   ((RCHOICE(I) .EQ. 0) .AND. (DEPARTN(J) .LT. 2) .AND.
C     C    (PAIRUP(I,ALLGROUP(J,1)) .EQ. 1)) .OR.
C     C ((RCHOICE(ALLGROUP(J,1)) .EQ. 0) .AND. (DEPARTN(J) .LT. 2) .AND.
C     C    (PAIRUP(ALLGROUP(J,1),I) .EQ. 1)))) .OR.
C     C    (((J .EQ. NEWDEPT(I)) .AND. (DEPARTN(NEWDEPT(I)) .EQ. 1)))
C     C   .OR. (DEPARTN(J) .LT. 1) .OR. (TCHOICE .LE. 0))
C     C    THEN
     
         CDEPT=-MAXKLIQ
         IF (RESTART(I) .EQ. 0) THEN
         HAVESEED=1
         END IF
         IF (J .EQ. NEWDEPT(I)) THEN
          NOWCLOSE(I)=LOWNOW+PENALTY
         END IF
       ELSE
     
       IF (STRUCTEQ .EQ. 1) THEN
C      SUBROUTINE DIFFMEAN(I,GROUPMAT,G,NUMTEACH,DIFF,THISN,
C     C ACTRSQR,TSS,MAXDEPT,ROWWT,COLWT,THISD,NEWDEPT)

       CALL DIFFMEAN(I,GROUPMAT,J,NUMTEACH,DIFF(I,J),
     C DEPARTN(J),ACTRSQR,TSS,MAXDEPT,ROWWT,COLWT,ZDEPT)
       ELSE
       NEWONE=1
C       SUBROUTINE DIFFCOMP(NEWMAT,I,J,NUMTEACH,NEWCON,
C     C DEPARTN,ACTRSQR,SSRI,SRI,OLDCON,ALLGROUP,
C     C RCHOICE,CONNECT,NEWONE,GMEAN,GVAR,SRIU2,XSRI,THISMW,
C     C THISVW)
       IF (NETLEV .NE. 2) THEN
       CALL DIFFCOMP(I,J,NUMTEACH,NEWCON(I,J),
     C DEPARTN(J),ACTRSQR,SSRI(J),SRI(J),OLDCON(J),
     C RCHOICE(I),DIFF(I,J),NEWONE,GMEAN(J),GVAR(J),
     C SRIU2(J),XSRI(J),MEANWT(I),VARWT(I),ROWWT,COLWT,QUANTYPE,
     C SQUAREIT,XEXPECT,XICON,XISTD,GVPLUS(J),GMPLUS(J),IDELTKB,
     C IDELTMB,IDELTVB,PERGROUP,TBLAUC,DISBAND(I),HYPERG,MAXCH)
       
       BLAUC(I,J)=TBLAUC
       END IF
C       NETLEV .NE. 2

       END IF

C  NETLEV .EQ. 2 IF NOT IN SAME GROUP
       IF (NETLEV .EQ. 2) THEN
        DIFF(I,J)=0.000
        CHANGEZ=0.0000
        IADDCON=0.000
        XNEWCON=0.000
         NEWZ=0.0000
        DO 9889 P=1,DEPARTN(J)
         NEWZ=0.0000
        THISMEM=ALLGROUP(J,P)
        IF (RCHOICE(THISMEM) .GT. 0.000) THEN
        IADDCON=IADDCON + NEWMAT(I,THISMEM)
        TADDCON=NEWMAT(THISMEM,I)
         XNEWCON=XNEWCON+TADDCON

        
        IF ((QUANTYPE .EQ. 1) .AND. (PLUSVAR(THISMEM) .GT. 0.000))
     C   THEN
        NEWZ=((TIDELTKA(THISMEM)+TADDCON)-PLUSMEAN(THISMEM)) /
     C              (PLUSVAR(THISMEM)**.5)
        END IF        
        IF ((QUANTYPE .EQ. 2) .AND. (PLUSMEAN(THISMEM) .GT. 0)) THEN
        NEWZ=((TIDELTKA(THISMEM)+TADDCON)-PLUSMEAN(THISMEM)) /
     C              (PLUSMEAN(THISMEM))**.5
        END IF
         IF (QUANTYPE .EQ. 3) THEN
         KSIGN=TADDCON/PLUSMEAN(THISMEM)
         IF (KSIGN .GT. 0) THEN
         NEWZ=2*TADDCON*LOG(KSIGN)
         END IF
         END IF
        CHANGEZ=CHANGEZ+NEWZ
        END IF
09889    CONTINUE
       INDIVZ=0.000
       IF (RCHOICE(I) .GT. 0)  THEN
       IE=MEANWT(I)*RCHOICE(I)*DEPARTN(J)/(NUMTEACH-1.)
       IVAR=(RCHOICE(I)*DEPARTN(J)*((NUMTEACH-1.)-DEPARTN(J))*
     C (MEANWT(I)**2/(NUMTEACH-1.)**2) *
     C  (1. + (NUMTEACH-1.)*VARWT(I)/((NUMTEACH-1.-DEPARTN(J))*
     C  MEANWT(I)**2) - HYPERG*((RCHOICE(I)-1.)/(NUMTEACH-2.))))
        IF ((QUANTYPE .EQ. 1) .AND. (IVAR .GT. 0)) THEN
        INDIVZ=(IADDCON-IE)/SQRT(IVAR)
         END IF
        IF ((QUANTYPE .EQ. 2) .AND. (IE .GT. 0)) THEN
        INDIVZ=(IADDCON-IE)/IE**.5
         END IF
         IF (QUANTYPE .EQ. 3) THEN
         KSIGN=IADDCON/IE
         IF (KSIGN .GT. 0) THEN
         INDIVZ=2*IADDCON*LOG(KSIGN)
         END IF
         END IF
   
         END IF
          IF (RCHOICE(I) .LT. DEPARTN(J)) THEN
           BDENOM=RCHOICE(I)
          ELSE
           BDENOM=DEPARTN(J)
          END IF

          BLAUC(I,J)=(COLWT*XNEWCON+ROWWT*IADDCON)/
     C     (BDENOM + DEPARTN(J))
         TEMPCON=XNEWCON+IADDCON
         DIFF(I,J)=(CHANGEZ+INDIVZ)-OLDGZ(J)
         IF (ABS(TEMPCON) .LT. .0001) THEN
         DIFF(I,J) =-999
         END IF
         END IF
C        IF NETLEV .EQ. 2
C  NETLEV .EQ. 2 IF NOT IN SAME GROUP

       IF (NETLEV .EQ. 1) THEN
        IF (QUANTYPE .EQ. 1) THEN
        DIFF(I,J)=-TOBFUN +
     C  (DTOTK + IDELTKA+IDELTKB - DTOTE - IDELTMA - IDELTMB)/
     C  (DTOTV + IDELTVA + IDELTVB)**.5
        END IF
        IF (QUANTYPE .EQ. 5) THEN
        DELTA5=IDELTKA+IDELTKB+DTOTK
        CHANGEN=(SAMEG1+2*MAXCH*(DEPARTN(J)-DEPARTN(NEWDEPT(I))+1))
     C   -DELTA5*COLWT
        IF (COLWT .LT. .0001) THEN
        DIFF(I,J)=DELTA5/CHANGEN
        ELSE
        DIFF(I,J)= DELTA5*(K1-CHANGEN)/((K2-DELTA5)*CHANGEN)
        END IF
        END IF
        IF (ABS(XICON) .LT. .0001) THEN
        DIFF(I,J)=-999
        END IF
       END IF
        IF ((DEPARTN(NEWDEPT(I)) .LT. 2) .AND. (BLT .EQ. 1)) THEN
         DIFF(I,J)=DIFF(I,J)-PENALTY
        END IF

        IF (DEPARTN(J) .EQ. 1) THEN
        IF (HALFDYAD .EQ. 1) THEN
        DIFF(I,J)=DIFF(I,J)/2.
        END IF
        IF (HALFDYAD .EQ. 2) THEN
        DIFF(I,J)=-999
        END IF
        END IF
   
         CDEPT=DIFF(I,J)
       IF ((J .NE. NEWDEPT(I)) .AND. (CDEPT .GT. NEXTPREF(I))) THEN
       NEXTPREF(I)=CDEPT
       NEXTTHED(I)=J
       END IF

        IF (J .EQ. NEWDEPT(I)) THEN
        IF (DEPARTN(J) .GT. 1) THEN
        IF (STRUCTEQ .EQ. 1) THEN
       CALL LMEAN(NEWDEPT,NUMTEACH,GROUPMAT,MAXDEPT,
     C DEPARTN,I,DIFF(I,J),ACTRSQR,TSS,ROWWT,COLWT,ZDEPT)
       ELSE
C  NETLEV 2 FOR SAME GROUP
       IF (NETLEV .EQ. 2) THEN
        CHANGEZ=0.000
        XNEWCON=0.000
        IF (DEPARTN(J) .GT. 2) THEN
        DO 9887 P=1,DEPARTN(J)
        THISMEM=ALLGROUP(J,P)
        IF ((RCHOICE(THISMEM) .GT. 0) .AND. (THISMEM .NE. I)) THEN
        ADDCON=NEWMAT(THISMEM,I)
         XNEWCON=XNEWCON+ADDCON
        NEWZ=0.000
        IF ( (QUANTYPE .EQ. 1) .AND. (IVSUB(THISMEM) .GT. 0)) THEN
        NEWZ=((TIDELTKA(THISMEM)-ADDCON)-IMSUB(THISMEM)) /
     C              (IVSUB(THISMEM)**.5)
        END IF
        IF ( (QUANTYPE .EQ. 2) .AND. (IMSUB(THISMEM) .GT. 0)) THEN
        NEWZ=((TIDELTKA(THISMEM)-ADDCON)-IMSUB(THISMEM)) /
     C              (IMSUB(THISMEM)**.5)
        END IF      
         IF (QUANTYPE .EQ. 3) THEN
         KSIGN=(TIDELTKA(THISMEM)-ADDCON)/IMSUB(THISMEM)
         IF (KSIGN .GT. 0) THEN
         NEWZ=2*(TIDELTKA(THISMEM)-ADDCON)*LOG(KSIGN)
         END IF
         END IF
        CHANGEZ=CHANGEZ+(NEWZ)
         END IF
09887    CONTINUE

         END IF
C         IF (DEPARTN(J) .GT. 2) THEN

         INDIVZ=0.000
         IF ((RCHOICE(I) .GT. 0) .AND. (CURVAR(I) .GT. 0)) THEN
         INDIVZ=(TIDELTKA(I)-CURMEAN(I))/SQRT(CURVAR(I))
         END IF
         DIFF(I,J)=OLDGZ(J) -(CHANGEZ)
         IF (DEPARTN(J) .EQ. 2) THEN
         IF (ALLGROUP(J,1) .EQ. I) THEN
         XNEWCON=NEWMAT(ALLGROUP(J,2),I)
          ELSE
         XNEWCON=NEWMAT(ALLGROUP(J,1),I)
         END IF
          END IF
          
         TNEWCON=XNEWCON+TIDELTKA(I)
         IF (ABS(TNEWCON) .LT. .0001) THEN
         DIFF(I,J)=-999
         END IF

          TEMPDEN=DEPARTN(J) - 1.
          IF (RCHOICE(I) .LT. TEMPDEN) THEN
           BDENOM=RCHOICE(I)
          ELSE
           BDENOM=TEMPDEN
          END IF
          TBLAUC=(COLWT*XNEWCON+ROWWT*TIDELTKA(I))/
     C                    (BDENOM + TEMPDEN)
         END IF
C       IF (NETLEV .EQ. 2) THEN
C  NETLEV 2 FOR SAME GROUP

       IF (NETLEV .EQ. 1) THEN
        IDELTKA=-TIDELTKA(I)
        IF (QUANTYPE .EQ. 1) THEN
        IDELTVA=GVSUB(J)-IVSUB(I)-GVAR(J)
        IDELTMA=GMSUB(J)-IMSUB(I)-GMEAN(J)
        DIFF(I,J)=TOBFUN - (DTOTK + IDELTKA - DTOTE - IDELTMA)/
     C  (DTOTV + IDELTVA)**.5
        END IF
        IF (QUANTYPE .EQ. 5) THEN
        DIFF(I,J)=TOBFUN
C        DELTA5=IDELTKA+DTOTK
C        CHANGEN=SAMEG1-2*(DEPARTN(NEWDEPT(I))-1)-DELTA5
C        DIFF(I,J)=TOBFUN-
C     C  DELTA5*(K1-CHANGEN)/((K2-DELTA5)*CHANGEN)
        END IF
        IF (ABS(IDELTKA) .LT. .0001) THEN
         DIFF(I,J)=-999
        END IF
          TEMPDEN=DEPARTN(J) - 1.
          IF (RCHOICE(I) .LT. TEMPDEN) THEN
           BDENOM=RCHOICE(I)
          ELSE
           BDENOM=TEMPDEN
          END IF
          TBLAUC=(TIDELTKA(I))/
     C                    (BDENOM + TEMPDEN)
C       TBLAUC TO HERE

       ELSE
        NEWONE=0
       IF (NETLEV .NE. 2) THEN
         DISBAND(I)=0
       CALL DIFFCOMP(I,J,NUMTEACH,NEWCON(I,J),
     C DEPARTN(J),ACTRSQR,SSRI(J),SRI(J),OLDCON(J),
     C RCHOICE(I),DIFF(I,J),NEWONE,GMEAN(J),GVAR(J),
     C SRIU2(J),XSRI(J),MEANWT(I),VARWT(I),ROWWT,COLWT,QUANTYPE,
     C SQUAREIT,IEXPECT(I),ICON(I),ISTD(I),(GVSUB(J)-IVSUB(I)),
     C (GMSUB(J)-IMSUB(I)),IDELTKA,IDELTMA,IDELTVA,PERGROUP,TBLAUC,
     C  DISBAND(I),HYPERG,MAXCH)
        END IF
C         NETLEV .NE. 2

        END IF
         END IF
        ELSE
         DIFF(I,J)=0.0

         IF (RESTART(I) .EQ. 0) THEN
         HAVESEED=1
         END IF
        END IF
        IF ((DIFF(I,J) .GT. 999999) .OR. (DIFF(I,J) .LT. -999999))
     C THEN
        DIFF(I,J) = 0.0000000
         END IF
        IF (DEPARTN(J) .EQ. 2) THEN
         IF (BLT .EQ. 1) THEN
         DIFF(I,J)=DIFF(I,J)+PENALTY
          END IF

        IF (HALFDYAD .EQ. 1) THEN
        DIFF(I,J)=DIFF(I,J)/2.
        END IF
        IF (HALFDYAD .EQ. 2) THEN
        DIFF(I,J)=-999
        END IF
        END IF

         CDEPT=DIFF(I,J)
         BLAUC(I,J)=TBLAUC
C         ALLC(I,J)=DIFF(I,J)
         NUMIN=NUMIN+1
         ORDCLOSE(NUMIN)=CDEPT
         NOWCLOSE(I)=CDEPT
         SUMCLOSE=SUMCLOSE+NOWCLOSE(I)
         IF (DEPARTN(NEWDEPT(I)) .LT. 2) THEN 
         SUMCLOSE=SUMCLOSE-NOWCLOSE(I)+PENALTY
          NUMIN=NUMIN-1
          NOWCLOSE(I)=LOWNOW+PENALTY
C          ALLC(I,J)=0.0
          BLAUC(I,J)=0.0
          DUMBO=0
         IF (RESTART(I) .EQ. 0) THEN
         HAVESEED=1
         END IF


         END IF
        END IF
        END IF
C        IF RHCOICE .GT. 0 AND DEPARTN .LT. 2
        IF ((CDEPT .GT. BESTD(I)) .AND. (CDEPT .LT. 999999)) THEN
         IF ((NETLEV .EQ. 1) .AND. (J .EQ. NEWDEPT(I)) .AND. 
     C   (QUANTYPE .NE. 5)) THEN
         DUMBO=0
         ELSE
         THED(I)=J
         BESTD(I)=CDEPT
         IF (DEPARTN(J) .GE. 2) THEN
         RBESTD(I)=CDEPT
         END IF
         END IF
C        NETLEV EQ 1
         END IF
C         CDEPT GT BESTD
         END IF
C          IF ((TRY .EQ. 1) .OR. (DEPARTN(J) .GT. 1)) THEN
   34 CONTINUE
       IF ((NETLEV .EQ. 1) .AND. (QUANTYPE .NE. 5)) THEN
       CHANGEC(I)=BESTD(I)
       ELSE
       CHANGEC(I)=BESTD(I)-NOWCLOSE(I)
        END IF
C       WRITE(212,251) I,CHANGEC(I),BESTD(I),NOWCLOSE(I),LOWCOMP,
C     C  THED(I),NEWDEPT(I)
C       IF (BESTD(I) .LT. LOWCONN) THEN
C       CONMEM=I
C       LOWCONN=BESTD(I)
C       END IF

       IF (CHANGEC(I) .GT. LOWCOMP) THEN
        LOWCOMP=CHANGEC(I)
        LOWMEM=I
       END IF
      END IF
      END IF
   28 CONTINUE

      SORTFLAG=2
      IF (NUMIN .GT. 1) THEN
      CALL SPSORT(ORDCLOSE,NUMIN,SLOTA,SORTFLAG,IER)
      END IF
      IF (PCTILE .LE. 1) THEN
        THEVAL=INT(PCTILE*NUMIN)
        IF (THEVAL .GE. 1) THEN
          NEARVAL=ORDCLOSE(THEVAL)
          FINEVAL=ORDCLOSE(NUMIN-THEVAL)
        END IF
      END IF
C      NEARVAL=SUMCLOSE/NUMIN
       XNEARVAL=.0001
       IF (NEARVAL .GT. XNEARVAL) THEN
       XNEARVAL=NEARVAL
       END IF
         DO 2228 I=1,NUMTEACH
         IAMELG(I)=0
       IF ((USESEED(I) .LT. MAXSEED) .AND. 
     C (RCHOICE(I) .GT. 0) .AND. ((NOWCLOSE(I) .LE. XNEARVAL) .OR. 
     C        (DEPARTN(NEWDEPT(I)) .LE. 1))) THEN
          ELGLIST(ELGC)=I
          ELGC=ELGC+1
          IAMELG(I)=1
         END IF
02228     CONTINUE
      ELGC=ELGC-1
C      CHECK HERE
       IF ((TRY .EQ. 2) .OR. 
     C ((TRY .GT. 1) .AND. (STRUCTEQ .EQ. 0))) THEN 
       NEARVAL=-999
       END IF
       IF ((QUANTYPE .EQ. 4) .AND. (TRY .EQ. 3)) THEN
       NEARVAL=0
       END IF

       KELGC=ELGC
       KNUMTEAC=NUMTEACH
      KRATIO=KELGC/KNUMTEAC
       KELGC=NUMTEACH-NUMIN
      CONTIN=0
      IF (((THED(LOWMEM) .EQ. NEWDEPT(LOWMEM)) .OR. 
     C     (CHANGEC(LOWMEM) .LE. STOPVAL)) .AND. 
     C  (KELGC .GE. 3) .AND. (HAVESEED .EQ. 1) .AND. (TRY .LE. 1))
     C  THEN 
C        BESTD(LOWMEM)=NEARVAL-.2
        CONTIN=1
      END IF

      IF ((CHANGEC(LOWMEM) .GT. STOPVAL) .OR. (CONTIN .EQ. 1) .OR.
     C (DEPARTN(NEWDEPT(LOWMEM)) .EQ. 1)) THEN
      OLDLOWM=LOWMEM       
        IF ((NOPRINT .EQ. 0) .AND. (PRINTO(1) .EQ. 1)) THEN
        WRITE(33,132)
       WRITE(33,2101) ' (N)    '
        DO 80 Z=1,MAXDEPT
          IF (DEPARTN(Z) .GT. 0) THEN
          WRITE(33,133) Z , (NSUBID(ALLGROUP(Z,P)) , P=1,DEPARTN(Z))
          WRITE(33,134) DEPARTN(Z),
     C         (NOWCLOSE(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,137) 'BEST G',
     C         (BESTD(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,2137) 'GROUP',
     C         (THED(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
         END IF
   80   CONTINUE
        END IF

        IF (QUICKEND .LT. 1) THEN



        IF (PRINTO(8) .EQ. 1) THEN
        WRITE(33,139) NSUBID(LOWMEM),NEWDEPT(LOWMEM),THED(LOWMEM)
        IF (CONTIN .EQ. 1) THEN
      WRITE(33,01349) NSUBID(LOWMEM),THED(LOWMEM),CHANGEC(LOWMEM)
       END IF
        END IF

C
C
C       NOW I HAVE FOUND THE BEST PERSON TO CHANGE (LOWMEM) AND THE 
C        BEST DEPARTMENT FOR THAT PERSON THED(LOWMEM)
C        AND THE DISTANCE TO THAT DEPARTMENT (BESTD(LOWMEM))
C        IS IT GOOD ENOUGH? 
C
C         MUTDYAD=0
         NOPICK=0
         TCHOICE=0
         IF (THED(LOWMEM) .GT. 0) THEN
       TCHOICE=RCHOICE(LOWMEM)+SRI(THED(LOWMEM))
         END IF 
      IF (TCHOICE .LE. 0) THEN
       NOPICK=1
       DUMBO=0
       END IF
      IF ((TRY .NE. 2) .AND. (MUTDYAD .EQ. 1)) THEN
      IF ((RCHOICE(LOWMEM) .EQ. 0) .AND. 
     C   (DEPARTN(THED(LOWMEM)) .LT. 2)) THEN
         NOPICK = 1
         DUMBO=0
      END IF
      IF ((DEPARTN(THED(LOWMEM)) .LT. 2)  .AND. 
     C    (RCHOICE(ALLGROUP(THED(LOWMEM),1)) .LT. 1)) THEN
       NOPICK=1
       DUMBO=0
      END IF
      END IF


C        IF ((QUANTYPE .NE. 5) .AND. 
      
        IF ((NOPICK .EQ. 1) .OR. (LOWMEM .LT. 1) .OR. 
     C (LOWMEM .EQ. OLOWMEM)) THEN
        MADECHNG=0
        ISOLIST(ISO)=LOWMEM
        IF (ISO .GE. MAXKLIQ) THEN
        KCOUNT2=MKCOUNT2+1
        END IF
        IF (ISO .LT. MAXKLIQ) THEN 
        ISO=ISO+1
        END IF
      ELSE
      IF ((BESTD(LOWMEM) .GT. NEARVAL) .AND. (CONTIN .EQ. 0)) THEN
C    .AND.  (CREATOG(NEWDEPT(LOWMEM)) .EQ. 0)) THEN
          NEEDNEW=0
          MADECHNG=1
          OLOWMEM=LOWMEM
          LONER=0
          OLDDEPT=NEWDEPT(LOWMEM)
          IF (OLDDEPT .GT. 0) THEN
        IF ((DISSOLVE .GT. 1) .AND. (DEPARTN(OLDDEPT) .LE. DISSOLVE))
     C     THEN
          DO 5844 DS=1,DEPARTN(OLDDEPT)
          OTHER= ALLGROUP(OLDDEPT,DS)
          IF (OTHER .NE. LOWMEM) THEN
          THISND=NEXTTHED(OTHER)
          IF ((PRINTO(23) .EQ. 1) .OR. (PRINTO(8) .EQ. 1)) THEN
          WRITE(33,5843) NSUBID(OTHER),THISND,OLDDEPT
          IF (PRINTO(24) .EQ. 1) THEN
          WRITE(6,5843) NSUBID(OTHER),THISND,OLDDEPT
          END IF
          END IF

          NEWDEPT(OTHER)=THISND
          DEPARTN(THISND)=DEPARTN(THISND)+1
          INEWGRP(THISND) = 0
          INEWGRP(THISND)=0
          CREATOG(THISND)=0
          END IF
05844      CONTINUE
         END IF
            END IF
C          LDEPART=NEWDEPT(LOWMEM)
           GCHOICE=0
           IF ((OLDDEPT .GT. 0) .AND. (LOWMEM .GT. 0)) THEN
           GCHOICE=SRI(OLDDEPT)-RCHOICE(LOWMEM)*MEANWT(LOWMEM)
           END IF
           DONEIT=0
          IF ((GCHOICE .LT. 1) .AND. (STRUCTEQ .EQ. 0)) THEN
          IF (OLDDEPT .GT. 0) THEN
          DO 2423 GC=1,DEPARTN(OLDDEPT)
          IF (ALLGROUP(OLDDEPT,GC) .GT. 0) THEN
          PAIRUP(ALLGROUP(OLDDEPT,GC),LOWMEM)=1
          END IF
          IF (ALLGROUP(OLDDEPT,GC) .NE. LOWMEM) THEN
           IF (DONEIT .EQ. 1) THEN
          MAXDEPT=MAXDEPT+1
          IF (ALLGROUP(OLDDEPT,GC) .GT. 0) THEN
          NEWDEPT(ALLGROUP(OLDDEPT,GC))=MAXDEPT
          END IF
          ELSE
          DONEIT =1
          END IF
          END IF
02423      CONTINUE
          END IF
          END IF
          IF (NEWDEPT(LOWMEM) .GT. 0) THEN
          LDEPTN=DEPARTN(NEWDEPT(LOWMEM))
          NEWDEPT(LOWMEM)=THED(LOWMEM)
          DEPARTN(THED(LOWMEM))=DEPARTN(THED(LOWMEM))+1
          END IF
          IF (OLDDEPT .GT. 0) THEN
          INEWGRP(OLDDEPT) = 0
          END IF
           IF (THED(LOWMEM) .GT. 0) THEN
          INEWGRP(THED(LOWMEM))=0
          CREATOG(THED(LOWMEM))=0
          END IF
         ELSE 
        IF ((PRINTO(8) .EQ. 1) .AND. (CONTIN .EQ. 0)) THEN
         WRITE(33,2339) NSUBID(LOWMEM),BESTD(LOWMEM),
     C   THED(LOWMEM),NEARVAL
        END IF

         IF (TRY .LE. 1) THEN 
         NOTYET=0
         IF (ELGC .GT. 0) THEN
         SORTFLAG=2
         IF (NUMTEACH .GT. 1) THEN
         CALL SPSORT(RBESTD,NUMTEACH,SLOTB,SORTFLAG,IER)
         END IF
         LOOKP=1
         DO WHILE ((NOTYET .EQ. 0) .AND. (LOOKP .LE. NUMTEACH))
           TPER=SLOTB(LOOKP)
           IF  ((RESTART(TPER) .EQ. 1) .OR. (TRY .GT. 1)) THEN
            LOOKP=LOOKP + 1
           ELSE
            NOTYET=1
            CONMEM=TPER
           END IF
          END DO
          END IF
                   
            IF (NOTYET .EQ. 0) THEN
             MKCOUNT2=KCOUNT2-5
             WRITE(33,89898) 'ITERATIONS ENDED BECAUSE A NEW GROUP WAS'
             WRITE(33,89898) 'CALLED FOR BUT THERE ARE NOT ENOUGH '
             WRITE(33,89898) 'ELIGIBLE SEED ACTORS.'
           ELSE
         IF (ELGC .GT. 2) THEN
         
         CALL KMULTMA3(ELGC,RCHOICE,DIRECT,COLWT,ROWWT,
     C             ONLIST,1,PERSON1,PERSON2,ELGLIST,CONMEM,NUMTEACH)
         ELSE
         PERSON1=ELGLIST(1)
         IF (ELGC .GT. 1) THEN
         PERSON2=ELGLIST(2)
         ELSE
         PERSON2=CONMEM
         END IF
         END IF

             RESTART(CONMEM)=1
             USESEED(CONMEM)=USESEED(CONMEM)+1
             NEEDNEW=1
             OLDDEPT=NEWDEPT(CONMEM)
             OLOWMEM=CONMEM
             MADECHNG=1
             MAXDEPT=MAXDEPT+1
             IF (PERSON1 .GT. 0) THEN
             USESEED(PERSON1)=USESEED(PERSON1)+1
             NEWDEPT(PERSON1)=MAXDEPT
             END IF
             IF (PERSON2 .GT. 0) THEN
             USESEED(PERSON2)=USESEED(PERSON2)+1
             NEWDEPT(PERSON2)=MAXDEPT
             END IF
             NEWDEPT(CONMEM)=MAXDEPT
             INEWGRP(MAXDEPT)=1
             CREATOG(MAXDEPT)=1
        IF (PRINTO(8) .EQ. 1) THEN
             WRITE(33,1339) (CUTOFF+1),NSUBID(CONMEM),
     C NSUBID(PERSON1),NSUBID(PERSON2)
        END IF
        IF ((PRINTO(23) .EQ. 1) .AND. (PRINTO(24) .EQ. 1)) THEN
             WRITE(6,1339) (CUTOFF+1),NSUBID(CONMEM),
     C NSUBID(PERSON1),NSUBID(PERSON2)
        END IF


           END IF
C           ENDING ON ELSE CALL KMULTMAT
C            WHICH IS REALLY IF NOTYET .EQ. 0

         END IF
C          ENDING ON IF TRY .LE. 1
         IF (TRY .GT. 1) THEN
             MADECHNG=0
             ISOLIST(ISO)=LOWMEM
C              WRITE(214,251) ISO,ISOLIST(ISO)
             ISO=ISO+1
         END IF

         END IF
C        IF (BESTD .GT. NEARVAL)


        END IF

C        IF NOPICK

      IF (MADECHNG .EQ. 1) THEN
        ISO=1
C       IF (DEBUG(23) .EQ. 1) THEN
        KCOUNT2=KCOUNT2+1

        IF (TRY .EQ. 2) THEN
        ATTACHL(LOWMEM)=0
        END IF

        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN,RCHOICE,MEANWT,VARWT,
     C  1,2) 
        CALL REMOVEO4(MAXDEPT,DEPARTN,LGROUP,1,CUTOFF,QUICKEND)
        DO 56 RP1=1,NUMTEACH
          NEWDEPT(RP1)=LGROUP(NEWDEPT(RP1))
00056    CONTINUE
        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN,RCHOICE,MEANWT,VARWT,
     C  1,2) 
C        END IF

C     IF ((DEPARTN(THED(LOWMEM)) .LT. 2)  .AND. 
C     C    (RCHOICE(ALLGROUP(THED(LOWMEM),1)) .LT. 1)) THEN NOPICK=1

        IF ((PRINTO(8) .EQ. 1) .AND. (NEEDNEW .EQ. 0) ) THEN
        WRITE(33,136) NSUBID(LOWMEM),OLDDEPT,NEWDEPT(LOWMEM),KCOUNT2
        WRITE(33,102) 
        IF (DONEIT .EQ. 1) THEN
        WRITE(33,1364) OLDDEPT
        WRITE(33,102) 
        END IF
        END IF
         IF (OLDDEPT .GT. 0) THEN
         OLDDEPT=LGROUP(OLDDEPT)
         END IF
C         LDEPART=LGROUP(LDEPART)

        DO 780 Z=1,MAXDEPT
         CINEWGRP(Z)=INEWGRP(Z)
         CCREATOG(Z)=CREATOG(Z)
00780     CONTINUE
 
       DO 480 Z=1,MAXDEPT
         INEWGRP(Z)=CINEWGRP(LGROUP(Z))
         CREATOG(Z)=CCREATOG(LGROUP(Z))
00480     CONTINUE

      END IF
C    madechnge = 1
      ELSE 
      NOWSTOP=1
      END IF
C      QUICKEND
      ELSE
       NOWSTOP=1
      END IF
C      (CHANGEC .GT. STOPVAL)
      END DO
C     WQWQ
        
          WRITE(33,1747) KCOUNT2, ' ITERATIONS FOR THIS PHASE'
          WRITE(33,102)
        IF (TRY .EQ. 1) THEN 
       HAVEISO=0
       B=MAXDEPT
       DO WHILE ((HAVEISO .EQ. 0) .AND. (B .GT. 0) )
       IF (DEPARTN(B) .EQ. 1) THEN
       HAVEISO=1
       END IF
       B=B-1
       END DO
       END IF



        IF ((QUICKEND .NE. 1) .AND. (STRUCTEQ .NE. 1)) THEN
        HADTO=0
        DO 987 CZ=1,NUMTEACH
         IF (DEPARTN(NEWDEPT(CZ)) .GT. 1) THEN
         TEMPCON=0
         THISDEPT=NEWDEPT(CZ)
         DO 3368 BZ=1,DEPARTN(THISDEPT)
         IF (ALLGROUP(THISDEPT,BZ) .NE. CZ) THEN
         TEMPCON=TEMPCON+NEWMAT(CZ,ALLGROUP(THISDEPT,BZ))+
     C   NEWMAT(ALLGROUP(THISDEPT,BZ),CZ)
         END IF
03368    CONTINUE
         IF (TEMPCON .LE. 0) THEN
         HADTO=1
         MAXDEPT=MAXDEPT+1
         IF (PRINTO(8) .EQ. 1) THEN
         WRITE(33,3341) CZ,NEWDEPT(CZ)
         END IF
         NEWDEPT(CZ)=MAXDEPT
         END IF
         END IF
C        DEPARTN(NEWDEPT(CZ) .GT. 1)

        IF ((TRY .GE. 2) .OR. (DEPARTN(NEWDEPT(CZ)) .LT. 2)) THEN
        ATTACHL(CZ)=1
        ELSE
        ATTACHL(CZ)=0
        END IF
00987    CONTINUE

         IF (HADTO .EQ. 1) THEN
        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN,RCHOICE,MEANWT,VARWT,
     C  1,2) 

           UNO=1
        CALL REMOVEO4(MAXDEPT,DEPARTN,LGROUP,UNO,CUTOFF,QUICKEND)
        DO 6651 RP1=1,NUMTEACH
         NEWDEPT(RP1)=LGROUP(NEWDEPT(RP1))
         ZDEPT(RP1)=NEWDEPT(RP1)
06651    CONTINUE

        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN,RCHOICE,MEANWT,VARWT,
     C  1,2) 
         END IF
        END IF
        IF ((QUICKEND .EQ. 1) .OR. 
     C     ((HADTO .EQ. 0) .AND. (HAVEISO .EQ. 0))) THEN
        TRY=TRY+4
        IF (QUICKEND .EQ. 1) THEN
        WRITE(33,102) 'ASKED FOR QUICK END'
        ELSE
        WRITE(33,102) 'NO ISOLATES, PHASES COMPLETE'
        END IF

        ELSE

          WRITE(33,102) IHEAD(TRY)
          WRITE(33,102)
          IF (PRINTO(24) .EQ. 1) THEN
          WRITE(6,102) IHEAD(TRY)
          WRITE(6,102)
          END IF
        END IF

        DVAL=ABS(BOUNDVAL-FINEVAL)
C        IF ((PCTILE .LT. 1) .AND. (DVAL .LT. BOUNDVAL) .AND.
C     C   (USEBOUND .LT. BOUNDVAL)) THEN
C        USEBOUND=FINEVAL
C        ELSE
        USEBOUND=BOUNDVAL
C        END IF

C        BLABOUND=.05
         IF (STRUCTEQ .EQ. 0) THEN
        PCTILE=2.0
        NEARVAL=-999
        END IF
        IF (QUANTYPE .EQ. 4) THEN
        PCTILE=2.0
        IF (TRY .EQ. 1) THEN
        NEARVAL=-999
        ELSE
        NEARVAL=0
        END IF
        END IF

        
        TRY=TRY+1
        IF (ATTACHI .EQ. 0) THEN
        TRY=TRY+4
         END IF

C         QUICKEND=1

        DIDIT=1
        CHANGEC(LOWMEM)=STOPVAL+10000.000
         END DO


          IF (PRINTO(1) .EQ. 1) THEN
          WRITE(33,132)
         WRITE(33,2101) ' (N)    '
        DO 82 Z=1,MAXDEPT
          IF (DEPARTN(Z) .GT. 0) THEN
          WRITE(33,133) Z , (NSUBID(ALLGROUP(Z,P)) , P=1,DEPARTN(Z))
          WRITE(33,134) DEPARTN(Z),
     C         (NOWCLOSE(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,137) 'BEST G',
     C         (BESTD(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
          WRITE(33,2137) 'GROUP',
     C         (THED(ALLGROUP(Z,P2)), P2=1,DEPARTN(Z))
           END IF
          DNUM(Z)=Z
   82   CONTINUE
         END IF
       LMAXDEPT=MAXDEPT
         HADTO=0
         DO 00088 IB=1,NUMTEACH
        IF ((NONEG .EQ. 1) .AND. (NOWCLOSE(IB) .LT. 0)) THEN
        HADTO=1
        MAXDEPT=MAXDEPT+1
        WRITE(33,1365) IB,NEWDEPT(IB)
        NEWDEPT(IB)=MAXDEPT
        END IF
00088           CONTINUE
         IF (HADTO .EQ. 1) THEN
        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN,RCHOICE,MEANWT,VARWT,
     C  1,2) 
         END IF

           UNO=1
        CALL REMOVEO4(MAXDEPT,DEPARTN,LGROUP,UNO,CUTOFF,QUICKEND)
        DO 656 RP1=1,NUMTEACH
         NEWDEPT(RP1)=LGROUP(NEWDEPT(RP1))
00656    CONTINUE

        CALL ASSIGN(NUMTEACH,NEWDEPT,MAXDEPT,
     C  DEPARTN,RCHOICE,MEANWT,VARWT,
     C  1,2) 
       MKCOUNT2=TKC
        NEARVAL=GNEARVAL
        PCTILE=GPCTILE 
C        END SASCENT

       CLOSE(20)
       RETURN
05843  FORMAT(' Reassigning actor ',I4,' to subgroup ',I4,
     C ' because the actor''s current group, ',I4,
     C ' was dissolved.')
03252 FORMAT(//,'---------------------------------------------',//)

    
 2105 FORMAT(A16,251(I5,1X))  
 2104 FORMAT(A16,251(F5.2,1X))  
 2102 FORMAT(10(A30)) 
89898 FORMAT(A,I5,30(A,F10.5))
 2101 FORMAT(251(A8)) 
 1747 FORMAT(I5,A)
  144 FORMAT(2F10.5)
C
  251 FORMAT(20(G15.5))
 2103 FORMAT(I8,I8,251(F5.2,1X))  
 2107 FORMAT(A16,251(I5,1X))  
  103 FORMAT(F8.1,251(F5.2,1X))  
  105 FORMAT(A15,251(I5,1X))  
  104 FORMAT(A15,251(F5.2,1X))  
  102 FORMAT(10(A30)) 
  101 FORMAT(251(A8)) 
89897   FORMAT(10(A))
  132 FORMAT(' GROUP    ACTORS')
  133 FORMAT(I4,4X,251(2X,I8,2X))
C 2102 FORMAT(251(A8))
  134 FORMAT('(',I4,')',4X,251(:,'(',:,E10.4,')'))
  137 FORMAT(A6,4X,251(:,'(',:,E10.4,')'))
 2137 FORMAT(A6,4X,251(:,'(',:,I10,')'))
  136 FORMAT(' HAVE MOVED ',I4,' FROM ',I4,' TO ',I4,' ITERATION #',I5)
 1365  FORMAT (' HAVE REASSIGNED ',I4,' FROM GROUP ',I4,
     C ' BECAUSE OF NEGATIVE ',
     C 'CONBTRIBUTION TO THE OBJECTIVE FUNCTION')
03341  FORMAT(' DETACHING ',I4, ' BECAUSE IT IS NOT CONNECTED TO ',
     C 'MEMBERS OF ITS GROUP, GROUP ',I4)
 1364 FORMAT(' HAVE DISBANDED MEMBERS OF ',I4,' DUE TO ZERO ROW',
     C ' MARGINALS')
  139 FORMAT(' WANT TO MOVE ',I4,' FROM ',I4,' TO ',I4)
02339 FORMAT(' ACTOR ',I5,' HAS ASSOCIATION OF ',E10.2,
     C ' WITH GROUP',I5,
     C/,'  WHICH IS NOT GREATER THAN THE CURRENT NEARVAL OF ',E10.2)
01339 FORMAT(' STARTING NEW GROUP # ',I5,' AROUND ',I5,' WITH ',
     CI5,' AND ',I5)
01349  FORMAT(' THERE ARE MORE THAN THREE ISOLATED ACTORS SO A',/,
     C ' GROUP WILL BE FORMED RATHER THAN CONVERGING AT THIS POINT',/
     C ' WITH MOVE OF ACTOR ',I5,' TO GROUP ',I5,' AND CHANGE VALUE',
     C /,' OF ',F10.5, ' .')

      END
