
      SUBROUTINE SLOGIT(MAXDEPT,DEPARTN,NUMTEACH,
     C NEWDEPT,COVMAT,FCOMPACT,TSS,WBSS,GROUPMAT,
     C ROWWT,COLWT,KQMAX)
      INCLUDE 'PARAM.H'

C LABEL,TITLES,PRINTT,KEEPLIST,

      REAL SS(MAXKLIQ,MAXKLIQ),GROUPMAT(MAXKLIQ,MAXKLIQ),
     C GRMEAN(MAXKLIQ,MAXKLIQ),GRVAR(MAXKLIQ,MAXKLIQ),NOB,TWEIGHT,
     C STOTCON,AMEAN,AVAR,MDIAG,VDIAG,CDIAG,
     C COVMAT(MAXGR,MAXGR),COLWT,ROWWT,
     C FCOMPACT,HUBSIM,STDHS,OUTOF,ZABS,PCON,
     C CHNGSIM,CHNGSTD,WBSS,TSS,WSS
      
      INTEGER MAXDEPT,DEPARTN(MAXKLIQ),KQMAX,
     C NUMTEACH,RCHOICE(MAXKLIQ),NEWDEPT(MAXKLIQ),
     C GROUP1,GROUP2,DMEMBERS(MAXKLIQ),THISPER,KTEMPS,I,J,
     C LMAXDEPT,LGROUP(MAXKLIQ),WANTSS,KDEPT,DMAXD,THISNI,THISNJ
     C K,LENGTH,NO2,G1,G2,G3,NEWORDER(MAXKLIQ),PRINTT,FINAL,FSYMMAT,
     C SAMEG,I2,OBSCONO(MAXKLIQ),OBSCONI(MAXKLIQ),DUMDEPT(MAXKLIQ)

       REAL ALLCON,CHNGCON,PC,DGROUPMA(MAXKLIQ,MAXKLIQ)

       REAL KSIGN,KCHISQR,KCHISQRI(MAXKLIQ),KCHISQRO(MAXKLIQ),
     C CHIMEANI(MAXKLIQ),CHIMEANO(MAXKLIQ),CHIVARI(MAXKLIQ),
     C CHIVARO(MAXKLIQ),TOTCHII,TOTCHIO,GEXPECT(MAXKLIQ),
     C GVAR(MAXKLIQ),GCENTRAL(MAXKLIQ),GCON(MAXKLIQ)
       REAL ZCOMPMAT(MAXKLIQ,MAXKLIQ)
       INTEGER HUBERT(MAXKLIQ,MAXKLIQ),RESULTM(MAXKLIQ,MAXKLIQ),
     C ALLGROUP(MAXKLIQ,MAXKLIQ),NEWMAT(MAXKLIQ,MAXKLIQ)
       REAL BLAUC(MAXKLIQ,MAXKLIQ),DIFF(MAXKLIQ,MAXKLIQ)
       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT,
     C BLAUC,DIFF

C       COMMON ZCOMPMAT,ALLGROUP,HUBERT,RESULTM,NEWMAT

      NO=1
      NOB=0.0000
      TWEIGHT=1.0000
      WANTSS=1
      
      DO 11 I=1,MAXDEPT
        DO 13 J=1,MAXDEPT
       COVMAT(I,J)=0
00013 CONTINUE 
      DO 12 J=1,NUMTEACH
       GRMEAN(I,J)=0.0
       GRVAR(I,J)=0.0
00012   CONTINUE
00011   CONTINUE
      
      CALL GETMEAN(NEWDEPT,NUMTEACH,GROUPMAT,MAXDEPT,
     C DEPARTN,WANTSS,SS,WSS,ROWWT,COLWT)

       DO 98 G1=1,MAXDEPT
       DO 998 G2=1,G1
       DO 99 J=1,NUMTEACH
       COVMAT(G1,G2)=COVMAT(G1,G2)+
     C  (GROUPMAT(G1,J)-GROUPMAT(G2,J))**2
00099   CONTINUE
00998    CONTINUE
00098     CONTINUE

       WBSS=0.00       
      DO 04 I=1,MAXDEPT
      DO 05 J=1,NUMTEACH
       GRMEAN(I,NEWDEPT(J))=GRMEAN(I,NEWDEPT(J))+GROUPMAT(I,J)
       GRVAR(I,NEWDEPT(J))=SS(I,NEWDEPT(J))+SS(I,J)
        WBSS=WBSS+SS(I,J)
00005   CONTINUE
00004   CONTINUE

       DO 06 I=1,MAXDEPT
       COVMAT(I,I)=GRVAR(I,I)/(DEPARTN(I)*MAXDEPT)
00006     CONTINUE

        DO 008 I=1,NUMTEACH
         DUMDEPT(I)=1
00008     CONTINUE
        
         TSS=0
         DMAXD=1
         KDEPT=DEPARTN(1)
         DEPARTN(1)=NUMTEACH
      CALL GETMEAN(DUMDEPT,NUMTEACH,DGROUPMA,DMAXD,
     C DEPARTN,WANTSS,SS,WSS,1.0,0.0)
          DEPARTN(1)=KDEPT
          DO 010 J=1,NUMTEACH
          TSS=TSS+SS(1,J)
00010      CONTINUE

           FCOMPACT=1-WBSS/TSS

       
   62 FORMAT(I2)
  512 FORMAT(3(A20,1X))
  513 FORMAT(10X,3(A20,1X))
  517 FORMAT(10X,A40)
   77 FORMAT('MATRIX OF GROUP ASSOCIATION',/)
  102 FORMAT(I2,251(I1))
  105 FORMAT(251(I1))
  193 FORMAT(/,A3,4(2X,A25),/)
  194 FORMAT(/,10(2X,A15),/)
  195 FORMAT(/,10(2X,F15.5),/)   
  192 FORMAT(I3,6X,I10,6X,6X,I10,6X,12X,F10.5,6X,6X,F10.5,6X,/)
  191 FORMAT(/,'SIMILARITY BETWEEN THE START AND END GROUPS:   ACTUAL 
     C  POSS  STANDARDIZED',/,45X,I10,I10,F10.5)
  301 FORMAT(I4,1X,251(F5.2,1X))
  302 FORMAT(A4,1X,251(F5.2,1X))
  103 FORMAT(20(F7.3))
  101 FORMAT(I2,251(I1))
  251 FORMAT(25(F10.5)) 
      RETURN
      END
