
      SUBROUTINE SORTMAT(INMAT,MAXG,CURPLACE,COMPARE,CENT,TSIZE)
      INCLUDE 'PARAM.H'
      INTEGER MAXG,ORDER(MAXGR),CHANGE,COMPARE,I,J,CURPLACE(MAXG),H,
     C INORD,MOVEG,TOG,KTOG,THISG,TOPVAL,TSIZE,USESORT,
     C SORTFLAG,IER
      REAL INMAT(MAXGR,MAXGR),COMPMAT(MAXGR,MAXGR),HIVAL,
     C NEWCONT,DENOM,IMPVAL,CURVAL,CENT(MAXKLIQ),MISSVAL

      HIVAL=-999999
      TOPVAL=999
      MISSVAL=20

      
      DO 2 I=2,MAXG
      DO 3 J=1,(I-1)
      IF (J .NE. I) THEN

      IF (ABS(COMPARE) .EQ. 1) THEN
      COMPMAT(I,J)=INMAT(I,J)-INMAT(J,I)
      END IF

      IF (ABS(COMPARE) .EQ. 2) THEN
        DENOM=INMAT(J,I)
        IF (ABS(INMAT(J,I)) .LT. .0001) THEN
          DENOM=.01
        END IF
        IF (ABS(INMAT(I,J)) .LE. .0000001) THEN
          IF (INMAT(J,I) .LT. 0) THEN
             COMPMAT(I,J)=MISSVAL
          ELSE
C    GGG
            COMPMAT(I,J)=-MISSVAL
          END IF
        ELSE
          COMPMAT(I,J)=LOG(INMAT(I,J)/DENOM)
        END IF
      END IF

C      IF (ABS(COMPMAT(I,J)) .GT. HIVAL) THEN
C      HIVAL=ABS(COMPMAT(I,J))
C      IF (COMPMAT(I,J) .GT. 0) THEN
C      ORDER(1)=I
C      ORDER(2)=J
C      ELSE
C      ORDER(1)=J
C      ORDER(2)=I
C     END IF
C     END IF

       END IF
      IF (COMPARE .GT. 0) THEN
      COMPMAT(I,J)=-COMPMAT(I,J)
      END IF
      COMPMAT(J,I)=-COMPMAT(I,J)

      
00003  CONTINUE
       COMPMAT(I,I)=0
        CURPLACE(I)=TOPVAL
00002   CONTINUE
       COMPMAT(1,1)=0
C       CURPLACE(ORDER(1))=1
C       CURPLACE(ORDER(2))=2

      DO 22 I=1,MAXG
      CENT(I)=0
      ORDER(I)=I
      DO 33 J=1,MAXG
      CENT(I)=CENT(I)-COMPMAT(I,J)
00033  CONTINUE
00022   CONTINUE
         USESORT=0
       IF (MAXG .GT. 1) THEN
       SORTFLAG=2
       CALL SPSORT(CENT,MAXG,ORDER,SORTFLAG,IER)
        END IF
       DO 23 I=1,MAXG
       CURPLACE(ORDER(I))=I
00023   CONTINUE


       INORD=MAXG-1

C       DO 77 I=1,MAXG
C       IF (CURPLACE(I) .EQ. TOPVAL) THEN
C       INORD=INORD+1
C       CURPLACE(I)=INORD
C       ORDER(INORD)=I
C      END IF
C00077  CONTINUE

      CHANGE=1
      DO WHILE (CHANGE .EQ. 1)
      CHANGE=0
      HIVAL=0
      DO 4 I=1,MAXG
      CURVAL=0
      IF (CURPLACE(I) .LT. MAXG) THEN
      DO 322 H=(CURPLACE(I)+1),(INORD)
      CURVAL=CURVAL+COMPMAT(I,ORDER(H))
00322  CONTINUE
      END IF
      DO 5 J=1,(INORD+1)
      IF ((J .NE. (CURPLACE(I) +1)) .AND. 
     C (J .NE. CURPLACE(I))) THEN
      NEWCONT=0      
      DO 6 H=J,(INORD)
      NEWCONT=NEWCONT+COMPMAT(I,ORDER(H))
00006 CONTINUE
      IMPVAL=NEWCONT-CURVAL
      IF (IMPVAL .GT. HIVAL) THEN
      HIVAL=IMPVAL
      MOVEG=I
      KTOG=J
      CHANGE=1
      END IF
      END IF
00005  CONTINUE
00004   CONTINUE
      IF (CHANGE .EQ. 1) THEN
       DO 7 I=1,INORD
        THISG=ORDER(I)
        IF (THISG .NE. MOVEG) THEN
         IF ((I .LT. CURPLACE(MOVEG)) 
     C  .AND. (I .GE. KTOG)) THEN
         CURPLACE(THISG)=CURPLACE(THISG)+1
         END IF

         IF ((I .GT. CURPLACE(MOVEG))
     C   .AND. (I .LT. KTOG)) THEN
         CURPLACE(THISG)=CURPLACE(THISG) -1
         END IF
        END IF
00007   CONTINUE
        IF (KTOG .GT. CURPLACE(MOVEG)) THEN
        KTOG=KTOG-1
        END IF
        CURPLACE(MOVEG)=KTOG

       INORD=0
       DO 8 I=1,MAXG
       IF ((CURPLACE(I) .GT. 0) .AND. 
     C (CURPLACE(I) .LE. MAXG)) THEN
       ORDER(CURPLACE(I))=I
       IF (CURPLACE(I) .LT. MAXG) THEN
       INORD=INORD+1
       END IF
       END IF
00008   CONTINUE
       IF (INORD .EQ. (MAXG-1)) THEN
       INORD=MAXG
       END IF
       END IF

       END DO
       RETURN
       END
