C     END SUBROUTINE ASSIGN2
C
C
C     BEGIN FUNCTION TOTWI
C
      SUBROUTINE TOTWI(INGROUP,THISGRP,NUMGROUP,PATTERN,STARTER,
     C                   ICOVAR,IEXPECT,ITOT,ICONNECT)
      INCLUDE 'PARAM.H'
      REAL NUMTOT,ICOVAR(MAXKLIQ),IEXPECT(MAXKLIQ)
      REAL CONGROUP(MAXKLIQ),PRELATE
      INTEGER MEMBER,EASY,OTHERMEM,INGROUP(MAXKLIQ,MAXKLIQ)
      INTEGER PATTERN(MAXKLIQ,MAXKLIQ)
      INTEGER STARTER,NUMGROUP,I,J,THISGRP,ICONNECT(MAXKLIQ)
      INTEGER TTOTWI
      REAL ITOT
C     INGROUP IS AN ARRAY OF THE ID'S OF THE PEOPLE IN THE GROUPS
C     NUMTOT IS THE TOTAL NUMBER OF TEACHERS
C     NUMGROUP IS THE NUMBER OF PEOPLE IN THE GROUP
C     PATTERN IS THE MATRIX OF RELATION PATTERNS
C     PRELATE IS THE PROPORTION OF PATTERNS WITHIN THE MATRIX
C     
       TTOTWI=STARTER
       DO 200  I =1,NUMGROUP
       CONGROUP(I)=0
       MEMBER=INGROUP(THISGRP,I)
       DO 300 J = 1,NUMGROUP
C         IF (J .NE. I) THEN
         OTHERMEM=INGROUP(THISGRP,J)
         CONGROUP(I)=CONGROUP(I)+PATTERN(MEMBER,OTHERMEM)
C         IF (THISGRP .EQ. 3) THEN 
C         WRITE(16,993) MEMBER,OTHERMEM,PATTERN(MEMBER,OTHERMEM)
C         END IF
C        END IF 
 300   CONTINUE
       ICONNECT(MEMBER)=CONGROUP(I)
       TTOTWI=TTOTWI+CONGROUP(I)
       ICOVAR(MEMBER)=TTOTWI-IEXPECT(MEMBER)
  200  CONTINUE
       ITOT=TTOTWI
  993 FORMAT('MEMBER=',F4.0,' OTHER=',F4.0,' PATT=',F4.0)
       RETURN
       END
